// Generated by entc-win32gen from `Windows.Win32.Security.Authorization`.
// Do not edit by hand. Re-run the generator to refresh.

typedef unsigned char       BYTE;
typedef unsigned short      WORD;
typedef unsigned long       DWORD;
typedef unsigned long long  ULONGLONG;
typedef long                LONG;
typedef unsigned long       ULONG;
typedef int                 BOOL;
typedef void*               PVOID;
typedef void*               HANDLE;

#define SDDL_REVISION_1 0x1
#define SDDL_REVISION 0x1
// SKIPPED const SDDL_OWNER: non-integer constant
// SKIPPED const SDDL_GROUP: non-integer constant
// SKIPPED const SDDL_DACL: non-integer constant
// SKIPPED const SDDL_SACL: non-integer constant
// SKIPPED const SDDL_PROTECTED: non-integer constant
// SKIPPED const SDDL_AUTO_INHERIT_REQ: non-integer constant
// SKIPPED const SDDL_AUTO_INHERITED: non-integer constant
// SKIPPED const SDDL_NULL_ACL: non-integer constant
// SKIPPED const SDDL_ACCESS_ALLOWED: non-integer constant
// SKIPPED const SDDL_ACCESS_DENIED: non-integer constant
// SKIPPED const SDDL_OBJECT_ACCESS_ALLOWED: non-integer constant
// SKIPPED const SDDL_OBJECT_ACCESS_DENIED: non-integer constant
// SKIPPED const SDDL_AUDIT: non-integer constant
// SKIPPED const SDDL_ALARM: non-integer constant
// SKIPPED const SDDL_OBJECT_AUDIT: non-integer constant
// SKIPPED const SDDL_OBJECT_ALARM: non-integer constant
// SKIPPED const SDDL_MANDATORY_LABEL: non-integer constant
// SKIPPED const SDDL_PROCESS_TRUST_LABEL: non-integer constant
// SKIPPED const SDDL_CALLBACK_ACCESS_ALLOWED: non-integer constant
// SKIPPED const SDDL_CALLBACK_ACCESS_DENIED: non-integer constant
// SKIPPED const SDDL_RESOURCE_ATTRIBUTE: non-integer constant
// SKIPPED const SDDL_SCOPED_POLICY_ID: non-integer constant
// SKIPPED const SDDL_CALLBACK_AUDIT: non-integer constant
// SKIPPED const SDDL_CALLBACK_OBJECT_ACCESS_ALLOWED: non-integer constant
// SKIPPED const SDDL_ACCESS_FILTER: non-integer constant
// SKIPPED const SDDL_INT: non-integer constant
// SKIPPED const SDDL_UINT: non-integer constant
// SKIPPED const SDDL_WSTRING: non-integer constant
// SKIPPED const SDDL_SID: non-integer constant
// SKIPPED const SDDL_BLOB: non-integer constant
// SKIPPED const SDDL_BOOLEAN: non-integer constant
// SKIPPED const SDDL_CONTAINER_INHERIT: non-integer constant
// SKIPPED const SDDL_OBJECT_INHERIT: non-integer constant
// SKIPPED const SDDL_NO_PROPAGATE: non-integer constant
// SKIPPED const SDDL_INHERIT_ONLY: non-integer constant
// SKIPPED const SDDL_INHERITED: non-integer constant
// SKIPPED const SDDL_CRITICAL: non-integer constant
// SKIPPED const SDDL_TRUST_PROTECTED_FILTER: non-integer constant
// SKIPPED const SDDL_AUDIT_SUCCESS: non-integer constant
// SKIPPED const SDDL_AUDIT_FAILURE: non-integer constant
// SKIPPED const SDDL_READ_PROPERTY: non-integer constant
// SKIPPED const SDDL_WRITE_PROPERTY: non-integer constant
// SKIPPED const SDDL_CREATE_CHILD: non-integer constant
// SKIPPED const SDDL_DELETE_CHILD: non-integer constant
// SKIPPED const SDDL_LIST_CHILDREN: non-integer constant
// SKIPPED const SDDL_SELF_WRITE: non-integer constant
// SKIPPED const SDDL_LIST_OBJECT: non-integer constant
// SKIPPED const SDDL_DELETE_TREE: non-integer constant
// SKIPPED const SDDL_CONTROL_ACCESS: non-integer constant
// SKIPPED const SDDL_READ_CONTROL: non-integer constant
// SKIPPED const SDDL_WRITE_DAC: non-integer constant
// SKIPPED const SDDL_WRITE_OWNER: non-integer constant
// SKIPPED const SDDL_STANDARD_DELETE: non-integer constant
// SKIPPED const SDDL_GENERIC_ALL: non-integer constant
// SKIPPED const SDDL_GENERIC_READ: non-integer constant
// SKIPPED const SDDL_GENERIC_WRITE: non-integer constant
// SKIPPED const SDDL_GENERIC_EXECUTE: non-integer constant
// SKIPPED const SDDL_FILE_ALL: non-integer constant
// SKIPPED const SDDL_FILE_READ: non-integer constant
// SKIPPED const SDDL_FILE_WRITE: non-integer constant
// SKIPPED const SDDL_FILE_EXECUTE: non-integer constant
// SKIPPED const SDDL_KEY_ALL: non-integer constant
// SKIPPED const SDDL_KEY_READ: non-integer constant
// SKIPPED const SDDL_KEY_WRITE: non-integer constant
// SKIPPED const SDDL_KEY_EXECUTE: non-integer constant
// SKIPPED const SDDL_NO_WRITE_UP: non-integer constant
// SKIPPED const SDDL_NO_READ_UP: non-integer constant
// SKIPPED const SDDL_NO_EXECUTE_UP: non-integer constant
#define SDDL_ALIAS_SIZE 0x2
// SKIPPED const SDDL_DOMAIN_ADMINISTRATORS: non-integer constant
// SKIPPED const SDDL_DOMAIN_GUESTS: non-integer constant
// SKIPPED const SDDL_DOMAIN_USERS: non-integer constant
// SKIPPED const SDDL_ENTERPRISE_DOMAIN_CONTROLLERS: non-integer constant
// SKIPPED const SDDL_DOMAIN_DOMAIN_CONTROLLERS: non-integer constant
// SKIPPED const SDDL_DOMAIN_COMPUTERS: non-integer constant
// SKIPPED const SDDL_BUILTIN_ADMINISTRATORS: non-integer constant
// SKIPPED const SDDL_BUILTIN_GUESTS: non-integer constant
// SKIPPED const SDDL_BUILTIN_USERS: non-integer constant
// SKIPPED const SDDL_LOCAL_ADMIN: non-integer constant
// SKIPPED const SDDL_LOCAL_GUEST: non-integer constant
// SKIPPED const SDDL_ACCOUNT_OPERATORS: non-integer constant
// SKIPPED const SDDL_BACKUP_OPERATORS: non-integer constant
// SKIPPED const SDDL_PRINTER_OPERATORS: non-integer constant
// SKIPPED const SDDL_SERVER_OPERATORS: non-integer constant
// SKIPPED const SDDL_AUTHENTICATED_USERS: non-integer constant
// SKIPPED const SDDL_PERSONAL_SELF: non-integer constant
// SKIPPED const SDDL_CREATOR_OWNER: non-integer constant
// SKIPPED const SDDL_CREATOR_GROUP: non-integer constant
// SKIPPED const SDDL_LOCAL_SYSTEM: non-integer constant
// SKIPPED const SDDL_POWER_USERS: non-integer constant
// SKIPPED const SDDL_EVERYONE: non-integer constant
// SKIPPED const SDDL_REPLICATOR: non-integer constant
// SKIPPED const SDDL_INTERACTIVE: non-integer constant
// SKIPPED const SDDL_NETWORK: non-integer constant
// SKIPPED const SDDL_SERVICE: non-integer constant
// SKIPPED const SDDL_RESTRICTED_CODE: non-integer constant
// SKIPPED const SDDL_WRITE_RESTRICTED_CODE: non-integer constant
// SKIPPED const SDDL_ANONYMOUS: non-integer constant
// SKIPPED const SDDL_SCHEMA_ADMINISTRATORS: non-integer constant
// SKIPPED const SDDL_CERT_SERV_ADMINISTRATORS: non-integer constant
// SKIPPED const SDDL_RAS_SERVERS: non-integer constant
// SKIPPED const SDDL_ENTERPRISE_ADMINS: non-integer constant
// SKIPPED const SDDL_GROUP_POLICY_ADMINS: non-integer constant
// SKIPPED const SDDL_ALIAS_PREW2KCOMPACC: non-integer constant
// SKIPPED const SDDL_LOCAL_SERVICE: non-integer constant
// SKIPPED const SDDL_NETWORK_SERVICE: non-integer constant
// SKIPPED const SDDL_REMOTE_DESKTOP: non-integer constant
// SKIPPED const SDDL_NETWORK_CONFIGURATION_OPS: non-integer constant
// SKIPPED const SDDL_PERFMON_USERS: non-integer constant
// SKIPPED const SDDL_PERFLOG_USERS: non-integer constant
// SKIPPED const SDDL_IIS_USERS: non-integer constant
// SKIPPED const SDDL_CRYPTO_OPERATORS: non-integer constant
// SKIPPED const SDDL_OWNER_RIGHTS: non-integer constant
// SKIPPED const SDDL_EVENT_LOG_READERS: non-integer constant
// SKIPPED const SDDL_ENTERPRISE_RO_DCs: non-integer constant
// SKIPPED const SDDL_CERTSVC_DCOM_ACCESS: non-integer constant
// SKIPPED const SDDL_ALL_APP_PACKAGES: non-integer constant
// SKIPPED const SDDL_RDS_REMOTE_ACCESS_SERVERS: non-integer constant
// SKIPPED const SDDL_RDS_ENDPOINT_SERVERS: non-integer constant
// SKIPPED const SDDL_RDS_MANAGEMENT_SERVERS: non-integer constant
// SKIPPED const SDDL_USER_MODE_DRIVERS: non-integer constant
// SKIPPED const SDDL_HYPER_V_ADMINS: non-integer constant
// SKIPPED const SDDL_CLONEABLE_CONTROLLERS: non-integer constant
// SKIPPED const SDDL_ACCESS_CONTROL_ASSISTANCE_OPS: non-integer constant
// SKIPPED const SDDL_REMOTE_MANAGEMENT_USERS: non-integer constant
// SKIPPED const SDDL_AUTHORITY_ASSERTED: non-integer constant
// SKIPPED const SDDL_SERVICE_ASSERTED: non-integer constant
// SKIPPED const SDDL_PROTECTED_USERS: non-integer constant
// SKIPPED const SDDL_KEY_ADMINS: non-integer constant
// SKIPPED const SDDL_ENTERPRISE_KEY_ADMINS: non-integer constant
// SKIPPED const SDDL_USER_MODE_HARDWARE_OPERATORS: non-integer constant
// SKIPPED const SDDL_OPENSSH_USERS: non-integer constant
// SKIPPED const SDDL_ML_LOW: non-integer constant
// SKIPPED const SDDL_ML_MEDIUM: non-integer constant
// SKIPPED const SDDL_ML_MEDIUM_PLUS: non-integer constant
// SKIPPED const SDDL_ML_HIGH: non-integer constant
// SKIPPED const SDDL_ML_SYSTEM: non-integer constant
// SKIPPED const SDDL_SEPERATOR: non-integer constant
// SKIPPED const SDDL_DELIMINATOR: non-integer constant
// SKIPPED const SDDL_ACE_BEGIN: non-integer constant
// SKIPPED const SDDL_ACE_END: non-integer constant
// SKIPPED const SDDL_ACE_COND_BEGIN: non-integer constant
// SKIPPED const SDDL_ACE_COND_END: non-integer constant
// SKIPPED const SDDL_SPACE: non-integer constant
// SKIPPED const SDDL_ACE_COND_BLOB_PREFIX: non-integer constant
// SKIPPED const SDDL_ACE_COND_SID_PREFIX: non-integer constant
// SKIPPED const SDDL_ACE_COND_ATTRIBUTE_PREFIX: non-integer constant
// SKIPPED const SDDL_ACE_COND_USER_ATTRIBUTE_PREFIX: non-integer constant
// SKIPPED const SDDL_ACE_COND_RESOURCE_ATTRIBUTE_PREFIX: non-integer constant
// SKIPPED const SDDL_ACE_COND_DEVICE_ATTRIBUTE_PREFIX: non-integer constant
// SKIPPED const SDDL_ACE_COND_TOKEN_ATTRIBUTE_PREFIX: non-integer constant
#define INHERITED_ACCESS_ENTRY 0x10
#define INHERITED_PARENT 0x10000000
#define INHERITED_GRANDPARENT 0x20000000
// SKIPPED const ACCCTRL_DEFAULT_PROVIDERA: non-integer constant
// SKIPPED const ACCCTRL_DEFAULT_PROVIDERW: non-integer constant
// SKIPPED const ACCCTRL_DEFAULT_PROVIDER: non-integer constant
#define TRUSTEE_ACCESS_ALLOWED 1
#define TRUSTEE_ACCESS_READ 2
#define TRUSTEE_ACCESS_WRITE 4
#define TRUSTEE_ACCESS_EXPLICIT 1
#define TRUSTEE_ACCESS_ALL -1
#define ACTRL_RESERVED 0x0
#define ACTRL_PERM_1 0x1
#define ACTRL_PERM_2 0x2
#define ACTRL_PERM_3 0x4
#define ACTRL_PERM_4 0x8
#define ACTRL_PERM_5 0x10
#define ACTRL_PERM_6 0x20
#define ACTRL_PERM_7 0x40
#define ACTRL_PERM_8 0x80
#define ACTRL_PERM_9 0x100
#define ACTRL_PERM_10 0x200
#define ACTRL_PERM_11 0x400
#define ACTRL_PERM_12 0x800
#define ACTRL_PERM_13 0x1000
#define ACTRL_PERM_14 0x2000
#define ACTRL_PERM_15 0x4000
#define ACTRL_PERM_16 0x8000
#define ACTRL_PERM_17 0x10000
#define ACTRL_PERM_18 0x20000
#define ACTRL_PERM_19 0x40000
#define ACTRL_PERM_20 0x80000
#define ACTRL_ACCESS_PROTECTED 0x1
#define ACTRL_SYSTEM_ACCESS 0x4000000
#define ACTRL_DELETE 0x8000000
#define ACTRL_READ_CONTROL 0x10000000
#define ACTRL_CHANGE_ACCESS 0x20000000
#define ACTRL_CHANGE_OWNER 0x40000000
#define ACTRL_SYNCHRONIZE 0x80000000
#define ACTRL_STD_RIGHTS_ALL 0xf8000000
#define ACTRL_FILE_READ 0x1
#define ACTRL_FILE_WRITE 0x2
#define ACTRL_FILE_APPEND 0x4
#define ACTRL_FILE_READ_PROP 0x8
#define ACTRL_FILE_WRITE_PROP 0x10
#define ACTRL_FILE_EXECUTE 0x20
#define ACTRL_FILE_READ_ATTRIB 0x80
#define ACTRL_FILE_WRITE_ATTRIB 0x100
#define ACTRL_FILE_CREATE_PIPE 0x200
#define ACTRL_DIR_LIST 0x1
#define ACTRL_DIR_CREATE_OBJECT 0x2
#define ACTRL_DIR_CREATE_CHILD 0x4
#define ACTRL_DIR_DELETE_CHILD 0x40
#define ACTRL_DIR_TRAVERSE 0x20
#define ACTRL_KERNEL_TERMINATE 0x1
#define ACTRL_KERNEL_THREAD 0x2
#define ACTRL_KERNEL_VM 0x4
#define ACTRL_KERNEL_VM_READ 0x8
#define ACTRL_KERNEL_VM_WRITE 0x10
#define ACTRL_KERNEL_DUP_HANDLE 0x20
#define ACTRL_KERNEL_PROCESS 0x40
#define ACTRL_KERNEL_SET_INFO 0x80
#define ACTRL_KERNEL_GET_INFO 0x100
#define ACTRL_KERNEL_CONTROL 0x200
#define ACTRL_KERNEL_ALERT 0x400
#define ACTRL_KERNEL_GET_CONTEXT 0x800
#define ACTRL_KERNEL_SET_CONTEXT 0x1000
#define ACTRL_KERNEL_TOKEN 0x2000
#define ACTRL_KERNEL_IMPERSONATE 0x4000
#define ACTRL_KERNEL_DIMPERSONATE 0x8000
#define ACTRL_PRINT_SADMIN 0x1
#define ACTRL_PRINT_SLIST 0x2
#define ACTRL_PRINT_PADMIN 0x4
#define ACTRL_PRINT_PUSE 0x8
#define ACTRL_PRINT_JADMIN 0x10
#define ACTRL_SVC_GET_INFO 0x1
#define ACTRL_SVC_SET_INFO 0x2
#define ACTRL_SVC_STATUS 0x4
#define ACTRL_SVC_LIST 0x8
#define ACTRL_SVC_START 0x10
#define ACTRL_SVC_STOP 0x20
#define ACTRL_SVC_PAUSE 0x40
#define ACTRL_SVC_INTERROGATE 0x80
#define ACTRL_SVC_UCONTROL 0x100
#define ACTRL_REG_QUERY 0x1
#define ACTRL_REG_SET 0x2
#define ACTRL_REG_CREATE_CHILD 0x4
#define ACTRL_REG_LIST 0x8
#define ACTRL_REG_NOTIFY 0x10
#define ACTRL_REG_LINK 0x20
#define ACTRL_WIN_CLIPBRD 0x1
#define ACTRL_WIN_GLOBAL_ATOMS 0x2
#define ACTRL_WIN_CREATE 0x4
#define ACTRL_WIN_LIST_DESK 0x8
#define ACTRL_WIN_LIST 0x10
#define ACTRL_WIN_READ_ATTRIBS 0x20
#define ACTRL_WIN_WRITE_ATTRIBS 0x40
#define ACTRL_WIN_SCREEN 0x80
#define ACTRL_WIN_EXIT 0x100
#define ACTRL_ACCESS_NO_OPTIONS 0x0
#define ACTRL_ACCESS_SUPPORTS_OBJECT_ENTRIES 0x1
#define AUDIT_TYPE_LEGACY 0x1
#define AUDIT_TYPE_WMI 0x2
#define AP_ParamTypeBits 0x8
#define AP_ParamTypeMask 255
#define _AUTHZ_SS_MAXSIZE 0x80
#define APF_AuditFailure 0x0
#define APF_AuditSuccess 0x1
#define APF_ValidFlags 0x1
#define AUTHZP_WPD_EVENT 0x10
#define AUTHZ_ALLOW_MULTIPLE_SOURCE_INSTANCES 0x1
#define AUTHZ_MIGRATED_LEGACY_PUBLISHER 0x2
#define AUTHZ_AUDIT_INSTANCE_INFORMATION 0x2
#define AUTHZ_SKIP_TOKEN_GROUPS 0x2
#define AUTHZ_REQUIRE_S4U_LOGON 0x4
#define AUTHZ_COMPUTE_PRIVILEGES 0x8
#define AUTHZ_SECURITY_ATTRIBUTE_TYPE_INVALID 0x0
#define AUTHZ_SECURITY_ATTRIBUTE_TYPE_INT64 0x1
#define AUTHZ_SECURITY_ATTRIBUTE_TYPE_UINT64 0x2
#define AUTHZ_SECURITY_ATTRIBUTE_TYPE_STRING 0x3
#define AUTHZ_SECURITY_ATTRIBUTE_TYPE_FQBN 0x4
#define AUTHZ_SECURITY_ATTRIBUTE_TYPE_SID 0x5
#define AUTHZ_SECURITY_ATTRIBUTE_TYPE_BOOLEAN 0x6
#define AUTHZ_SECURITY_ATTRIBUTE_TYPE_OCTET_STRING 0x10
#define AUTHZ_SECURITY_ATTRIBUTES_INFORMATION_VERSION_V1 0x1
#define AUTHZ_SECURITY_ATTRIBUTES_INFORMATION_VERSION 0x1
#define AUTHZ_RPC_INIT_INFO_CLIENT_VERSION_V1 0x1
#define AUTHZ_INIT_INFO_VERSION_V1 0x1
#define AUTHZ_WPD_CATEGORY_FLAG 0x10
#define AUTHZ_FLAG_ALLOW_MULTIPLE_SOURCE_INSTANCES 0x1
#define OLESCRIPT_E_SYNTAX -2147352319
#define SE_UNKNOWN_OBJECT_TYPE 0
#define SE_FILE_OBJECT 1
#define SE_SERVICE 2
#define SE_PRINTER 3
#define SE_REGISTRY_KEY 4
#define SE_LMSHARE 5
#define SE_KERNEL_OBJECT 6
#define SE_WINDOW_OBJECT 7
#define SE_DS_OBJECT 8
#define SE_DS_OBJECT_ALL 9
#define SE_PROVIDER_DEFINED_OBJECT 10
#define SE_WMIGUID_OBJECT 11
#define SE_REGISTRY_WOW64_32KEY 12
#define SE_REGISTRY_WOW64_64KEY 13
#define NO_MULTIPLE_TRUSTEE 0
#define TRUSTEE_IS_IMPERSONATE 1
#define TRUSTEE_IS_UNKNOWN 0
#define TRUSTEE_IS_USER 1
#define TRUSTEE_IS_GROUP 2
#define TRUSTEE_IS_DOMAIN 3
#define TRUSTEE_IS_ALIAS 4
#define TRUSTEE_IS_WELL_KNOWN_GROUP 5
#define TRUSTEE_IS_DELETED 6
#define TRUSTEE_IS_INVALID 7
#define TRUSTEE_IS_COMPUTER 8
#define AUTHZ_ACCESS_CHECK_NO_DEEP_COPY_SD 0x1
#define TRUSTEE_IS_SID 0
#define TRUSTEE_IS_NAME 1
#define TRUSTEE_BAD_FORM 2
#define TRUSTEE_IS_OBJECTS_AND_SID 3
#define TRUSTEE_IS_OBJECTS_AND_NAME 4
#define AuthzAuditEventInfoFlags 1
#define AuthzAuditEventInfoOperationType 2
#define AuthzAuditEventInfoObjectType 3
#define AuthzAuditEventInfoObjectName 4
#define AuthzAuditEventInfoAdditionalInfo 5
#define ACTRL_ACCESS_ALLOWED 0x1
#define ACTRL_ACCESS_DENIED 0x2
#define ACTRL_AUDIT_SUCCESS 0x4
#define ACTRL_AUDIT_FAILURE 0x8
#define AZ_PROP_NAME 1
#define AZ_PROP_DESCRIPTION 2
#define AZ_PROP_WRITABLE 3
#define AZ_PROP_APPLICATION_DATA 4
#define AZ_PROP_CHILD_CREATE 5
#define AZ_MAX_APPLICATION_NAME_LENGTH 512
#define AZ_MAX_OPERATION_NAME_LENGTH 64
#define AZ_MAX_TASK_NAME_LENGTH 64
#define AZ_MAX_SCOPE_NAME_LENGTH 65536
#define AZ_MAX_GROUP_NAME_LENGTH 64
#define AZ_MAX_ROLE_NAME_LENGTH 64
#define AZ_MAX_NAME_LENGTH 65536
#define AZ_MAX_DESCRIPTION_LENGTH 1024
#define AZ_MAX_APPLICATION_DATA_LENGTH 4096
#define AZ_SUBMIT_FLAG_ABORT 1
#define AZ_SUBMIT_FLAG_FLUSH 2
#define AZ_MAX_POLICY_URL_LENGTH 65536
#define AZ_AZSTORE_FLAG_CREATE 1
#define AZ_AZSTORE_FLAG_MANAGE_STORE_ONLY 2
#define AZ_AZSTORE_FLAG_BATCH_UPDATE 4
#define AZ_AZSTORE_FLAG_AUDIT_IS_CRITICAL 8
#define AZ_AZSTORE_FORCE_APPLICATION_CLOSE 16
#define AZ_AZSTORE_NT6_FUNCTION_LEVEL 32
#define AZ_AZSTORE_FLAG_MANAGE_ONLY_PASSIVE_SUBMIT 32768
#define AZ_PROP_AZSTORE_DOMAIN_TIMEOUT 100
#define AZ_AZSTORE_DEFAULT_DOMAIN_TIMEOUT 15000
#define AZ_PROP_AZSTORE_SCRIPT_ENGINE_TIMEOUT 101
#define AZ_AZSTORE_MIN_DOMAIN_TIMEOUT 500
#define AZ_AZSTORE_MIN_SCRIPT_ENGINE_TIMEOUT 5000
#define AZ_AZSTORE_DEFAULT_SCRIPT_ENGINE_TIMEOUT 45000
#define AZ_PROP_AZSTORE_MAX_SCRIPT_ENGINES 102
#define AZ_AZSTORE_DEFAULT_MAX_SCRIPT_ENGINES 120
#define AZ_PROP_AZSTORE_MAJOR_VERSION 103
#define AZ_PROP_AZSTORE_MINOR_VERSION 104
#define AZ_PROP_AZSTORE_TARGET_MACHINE 105
#define AZ_PROP_AZTORE_IS_ADAM_INSTANCE 106
#define AZ_PROP_OPERATION_ID 200
#define AZ_PROP_TASK_OPERATIONS 300
#define AZ_PROP_TASK_BIZRULE 301
#define AZ_PROP_TASK_BIZRULE_LANGUAGE 302
#define AZ_PROP_TASK_TASKS 303
#define AZ_PROP_TASK_BIZRULE_IMPORTED_PATH 304
#define AZ_PROP_TASK_IS_ROLE_DEFINITION 305
#define AZ_MAX_TASK_BIZRULE_LENGTH 65536
#define AZ_MAX_TASK_BIZRULE_LANGUAGE_LENGTH 64
#define AZ_MAX_TASK_BIZRULE_IMPORTED_PATH_LENGTH 512
#define AZ_MAX_BIZRULE_STRING 65536
#define AZ_PROP_GROUP_TYPE 400
#define AZ_GROUPTYPE_LDAP_QUERY 1
#define AZ_GROUPTYPE_BASIC 2
#define AZ_GROUPTYPE_BIZRULE 3
#define AZ_PROP_GROUP_APP_MEMBERS 401
#define AZ_PROP_GROUP_APP_NON_MEMBERS 402
#define AZ_PROP_GROUP_LDAP_QUERY 403
#define AZ_MAX_GROUP_LDAP_QUERY_LENGTH 4096
#define AZ_PROP_GROUP_MEMBERS 404
#define AZ_PROP_GROUP_NON_MEMBERS 405
#define AZ_PROP_GROUP_MEMBERS_NAME 406
#define AZ_PROP_GROUP_NON_MEMBERS_NAME 407
#define AZ_PROP_GROUP_BIZRULE 408
#define AZ_PROP_GROUP_BIZRULE_LANGUAGE 409
#define AZ_PROP_GROUP_BIZRULE_IMPORTED_PATH 410
#define AZ_MAX_GROUP_BIZRULE_LENGTH 65536
#define AZ_MAX_GROUP_BIZRULE_LANGUAGE_LENGTH 64
#define AZ_MAX_GROUP_BIZRULE_IMPORTED_PATH_LENGTH 512
#define AZ_PROP_ROLE_APP_MEMBERS 500
#define AZ_PROP_ROLE_MEMBERS 501
#define AZ_PROP_ROLE_OPERATIONS 502
#define AZ_PROP_ROLE_TASKS 504
#define AZ_PROP_ROLE_MEMBERS_NAME 505
#define AZ_PROP_SCOPE_BIZRULES_WRITABLE 600
#define AZ_PROP_SCOPE_CAN_BE_DELEGATED 601
#define AZ_PROP_CLIENT_CONTEXT_USER_DN 700
#define AZ_PROP_CLIENT_CONTEXT_USER_SAM_COMPAT 701
#define AZ_PROP_CLIENT_CONTEXT_USER_DISPLAY 702
#define AZ_PROP_CLIENT_CONTEXT_USER_GUID 703
#define AZ_PROP_CLIENT_CONTEXT_USER_CANONICAL 704
#define AZ_PROP_CLIENT_CONTEXT_USER_UPN 705
#define AZ_PROP_CLIENT_CONTEXT_USER_DNS_SAM_COMPAT 707
#define AZ_PROP_CLIENT_CONTEXT_ROLE_FOR_ACCESS_CHECK 708
#define AZ_PROP_CLIENT_CONTEXT_LDAP_QUERY_DN 709
#define AZ_PROP_APPLICATION_AUTHZ_INTERFACE_CLSID 800
#define AZ_PROP_APPLICATION_VERSION 801
#define AZ_MAX_APPLICATION_VERSION_LENGTH 512
#define AZ_PROP_APPLICATION_NAME 802
#define AZ_PROP_APPLICATION_BIZRULE_ENABLED 803
#define AZ_PROP_APPLY_STORE_SACL 900
#define AZ_PROP_GENERATE_AUDITS 901
#define AZ_PROP_POLICY_ADMINS 902
#define AZ_PROP_POLICY_READERS 903
#define AZ_PROP_DELEGATED_POLICY_USERS 904
#define AZ_PROP_POLICY_ADMINS_NAME 905
#define AZ_PROP_POLICY_READERS_NAME 906
#define AZ_PROP_DELEGATED_POLICY_USERS_NAME 907
#define AZ_CLIENT_CONTEXT_SKIP_GROUP 1
#define AZ_CLIENT_CONTEXT_SKIP_LDAP_QUERY 1
#define AZ_CLIENT_CONTEXT_GET_GROUP_RECURSIVE 2
#define AZ_CLIENT_CONTEXT_GET_GROUPS_STORE_LEVEL_ONLY 2
#define AUTHZ_RM_FLAG_NO_AUDIT 0x1
#define AUTHZ_RM_FLAG_INITIALIZE_UNDER_IMPERSONATION 0x2
#define AUTHZ_RM_FLAG_NO_CENTRAL_ACCESS_POLICIES 0x4
#define TREE_SEC_INFO_SET 0x1
#define TREE_SEC_INFO_RESET 0x2
#define TREE_SEC_INFO_RESET_KEEP_EXPLICIT 0x3
#define AuthzContextInfoUserSid 1
#define AuthzContextInfoGroupsSids 2
#define AuthzContextInfoRestrictedSids 3
#define AuthzContextInfoPrivileges 4
#define AuthzContextInfoExpirationTime 5
#define AuthzContextInfoServerContext 6
#define AuthzContextInfoIdentifier 7
#define AuthzContextInfoSource 8
#define AuthzContextInfoAll 9
#define AuthzContextInfoAuthenticationId 10
#define AuthzContextInfoSecurityAttributes 11
#define AuthzContextInfoDeviceSids 12
#define AuthzContextInfoUserClaims 13
#define AuthzContextInfoDeviceClaims 14
#define AuthzContextInfoAppContainerSid 15
#define AuthzContextInfoCapabilitySids 16
#define AUTHZ_SECURITY_ATTRIBUTE_NON_INHERITABLE 0x1
#define AUTHZ_SECURITY_ATTRIBUTE_VALUE_CASE_SENSITIVE 0x2
#define ProgressInvokeNever 1
#define ProgressInvokeEveryObject 2
#define ProgressInvokeOnError 3
#define ProgressCancelOperation 4
#define ProgressRetryOperation 5
#define ProgressInvokePrePostError 6
#define AUTHZ_NO_SUCCESS_AUDIT 0x1
#define AUTHZ_NO_FAILURE_AUDIT 0x2
#define AUTHZ_NO_ALLOC_STRINGS 0x4
#define NOT_USED_ACCESS 0
#define GRANT_ACCESS 1
#define SET_ACCESS 2
#define DENY_ACCESS 3
#define REVOKE_ACCESS 4
#define SET_AUDIT_SUCCESS 5
#define SET_AUDIT_FAILURE 6
#define AUTHZ_GENERATE_SUCCESS_AUDIT 0x1
#define AUTHZ_GENERATE_FAILURE_AUDIT 0x2
#define AUTHZ_SECURITY_ATTRIBUTE_OPERATION_NONE 0
#define AUTHZ_SECURITY_ATTRIBUTE_OPERATION_REPLACE_ALL 1
#define AUTHZ_SECURITY_ATTRIBUTE_OPERATION_ADD 2
#define AUTHZ_SECURITY_ATTRIBUTE_OPERATION_DELETE 3
#define AUTHZ_SECURITY_ATTRIBUTE_OPERATION_REPLACE 4
#define APT_None 1
#define APT_String 2
#define APT_Ulong 3
#define APT_Pointer 4
#define APT_Sid 5
#define APT_LogonId 6
#define APT_ObjectTypeList 7
#define APT_Luid 8
#define APT_Guid 9
#define APT_Time 10
#define APT_Int64 11
#define APT_IpAddress 12
#define APT_LogonIdWithSid 13
#define AUTHZ_SID_OPERATION_NONE 0
#define AUTHZ_SID_OPERATION_REPLACE_ALL 1
#define AUTHZ_SID_OPERATION_ADD 2
#define AUTHZ_SID_OPERATION_DELETE 3
#define AUTHZ_SID_OPERATION_REPLACE 4

// SKIPPED struct AzBizRuleContext: no representable fields
typedef struct _INHERITED_FROMW {
    int GenerationGap;
    void* AncestorName;
} INHERITED_FROMW;

typedef struct _AUDIT_IP_ADDRESS {
    unsigned char pIpAddress[128];
} AUDIT_IP_ADDRESS;

typedef struct _TRUSTEE_ACCESSA {
    void* lpProperty;
    unsigned int Access;
    unsigned int fAccessFlags;
    unsigned int fReturnedAccess;
} TRUSTEE_ACCESSA;

typedef struct _ACTRL_ACCESS_ENTRY_LISTA {
    unsigned int cEntries;
    void* pAccessList;
} ACTRL_ACCESS_ENTRY_LISTA;

typedef struct _ACTRL_ACCESSA {
    unsigned int cEntries;
    void* pPropertyAccessList;
} ACTRL_ACCESSA;

typedef struct _ACTRL_ACCESS_INFOW {
    unsigned int fAccessPermission;
    void* lpAccessPermissionName;
} ACTRL_ACCESS_INFOW;

typedef struct _AUDIT_PARAM {
    void* Type;
    unsigned int Length;
    unsigned int Flags;
    void* Anonymous1;
    void* Anonymous2;
} AUDIT_PARAM;

typedef struct _ACTRL_ACCESS_ENTRYA {
    void* Trustee;
    void* fAccessFlags;
    unsigned int Access;
    unsigned int ProvSpecificAccess;
    void* Inheritance;
    void* lpInheritProperty;
} ACTRL_ACCESS_ENTRYA;

typedef struct _AUTHZ_CAP_CHANGE_SUBSCRIPTION_HANDLE {
    void* Value;
} AUTHZ_CAP_CHANGE_SUBSCRIPTION_HANDLE;

typedef struct _AUTHZ_RESOURCE_MANAGER_HANDLE {
    void* Value;
} AUTHZ_RESOURCE_MANAGER_HANDLE;

typedef struct _AUTHZ_ACCESS_REPLY {
    unsigned int ResultListLength;
    void* GrantedAccessMask;
    void* SaclEvaluationResults;
    void* Error;
} AUTHZ_ACCESS_REPLY;

typedef struct _ACTRL_PROPERTY_ENTRYA {
    void* lpProperty;
    void* pAccessEntryList;
    unsigned int fListFlags;
} ACTRL_PROPERTY_ENTRYA;

typedef struct _AUTHZ_AUDIT_EVENT_TYPE_LEGACY {
    unsigned short CategoryId;
    unsigned short AuditId;
    unsigned short ParameterCount;
} AUTHZ_AUDIT_EVENT_TYPE_LEGACY;

// SKIPPED struct AzAuthorizationStore: no representable fields
typedef struct _AUTHZ_SECURITY_ATTRIBUTE_V1 {
    void* pName;
    unsigned short ValueType;
    unsigned short Reserved;
    void* Flags;
    unsigned int ValueCount;
    void* Values;
} AUTHZ_SECURITY_ATTRIBUTE_V1;

typedef struct _AUTHZ_SECURITY_EVENT_PROVIDER_HANDLE {
    void* Value;
} AUTHZ_SECURITY_EVENT_PROVIDER_HANDLE;

typedef struct _TRUSTEE_W {
    void* pMultipleTrustee;
    void* MultipleTrusteeOperation;
    void* TrusteeForm;
    void* TrusteeType;
    void* ptstrName;
} TRUSTEE_W;

typedef struct _AUTHZ_SECURITY_ATTRIBUTE_FQBN_VALUE {
    unsigned long long Version;
    void* pName;
} AUTHZ_SECURITY_ATTRIBUTE_FQBN_VALUE;

typedef struct _AUTHZ_REGISTRATION_OBJECT_TYPE_NAME_OFFSET {
    void* szObjectTypeName;
    unsigned int dwOffset;
} AUTHZ_REGISTRATION_OBJECT_TYPE_NAME_OFFSET;

typedef struct _INHERITED_FROMA {
    int GenerationGap;
    void* AncestorName;
} INHERITED_FROMA;

typedef struct _ACTRL_OVERLAPPED {
    void* Anonymous;
    unsigned int Reserved2;
    void* hEvent;
} ACTRL_OVERLAPPED;

typedef struct _AUTHZ_AUDIT_EVENT_HANDLE {
    void* Value;
} AUTHZ_AUDIT_EVENT_HANDLE;

typedef struct _EXPLICIT_ACCESS_A {
    unsigned int grfAccessPermissions;
    void* grfAccessMode;
    void* grfInheritance;
    void* Trustee;
} EXPLICIT_ACCESS_A;

typedef struct _AUTHZ_CLIENT_CONTEXT_HANDLE {
    void* Value;
} AUTHZ_CLIENT_CONTEXT_HANDLE;

typedef struct _OBJECTS_AND_SID {
    void* ObjectsPresent;
    void* ObjectTypeGuid;
    void* InheritedObjectTypeGuid;
    void* pSid;
} OBJECTS_AND_SID;

typedef struct _AUTHZ_ACCESS_CHECK_RESULTS_HANDLE {
    void* Value;
} AUTHZ_ACCESS_CHECK_RESULTS_HANDLE;

typedef struct _AUTHZ_INIT_INFO {
    unsigned short version;
    void* szResourceManagerName;
    void* pfnDynamicAccessCheck;
    void* pfnComputeDynamicGroups;
    void* pfnFreeDynamicGroups;
    void* pfnGetCentralAccessPolicy;
    void* pfnFreeCentralAccessPolicy;
} AUTHZ_INIT_INFO;

typedef struct _ACTRL_ACCESS_ENTRY_LISTW {
    unsigned int cEntries;
    void* pAccessList;
} ACTRL_ACCESS_ENTRY_LISTW;

typedef struct _AUDIT_OBJECT_TYPES {
    unsigned short Count;
    unsigned short Flags;
    void* pObjectTypes;
} AUDIT_OBJECT_TYPES;

typedef struct _ACTRL_ACCESS_INFOA {
    unsigned int fAccessPermission;
    void* lpAccessPermissionName;
} ACTRL_ACCESS_INFOA;

typedef struct _ACTRL_CONTROL_INFOW {
    void* lpControlId;
    void* lpControlName;
} ACTRL_CONTROL_INFOW;

typedef struct _ACTRL_CONTROL_INFOA {
    void* lpControlId;
    void* lpControlName;
} ACTRL_CONTROL_INFOA;

typedef struct _ACTRL_ACCESSW {
    unsigned int cEntries;
    void* pPropertyAccessList;
} ACTRL_ACCESSW;

typedef struct _AUTHZ_AUDIT_EVENT_TYPE_UNION {
    void* Legacy;
} AUTHZ_AUDIT_EVENT_TYPE_UNION;

typedef struct _AUTHZ_AUDIT_EVENT_TYPE_OLD {
    unsigned int Version;
    unsigned int dwFlags;
    int RefCount;
    unsigned long long hAudit;
    void* LinkId;
    void* u;
} AUTHZ_AUDIT_EVENT_TYPE_OLD;

typedef struct _EXPLICIT_ACCESS_W {
    unsigned int grfAccessPermissions;
    void* grfAccessMode;
    void* grfInheritance;
    void* Trustee;
} EXPLICIT_ACCESS_W;

typedef struct _FN_OBJECT_MGR_FUNCTS {
    unsigned int Placeholder;
} FN_OBJECT_MGR_FUNCTS;

typedef struct _AUTHZ_SECURITY_ATTRIBUTES_INFORMATION {
    unsigned short Version;
    unsigned short Reserved;
    unsigned int AttributeCount;
    void* Attribute;
} AUTHZ_SECURITY_ATTRIBUTES_INFORMATION;

typedef struct _TRUSTEE_A {
    void* pMultipleTrustee;
    void* MultipleTrusteeOperation;
    void* TrusteeForm;
    void* TrusteeType;
    void* ptstrName;
} TRUSTEE_A;

typedef struct _OBJECTS_AND_NAME_W {
    void* ObjectsPresent;
    void* ObjectType;
    void* ObjectTypeName;
    void* InheritedObjectTypeName;
    void* ptstrName;
} OBJECTS_AND_NAME_W;

typedef struct _AUTHZ_ACCESS_REQUEST {
    unsigned int DesiredAccess;
    void* PrincipalSelfSid;
    void* ObjectTypeList;
    unsigned int ObjectTypeListLength;
    void* OptionalArguments;
} AUTHZ_ACCESS_REQUEST;

typedef struct _OBJECTS_AND_NAME_A {
    void* ObjectsPresent;
    void* ObjectType;
    void* ObjectTypeName;
    void* InheritedObjectTypeName;
    void* ptstrName;
} OBJECTS_AND_NAME_A;

typedef struct _AUDIT_OBJECT_TYPE {
    void* ObjectType;
    unsigned short Flags;
    unsigned short Level;
    unsigned int AccessMask;
} AUDIT_OBJECT_TYPE;

typedef struct _AUTHZ_AUDIT_EVENT_TYPE_HANDLE {
    void* Value;
} AUTHZ_AUDIT_EVENT_TYPE_HANDLE;

typedef struct _AUTHZ_RPC_INIT_INFO_CLIENT {
    unsigned short version;
    void* ObjectUuid;
    void* ProtSeq;
    void* NetworkAddr;
    void* Endpoint;
    void* Options;
    void* ServerSpn;
} AUTHZ_RPC_INIT_INFO_CLIENT;

typedef struct _AUTHZ_SECURITY_ATTRIBUTE_OCTET_STRING_VALUE {
    void* pValue;
    unsigned int ValueLength;
} AUTHZ_SECURITY_ATTRIBUTE_OCTET_STRING_VALUE;

// SKIPPED struct AzPrincipalLocator: no representable fields
typedef struct _TRUSTEE_ACCESSW {
    void* lpProperty;
    unsigned int Access;
    unsigned int fAccessFlags;
    unsigned int fReturnedAccess;
} TRUSTEE_ACCESSW;

typedef struct _AUDIT_PARAMS {
    unsigned int Length;
    unsigned int Flags;
    unsigned short Count;
    void* Parameters;
} AUDIT_PARAMS;

typedef struct _ACTRL_PROPERTY_ENTRYW {
    void* lpProperty;
    void* pAccessEntryList;
    unsigned int fListFlags;
} ACTRL_PROPERTY_ENTRYW;

typedef struct _AUTHZ_SOURCE_SCHEMA_REGISTRATION {
    unsigned int dwFlags;
    void* szEventSourceName;
    void* szEventMessageFile;
    void* szEventSourceXmlSchemaFile;
    void* szEventAccessStringsFile;
    void* szExecutableImagePath;
    void* Anonymous;
    unsigned int dwObjectTypeNameCount;
    void* ObjectTypeNames[1];
} AUTHZ_SOURCE_SCHEMA_REGISTRATION;

typedef struct _ACTRL_ACCESS_ENTRYW {
    void* Trustee;
    void* fAccessFlags;
    unsigned int Access;
    unsigned int ProvSpecificAccess;
    void* Inheritance;
    void* lpInheritProperty;
} ACTRL_ACCESS_ENTRYW;

