// Generated by entc-win32gen from `Windows.Win32.System.Console`.
// Do not edit by hand. Re-run the generator to refresh.

typedef unsigned char       BYTE;
typedef unsigned short      WORD;
typedef unsigned long       DWORD;
typedef unsigned long long  ULONGLONG;
typedef long                LONG;
typedef unsigned long       ULONG;
typedef int                 BOOL;
typedef void*               PVOID;
typedef void*               HANDLE;

#define CONSOLE_TEXTMODE_BUFFER 0x1
#define CONSOLE_SELECTION_INVERTED 0x10
#define VDM_HIDE_WINDOW 0x1
#define VDM_IS_ICONIC 0x2
#define VDM_CLIENT_RECT 0x3
#define VDM_CLIENT_TO_SCREEN 0x4
#define VDM_SCREEN_TO_CLIENT 0x5
#define VDM_IS_HIDDEN 0x6
#define VDM_FULLSCREEN_NOPAINT 0x7
#define VDM_SET_VIDEO_MODE 0x8
#define CONSOLE_UNREGISTER_VDM 0x0
#define CONSOLE_REGISTER_VDM 0x1
#define CONSOLE_REGISTER_WOW 0x2
#define CONSOLE_NOSHORTCUTKEY 0x0
#define CONSOLE_ALTTAB 0x1
#define CONSOLE_ALTESC 0x2
#define CONSOLE_ALTSPACE 0x4
#define CONSOLE_ALTENTER 0x8
#define CONSOLE_ALTPRTSC 0x10
#define CONSOLE_PRTSC 0x20
#define CONSOLE_CTRLESC 0x40
#define CONSOLE_MODIFIER_SHIFT 0x3
#define CONSOLE_MODIFIER_CONTROL 0x4
#define CONSOLE_MODIFIER_ALT 0x8
#define CHAR_TYPE_SBCS 0x0
#define CHAR_TYPE_LEADING 0x2
#define CHAR_TYPE_TRAILING 0x3
#define CONSOLE_HANDLE_SIGNATURE 0x3
#define CONSOLE_HANDLE_NEVERSET 0x10000000
// SKIPPED const CONSOLE_INPUT_STRING: non-integer constant
// SKIPPED const CONSOLE_OUTPUT_STRING: non-integer constant
// SKIPPED const CONSOLE_GENERIC: non-integer constant
#define PID_CONSOLE_FORCEV2 0x1
#define PID_CONSOLE_WRAPTEXT 0x2
#define PID_CONSOLE_FILTERONPASTE 0x3
#define PID_CONSOLE_CTRLKEYSDISABLED 0x4
#define PID_CONSOLE_LINESELECTION 0x5
#define PID_CONSOLE_WINDOWTRANSPARENCY 0x6
#define PID_CONSOLE_WINDOWMAXIMIZED 0x7
#define PID_CONSOLE_CURSOR_TYPE 0x8
#define PID_CONSOLE_CURSOR_COLOR 0x9
#define PID_CONSOLE_INTERCEPT_COPY_PASTE 0xa
#define PID_CONSOLE_DEFAULTFOREGROUND 0xb
#define PID_CONSOLE_DEFAULTBACKGROUND 0xc
#define PID_CONSOLE_TERMINALSCROLLING 0xd
#define ATTACH_PARENT_PROCESS 0xffffffff
#define CTRL_C_EVENT 0x0
#define CTRL_BREAK_EVENT 0x1
#define CTRL_CLOSE_EVENT 0x2
#define CTRL_LOGOFF_EVENT 0x5
#define CTRL_SHUTDOWN_EVENT 0x6
#define PSEUDOCONSOLE_INHERIT_CURSOR 0x1
#define CONSOLE_NO_SELECTION 0x0
#define CONSOLE_SELECTION_IN_PROGRESS 0x1
#define CONSOLE_SELECTION_NOT_EMPTY 0x2
#define CONSOLE_MOUSE_SELECTION 0x4
#define CONSOLE_MOUSE_DOWN 0x8
#define HISTORY_NO_DUP_FLAG 0x1
#define CONSOLE_FULLSCREEN 0x1
#define CONSOLE_FULLSCREEN_HARDWARE 0x2
#define CONSOLE_FULLSCREEN_MODE 0x1
#define CONSOLE_WINDOWED_MODE 0x2
#define RIGHT_ALT_PRESSED 0x1
#define LEFT_ALT_PRESSED 0x2
#define RIGHT_CTRL_PRESSED 0x4
#define LEFT_CTRL_PRESSED 0x8
#define SHIFT_PRESSED 0x10
#define NUMLOCK_ON 0x20
#define SCROLLLOCK_ON 0x40
#define CAPSLOCK_ON 0x80
#define ENHANCED_KEY 0x100
#define NLS_DBCSCHAR 0x10000
#define NLS_ALPHANUMERIC 0x0
#define NLS_KATAKANA 0x20000
#define NLS_HIRAGANA 0x40000
#define NLS_ROMAN 0x400000
#define NLS_IME_CONVERSION 0x800000
#define ALTNUMPAD_BIT 0x4000000
#define NLS_IME_DISABLE 0x20000000
#define FROM_LEFT_1ST_BUTTON_PRESSED 0x1
#define RIGHTMOST_BUTTON_PRESSED 0x2
#define FROM_LEFT_2ND_BUTTON_PRESSED 0x4
#define FROM_LEFT_3RD_BUTTON_PRESSED 0x8
#define FROM_LEFT_4TH_BUTTON_PRESSED 0x10
#define MOUSE_MOVED 0x1
#define DOUBLE_CLICK 0x2
#define MOUSE_WHEELED 0x4
#define MOUSE_HWHEELED 0x8
#define KEY_EVENT 0x1
#define MOUSE_EVENT 0x2
#define WINDOW_BUFFER_SIZE_EVENT 0x4
#define MENU_EVENT 0x8
#define FOCUS_EVENT 0x10
#define ALLOC_CONSOLE_RESULT_NO_CONSOLE 0
#define ALLOC_CONSOLE_RESULT_NEW_CONSOLE 1
#define ALLOC_CONSOLE_RESULT_EXISTING_CONSOLE 2
#define ENABLE_PROCESSED_INPUT 0x1
#define ENABLE_LINE_INPUT 0x2
#define ENABLE_ECHO_INPUT 0x4
#define ENABLE_WINDOW_INPUT 0x8
#define ENABLE_MOUSE_INPUT 0x10
#define ENABLE_INSERT_MODE 0x20
#define ENABLE_QUICK_EDIT_MODE 0x40
#define ENABLE_EXTENDED_FLAGS 0x80
#define ENABLE_AUTO_POSITION 0x100
#define ENABLE_VIRTUAL_TERMINAL_INPUT 0x200
#define ENABLE_PROCESSED_OUTPUT 0x1
#define ENABLE_WRAP_AT_EOL_OUTPUT 0x2
#define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x4
#define DISABLE_NEWLINE_AUTO_RETURN 0x8
#define ENABLE_LVB_GRID_WORLDWIDE 0x10
#define FOREGROUND_BLUE 0x1
#define FOREGROUND_GREEN 0x2
#define FOREGROUND_RED 0x4
#define FOREGROUND_INTENSITY 0x8
#define BACKGROUND_BLUE 0x10
#define BACKGROUND_GREEN 0x20
#define BACKGROUND_RED 0x40
#define BACKGROUND_INTENSITY 0x80
#define COMMON_LVB_LEADING_BYTE 0x100
#define COMMON_LVB_TRAILING_BYTE 0x200
#define COMMON_LVB_GRID_HORIZONTAL 0x400
#define COMMON_LVB_GRID_LVERTICAL 0x800
#define COMMON_LVB_GRID_RVERTICAL 0x1000
#define COMMON_LVB_REVERSE_VIDEO 0x4000
#define COMMON_LVB_UNDERSCORE 0x8000
#define COMMON_LVB_SBCSDBCS 0x300
#define STD_INPUT_HANDLE 0xfffffff6
#define STD_OUTPUT_HANDLE 0xfffffff5
#define STD_ERROR_HANDLE 0xfffffff4
#define Reserved1 0
#define ConsoleNotifyConsoleApplication 1
#define Reserved2 2
#define ConsoleSetCaretInfo 3
#define Reserved3 4
#define ConsoleSetForeground 5
#define ConsoleSetWindowOwner 6
#define ConsoleEndTask 7
#define ALLOC_CONSOLE_MODE_DEFAULT 0
#define ALLOC_CONSOLE_MODE_NEW_WINDOW 1
#define ALLOC_CONSOLE_MODE_NO_WINDOW 2

typedef struct _ALLOC_CONSOLE_OPTIONS {
    void* mode;
    BOOL useShowWindow;
    unsigned short showWindow;
} ALLOC_CONSOLE_OPTIONS;

typedef struct _CONSOLE_HISTORY_INFO {
    unsigned int cbSize;
    unsigned int HistoryBufferSize;
    unsigned int NumberOfHistoryBuffers;
    unsigned int dwFlags;
} CONSOLE_HISTORY_INFO;

typedef struct _CONSOLE_CARET_INFO {
    void* hwnd;
    void* rc;
} CONSOLE_CARET_INFO;

typedef struct _HPCON {
    long long Value;
} HPCON;

typedef struct _KEY_EVENT_RECORD {
    BOOL bKeyDown;
    unsigned short wRepeatCount;
    unsigned short wVirtualKeyCode;
    unsigned short wVirtualScanCode;
    void* uChar;
    unsigned int dwControlKeyState;
} KEY_EVENT_RECORD;

typedef struct _CONSOLE_SCREEN_BUFFER_INFO {
    void* dwSize;
    void* dwCursorPosition;
    void* wAttributes;
    void* srWindow;
    void* dwMaximumWindowSize;
} CONSOLE_SCREEN_BUFFER_INFO;

typedef struct _CONSOLE_SCREEN_BUFFER_INFOEX {
    unsigned int cbSize;
    void* dwSize;
    void* dwCursorPosition;
    void* wAttributes;
    void* srWindow;
    void* dwMaximumWindowSize;
    unsigned short wPopupAttributes;
    BOOL bFullscreenSupported;
    void* ColorTable[16];
} CONSOLE_SCREEN_BUFFER_INFOEX;

typedef struct _INPUT_RECORD {
    unsigned short EventType;
    void* Event;
} INPUT_RECORD;

typedef struct _ExtKeySubst {
    unsigned short wMod;
    unsigned short wVirKey;
    unsigned short wUnicodeChar;
} ExtKeySubst;

typedef struct _CONSOLEWINDOWOWNER {
    void* hwnd;
    unsigned int ProcessId;
    unsigned int ThreadId;
} CONSOLEWINDOWOWNER;

typedef struct _SMALL_RECT {
    short Left;
    short Top;
    short Right;
    short Bottom;
} SMALL_RECT;

typedef struct _MENU_EVENT_RECORD {
    unsigned int dwCommandId;
} MENU_EVENT_RECORD;

typedef struct _CONSOLE_FONT_INFO {
    unsigned int nFont;
    void* dwFontSize;
} CONSOLE_FONT_INFO;

typedef struct _CONSOLE_READCONSOLE_CONTROL {
    unsigned int nLength;
    unsigned int nInitialChars;
    unsigned int dwCtrlWakeupMask;
    unsigned int dwControlKeyState;
} CONSOLE_READCONSOLE_CONTROL;

typedef struct _CONSOLE_CURSOR_INFO {
    unsigned int dwSize;
    BOOL bVisible;
} CONSOLE_CURSOR_INFO;

typedef struct _CONSOLE_SELECTION_INFO {
    unsigned int dwFlags;
    void* dwSelectionAnchor;
    void* srSelection;
} CONSOLE_SELECTION_INFO;

typedef struct _CONSOLESETFOREGROUND {
    void* hProcess;
    BOOL bForeground;
} CONSOLESETFOREGROUND;

typedef struct _CONSOLE_FONT_INFOEX {
    unsigned int cbSize;
    unsigned int nFont;
    void* dwFontSize;
    unsigned int FontFamily;
    unsigned int FontWeight;
    unsigned short FaceName[32];
} CONSOLE_FONT_INFOEX;

typedef struct _APPKEY {
    unsigned short Modifier;
    unsigned short ScanCode;
} APPKEY;

typedef struct _CONSOLEENDTASK {
    void* ProcessId;
    void* hwnd;
    unsigned int ConsoleEventCode;
    unsigned int ConsoleFlags;
} CONSOLEENDTASK;

typedef struct _ExtKeyDef {
    void* keys[3];
} ExtKeyDef;

typedef struct _MOUSE_EVENT_RECORD {
    void* dwMousePosition;
    unsigned int dwButtonState;
    unsigned int dwControlKeyState;
    unsigned int dwEventFlags;
} MOUSE_EVENT_RECORD;

typedef struct _CHAR_INFO {
    void* Char;
    unsigned short Attributes;
} CHAR_INFO;

typedef struct _CONSOLE_GRAPHICS_BUFFER_INFO {
    unsigned int dwBitMapInfoLength;
    void* lpBitMapInfo;
    unsigned int dwUsage;
    void* hMutex;
    void* lpBitMap;
} CONSOLE_GRAPHICS_BUFFER_INFO;

typedef struct _FOCUS_EVENT_RECORD {
    BOOL bSetFocus;
} FOCUS_EVENT_RECORD;

typedef struct _WINDOW_BUFFER_SIZE_RECORD {
    void* dwSize;
} WINDOW_BUFFER_SIZE_RECORD;

typedef struct _CONSOLE_PROCESS_INFO {
    unsigned int dwProcessID;
    unsigned int dwFlags;
} CONSOLE_PROCESS_INFO;

typedef struct _COORD {
    short X;
    short Y;
} COORD;

typedef struct _ExtKeyDefBuf {
    unsigned int dwVersion;
    unsigned int dwCheckSum;
    void* table[26];
} ExtKeyDefBuf;

