// Generated by entc-win32gen from `Windows.Win32.System.Environment`.
// Do not edit by hand. Re-run the generator to refresh.

typedef unsigned char       BYTE;
typedef unsigned short      WORD;
typedef unsigned long       DWORD;
typedef unsigned long long  ULONGLONG;
typedef long                LONG;
typedef unsigned long       ULONG;
typedef int                 BOOL;
typedef void*               PVOID;
typedef void*               HANDLE;

#define ENCLAVE_RUNTIME_POLICY_ALLOW_FULL_DEBUG 0x1
#define ENCLAVE_RUNTIME_POLICY_ALLOW_DYNAMIC_DEBUG 0x2
#define ENCLAVE_UNSEAL_FLAG_STALE_KEY 0x1
#define ENCLAVE_FLAG_FULL_DEBUG_ENABLED 0x1
#define ENCLAVE_FLAG_DYNAMIC_DEBUG_ENABLED 0x2
#define ENCLAVE_FLAG_DYNAMIC_DEBUG_ACTIVE 0x4
#define VBS_ENCLAVE_REPORT_PKG_HEADER_VERSION_CURRENT 0x1
#define VBS_ENCLAVE_REPORT_SIGNATURE_SCHEME_SHA256_RSA_PSS_SHA256 0x1
#define VBS_ENCLAVE_REPORT_VERSION_CURRENT 0x1
#define ENCLAVE_REPORT_DATA_LENGTH 0x40
#define VBS_ENCLAVE_VARDATA_INVALID 0x0
#define VBS_ENCLAVE_VARDATA_MODULE 0x1
#define ENCLAVE_VBS_BASIC_KEY_FLAG_MEASUREMENT 0x1
#define ENCLAVE_VBS_BASIC_KEY_FLAG_FAMILY_ID 0x2
#define ENCLAVE_VBS_BASIC_KEY_FLAG_IMAGE_ID 0x4
#define ENCLAVE_VBS_BASIC_KEY_FLAG_DEBUG_KEY 0x8
#define ENCLAVE_IDENTITY_POLICY_SEAL_INVALID 0
#define ENCLAVE_IDENTITY_POLICY_SEAL_EXACT_CODE 1
#define ENCLAVE_IDENTITY_POLICY_SEAL_SAME_PRIMARY_CODE 2
#define ENCLAVE_IDENTITY_POLICY_SEAL_SAME_IMAGE 3
#define ENCLAVE_IDENTITY_POLICY_SEAL_SAME_FAMILY 4
#define ENCLAVE_IDENTITY_POLICY_SEAL_SAME_AUTHOR 5

typedef struct _TRUSTLET_BINDING_DATA {
    unsigned long long TrustletIdentity;
    void* TrustletSessionId;
    unsigned int TrustletSvn;
    unsigned int Reserved1;
    unsigned long long Reserved2;
} TRUSTLET_BINDING_DATA;

typedef struct _VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR64 {
    unsigned long long ThreadContext[4];
    unsigned long long EntryPoint;
    unsigned long long StackPointer;
    unsigned long long ExceptionEntryPoint;
    unsigned long long ExceptionStack;
    unsigned int ExceptionActive;
} VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR64;

typedef struct _VBS_BASIC_ENCLAVE_EXCEPTION_AMD64 {
    unsigned int ExceptionCode;
    unsigned int NumberParameters;
    unsigned long long ExceptionInformation[3];
    unsigned long long ExceptionRAX;
    unsigned long long ExceptionRCX;
    unsigned long long ExceptionRIP;
    unsigned long long ExceptionRFLAGS;
    unsigned long long ExceptionRSP;
} VBS_BASIC_ENCLAVE_EXCEPTION_AMD64;

typedef struct _VBS_ENCLAVE_REPORT_VARDATA_HEADER {
    unsigned int DataType;
    unsigned int Size;
} VBS_ENCLAVE_REPORT_VARDATA_HEADER;

typedef struct _VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR32 {
    unsigned int ThreadContext[4];
    unsigned int EntryPoint;
    unsigned int StackPointer;
    unsigned int ExceptionEntryPoint;
    unsigned int ExceptionStack;
    unsigned int ExceptionActive;
} VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR32;

typedef struct _VBS_BASIC_ENCLAVE_SYSCALL_PAGE {
    void* ReturnFromEnclave;
    void* ReturnFromException;
    void* TerminateThread;
    void* InterruptThread;
    void* CommitPages;
    void* DecommitPages;
    void* ProtectPages;
    void* CreateThread;
    void* GetEnclaveInformation;
    void* GenerateKey;
    void* GenerateReport;
    void* VerifyReport;
    void* GenerateRandomData;
} VBS_BASIC_ENCLAVE_SYSCALL_PAGE;

typedef struct _VBS_ENCLAVE_REPORT_PKG_HEADER {
    unsigned int PackageSize;
    unsigned int Version;
    unsigned int SignatureScheme;
    unsigned int SignedStatementSize;
    unsigned int SignatureSize;
    unsigned int Reserved;
} VBS_ENCLAVE_REPORT_PKG_HEADER;

typedef struct _PS_TRUSTLET_TKSESSION_ID {
    unsigned long long SessionId[4];
} PS_TRUSTLET_TKSESSION_ID;

typedef struct _ENCLAVE_INFORMATION {
    unsigned int EnclaveType;
    unsigned int Reserved;
    void* BaseAddress;
    unsigned long long Size;
    void* Identity;
} ENCLAVE_INFORMATION;

typedef struct _ENCLAVE_IDENTITY {
    unsigned char OwnerId[32];
    unsigned char UniqueId[32];
    unsigned char AuthorId[32];
    unsigned char FamilyId[16];
    unsigned char ImageId[16];
    unsigned int EnclaveSvn;
    unsigned int SecureKernelSvn;
    unsigned int PlatformSvn;
    unsigned int Flags;
    unsigned int SigningLevel;
    unsigned int EnclaveType;
} ENCLAVE_IDENTITY;

typedef struct _ENCLAVE_VBS_BASIC_KEY_REQUEST {
    unsigned int RequestSize;
    unsigned int Flags;
    unsigned int EnclaveSVN;
    unsigned int SystemKeyID;
    unsigned int CurrentSystemKeyID;
} ENCLAVE_VBS_BASIC_KEY_REQUEST;

typedef struct _VBS_ENCLAVE_REPORT {
    unsigned int ReportSize;
    unsigned int ReportVersion;
    unsigned char EnclaveData[64];
    void* EnclaveIdentity;
} VBS_ENCLAVE_REPORT;

typedef struct _VBS_ENCLAVE_REPORT_MODULE {
    void* Header;
    unsigned char UniqueId[32];
    unsigned char AuthorId[32];
    unsigned char FamilyId[16];
    unsigned char ImageId[16];
    unsigned int Svn;
    unsigned short ModuleName[1];
} VBS_ENCLAVE_REPORT_MODULE;

