// Generated by entc-win32gen from `Windows.Win32.System.IO`.
// Do not edit by hand. Re-run the generator to refresh.

typedef unsigned char       BYTE;
typedef unsigned short      WORD;
typedef unsigned long       DWORD;
typedef unsigned long long  ULONGLONG;
typedef long                LONG;
typedef unsigned long       ULONG;
typedef int                 BOOL;
typedef void*               PVOID;
typedef void*               HANDLE;

typedef struct _OVERLAPPED_ENTRY {
    unsigned long long lpCompletionKey;
    void* lpOverlapped;
    unsigned long long Internal;
    unsigned int dwNumberOfBytesTransferred;
} OVERLAPPED_ENTRY;

typedef struct _IO_STATUS_BLOCK {
    void* Anonymous;
    unsigned long long Information;
} IO_STATUS_BLOCK;

typedef struct _OVERLAPPED {
    unsigned long long Internal;
    unsigned long long InternalHigh;
    void* Anonymous;
    void* hEvent;
} OVERLAPPED;

