// Generated by entc-win32gen from `Windows.Win32.System.Kernel`.
// Do not edit by hand. Re-run the generator to refresh.

typedef unsigned char       BYTE;
typedef unsigned short      WORD;
typedef unsigned long       DWORD;
typedef unsigned long long  ULONGLONG;
typedef long                LONG;
typedef unsigned long       ULONG;
typedef int                 BOOL;
typedef void*               PVOID;
typedef void*               HANDLE;

#define OBJ_HANDLE_TAGBITS 3
#define RTL_BALANCED_NODE_RESERVED_PARENT_MASK 0x3
#define NULL64 0x0
#define MAXUCHAR 0xff
#define MAXUSHORT 0xffff
#define MAXULONG 0xffffffff
#define NotificationTimer 0
#define SynchronizationTimer 1
#define ExceptionContinueExecution 0
#define ExceptionContinueSearch 1
#define ExceptionNestedException 2
#define ExceptionCollidedUnwind 3
#define WaitAll 0
#define WaitAny 1
#define WaitNotification 2
#define WaitDequeue 3
#define WaitDpc 4
#define NotificationEvent 0
#define SynchronizationEvent 1
#define NtProductWinNt 1
#define NtProductLanManNt 2
#define NtProductServer 3
#define SmallBusiness 0
#define Enterprise 1
#define BackOffice 2
#define CommunicationServer 3
#define TerminalServer 4
#define SmallBusinessRestricted 5
#define EmbeddedNT 6
#define DataCenter 7
#define SingleUserTS 8
#define Personal 9
#define Blade 10
#define EmbeddedRestricted 11
#define SecurityAppliance 12
#define StorageServer 13
#define ComputeServer 14
#define WHServer 15
#define PhoneNT 16
#define MultiUserTS 17
#define MaxSuiteType 18
#define UNSPECIFIED_COMPARTMENT_ID 0
#define DEFAULT_COMPARTMENT_ID 1

typedef struct _WNF_STATE_NAME {
    unsigned int Data[2];
} WNF_STATE_NAME;

typedef struct _STRING64 {
    unsigned short Length;
    unsigned short MaximumLength;
    unsigned long long Buffer;
} STRING64;

typedef struct _OBJECTID {
    void* Lineage;
    unsigned int Uniquifier;
} OBJECTID;

typedef struct _NT_TIB {
    void* ExceptionList;
    void* StackBase;
    void* StackLimit;
    void* SubSystemTib;
    void* Anonymous;
    void* ArbitraryUserPointer;
    void* Self;
} NT_TIB;

typedef struct _STRING {
    unsigned short Length;
    unsigned short MaximumLength;
    void* Buffer;
} STRING;

typedef struct _EXCEPTION_REGISTRATION_RECORD {
    void* Next;
    void* Handler;
} EXCEPTION_REGISTRATION_RECORD;

typedef struct _CSTRING {
    unsigned short Length;
    unsigned short MaximumLength;
    void* Buffer;
} CSTRING;

typedef struct _SLIST_HEADER {
    void* Anonymous;
    void* HeaderArm64;
} SLIST_HEADER;

typedef struct _SLIST_HEADER {
    void* Anonymous;
    void* HeaderX64;
} SLIST_HEADER;

typedef struct _SLIST_HEADER {
    unsigned long long Alignment;
    void* Anonymous;
} SLIST_HEADER;

typedef struct _LIST_ENTRY32 {
    unsigned int Flink;
    unsigned int Blink;
} LIST_ENTRY32;

typedef struct _SINGLE_LIST_ENTRY {
    void* Next;
} SINGLE_LIST_ENTRY;

typedef struct _LIST_ENTRY {
    void* Flink;
    void* Blink;
} LIST_ENTRY;

typedef struct _STRING32 {
    unsigned short Length;
    unsigned short MaximumLength;
    unsigned int Buffer;
} STRING32;

typedef struct _PROCESSOR_NUMBER {
    unsigned short Group;
    unsigned char Number;
    unsigned char Reserved;
} PROCESSOR_NUMBER;

typedef struct _QUAD {
    void* Anonymous;
} QUAD;

typedef struct _SLIST_ENTRY {
    void* Next;
} SLIST_ENTRY;

typedef struct _SINGLE_LIST_ENTRY32 {
    unsigned int Next;
} SINGLE_LIST_ENTRY32;

typedef struct _RTL_BALANCED_NODE {
    void* Anonymous1;
    void* Anonymous2;
} RTL_BALANCED_NODE;

typedef struct _FLOATING_SAVE_AREA {
    unsigned int ControlWord;
    unsigned int StatusWord;
    unsigned int TagWord;
    unsigned int ErrorOffset;
    unsigned int ErrorSelector;
    unsigned int DataOffset;
    unsigned int DataSelector;
    unsigned char RegisterArea[80];
    unsigned int Cr0NpxState;
} FLOATING_SAVE_AREA;

typedef struct _FLOATING_SAVE_AREA {
    unsigned int ControlWord;
    unsigned int StatusWord;
    unsigned int TagWord;
    unsigned int ErrorOffset;
    unsigned int ErrorSelector;
    unsigned int DataOffset;
    unsigned int DataSelector;
    unsigned char RegisterArea[80];
    unsigned int Spare0;
} FLOATING_SAVE_AREA;

typedef struct _LIST_ENTRY64 {
    unsigned long long Flink;
    unsigned long long Blink;
} LIST_ENTRY64;

