// Generated by entc-win32gen from `Windows.Win32.System.LibraryLoader`.
// Do not edit by hand. Re-run the generator to refresh.

typedef unsigned char       BYTE;
typedef unsigned short      WORD;
typedef unsigned long       DWORD;
typedef unsigned long long  ULONGLONG;
typedef long                LONG;
typedef unsigned long       ULONG;
typedef int                 BOOL;
typedef void*               PVOID;
typedef void*               HANDLE;

#define FIND_RESOURCE_DIRECTORY_TYPES 0x100
#define FIND_RESOURCE_DIRECTORY_NAMES 0x200
#define FIND_RESOURCE_DIRECTORY_LANGUAGES 0x400
#define RESOURCE_ENUM_LN 0x1
#define RESOURCE_ENUM_MUI 0x2
#define RESOURCE_ENUM_MUI_SYSTEM 0x4
#define RESOURCE_ENUM_VALIDATE 0x8
#define RESOURCE_ENUM_MODULE_EXACT 0x10
#define SUPPORT_LANG_NUMBER 0x20
#define GET_MODULE_HANDLE_EX_FLAG_PIN 0x1
#define GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT 0x2
#define GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS 0x4
#define CURRENT_IMPORT_REDIRECTION_VERSION 0x1
#define LOAD_LIBRARY_OS_INTEGRITY_CONTINUITY 0x8000
#define DONT_RESOLVE_DLL_REFERENCES 0x1
#define LOAD_LIBRARY_AS_DATAFILE 0x2
#define LOAD_WITH_ALTERED_SEARCH_PATH 0x8
#define LOAD_IGNORE_CODE_AUTHZ_LEVEL 0x10
#define LOAD_LIBRARY_AS_IMAGE_RESOURCE 0x20
#define LOAD_LIBRARY_AS_DATAFILE_EXCLUSIVE 0x40
#define LOAD_LIBRARY_REQUIRE_SIGNED_TARGET 0x80
#define LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR 0x100
#define LOAD_LIBRARY_SEARCH_APPLICATION_DIR 0x200
#define LOAD_LIBRARY_SEARCH_USER_DIRS 0x400
#define LOAD_LIBRARY_SEARCH_SYSTEM32 0x800
#define LOAD_LIBRARY_SEARCH_DEFAULT_DIRS 0x1000
#define LOAD_LIBRARY_SAFE_CURRENT_DIRS 0x2000
#define LOAD_LIBRARY_SEARCH_SYSTEM32_NO_FORWARDER 0x4000

typedef struct _ENUMUILANG {
    unsigned int NumOfEnumUILang;
    unsigned int SizeOfEnumUIBuffer;
    void* pEnumUIBuffer;
} ENUMUILANG;

typedef struct _REDIRECTION_DESCRIPTOR {
    unsigned int Version;
    unsigned int FunctionCount;
    void* Redirections;
} REDIRECTION_DESCRIPTOR;

typedef struct _REDIRECTION_FUNCTION_DESCRIPTOR {
    void* DllName;
    void* FunctionName;
    void* RedirectionTarget;
} REDIRECTION_FUNCTION_DESCRIPTOR;

