// Generated by entc-win32gen from `Windows.Win32.System.Memory`.
// Do not edit by hand. Re-run the generator to refresh.

typedef unsigned char       BYTE;
typedef unsigned short      WORD;
typedef unsigned long       DWORD;
typedef unsigned long long  ULONGLONG;
typedef long                LONG;
typedef unsigned long       ULONG;
typedef int                 BOOL;
typedef void*               PVOID;
typedef void*               HANDLE;

#define FILE_CACHE_MAX_HARD_ENABLE 0x1
#define FILE_CACHE_MAX_HARD_DISABLE 0x2
#define FILE_CACHE_MIN_HARD_ENABLE 0x4
#define FILE_CACHE_MIN_HARD_DISABLE 0x8
#define MEHC_PATROL_SCRUBBER_PRESENT 0x1
#define WIN32_MEMORY_NUMA_PERFORMANCE_ALL_TARGET_NODE 0xffffffff
#define WIN32_MEMORY_NUMA_PERFORMANCE_READ_LATENCY 0x1
#define WIN32_MEMORY_NUMA_PERFORMANCE_READ_BANDWIDTH 0x2
#define WIN32_MEMORY_NUMA_PERFORMANCE_WRITE_LATENCY 0x4
#define WIN32_MEMORY_NUMA_PERFORMANCE_WRITE_BANDWIDTH 0x8
#define VmOfferPriorityVeryLow 1
#define VmOfferPriorityLow 2
#define VmOfferPriorityBelowNormal 3
#define VmOfferPriorityNormal 4
#define MEM_COMMIT 0x1000
#define MEM_RESERVE 0x2000
#define MEM_RESET 0x80000
#define MEM_RESET_UNDO 0x1000000
#define MEM_REPLACE_PLACEHOLDER 0x4000
#define MEM_LARGE_PAGES 0x20000000
#define MEM_RESERVE_PLACEHOLDER 0x40000
#define MEM_FREE 0x10000
#define QUOTA_LIMITS_HARDWS_MIN_ENABLE 0x1
#define QUOTA_LIMITS_HARDWS_MIN_DISABLE 0x2
#define QUOTA_LIMITS_HARDWS_MAX_ENABLE 0x4
#define QUOTA_LIMITS_HARDWS_MAX_DISABLE 0x8
#define GHND 0x42
#define GMEM_FIXED 0x0
#define GMEM_MOVEABLE 0x2
#define GMEM_ZEROINIT 0x40
#define GPTR 0x40
#define MEM_PRIVATE 0x20000
#define MEM_MAPPED 0x40000
#define MEM_IMAGE 0x1000000
#define MemDedicatedAttributeReadBandwidth 0
#define MemDedicatedAttributeReadLatency 1
#define MemDedicatedAttributeWriteBandwidth 2
#define MemDedicatedAttributeWriteLatency 3
#define MemDedicatedAttributeMax 4
#define MemExtendedParameterInvalidType 0
#define MemExtendedParameterAddressRequirements 1
#define MemExtendedParameterNumaNode 2
#define MemExtendedParameterPartitionHandle 3
#define MemExtendedParameterUserPhysicalHandle 4
#define MemExtendedParameterAttributeFlags 5
#define MemExtendedParameterImageMachine 6
#define MemExtendedParameterMax 7
#define MEM_DECOMMIT 0x4000
#define MEM_RELEASE 0x8000
#define PAGE_NOACCESS 0x1
#define PAGE_READONLY 0x2
#define PAGE_READWRITE 0x4
#define PAGE_WRITECOPY 0x8
#define PAGE_EXECUTE 0x10
#define PAGE_EXECUTE_READ 0x20
#define PAGE_EXECUTE_READWRITE 0x40
#define PAGE_EXECUTE_WRITECOPY 0x80
#define PAGE_GUARD 0x100
#define PAGE_NOCACHE 0x200
#define PAGE_WRITECOMBINE 0x400
#define PAGE_GRAPHICS_NOACCESS 0x800
#define PAGE_GRAPHICS_READONLY 0x1000
#define PAGE_GRAPHICS_READWRITE 0x2000
#define PAGE_GRAPHICS_EXECUTE 0x4000
#define PAGE_GRAPHICS_EXECUTE_READ 0x8000
#define PAGE_GRAPHICS_EXECUTE_READWRITE 0x10000
#define PAGE_GRAPHICS_COHERENT 0x20000
#define PAGE_GRAPHICS_NOCACHE 0x40000
#define PAGE_ENCLAVE_THREAD_CONTROL 0x80000000
#define PAGE_REVERT_TO_FILE_MAP 0x80000000
#define PAGE_TARGETS_NO_UPDATE 0x40000000
#define PAGE_TARGETS_INVALID 0x40000000
#define PAGE_ENCLAVE_UNVALIDATED 0x20000000
#define PAGE_ENCLAVE_MASK 0x10000000
#define PAGE_ENCLAVE_DECOMMIT 0x10000000
#define PAGE_ENCLAVE_SS_FIRST 0x10000001
#define PAGE_ENCLAVE_SS_REST 0x10000002
#define SEC_PARTITION_OWNER_HANDLE 0x40000
#define SEC_64K_PAGES 0x80000
#define SEC_FILE 0x800000
#define SEC_IMAGE 0x1000000
#define SEC_PROTECTED_IMAGE 0x2000000
#define SEC_RESERVE 0x4000000
#define SEC_COMMIT 0x8000000
#define SEC_NOCACHE 0x10000000
#define SEC_WRITECOMBINE 0x40000000
#define SEC_LARGE_PAGES 0x80000000
#define SEC_IMAGE_NO_EXECUTE 0x11000000
#define MemSectionExtendedParameterInvalidType 0
#define MemSectionExtendedParameterUserPhysicalFlags 1
#define MemSectionExtendedParameterNumaNode 2
#define MemSectionExtendedParameterSigningLevel 3
#define MemSectionExtendedParameterMax 4
#define HEAP_NONE 0x0
#define HEAP_NO_SERIALIZE 0x1
#define HEAP_GROWABLE 0x2
#define HEAP_GENERATE_EXCEPTIONS 0x4
#define HEAP_ZERO_MEMORY 0x8
#define HEAP_REALLOC_IN_PLACE_ONLY 0x10
#define HEAP_TAIL_CHECKING_ENABLED 0x20
#define HEAP_FREE_CHECKING_ENABLED 0x40
#define HEAP_DISABLE_COALESCE_ON_FREE 0x80
#define HEAP_CREATE_ALIGN_16 0x10000
#define HEAP_CREATE_ENABLE_TRACING 0x20000
#define HEAP_CREATE_ENABLE_EXECUTE 0x40000
#define HEAP_MAXIMUM_TAG 0xfff
#define HEAP_PSEUDO_TAG_FLAG 0x8000
#define HEAP_TAG_SHIFT 0x12
#define HEAP_CREATE_SEGMENT_HEAP 0x100
#define HEAP_CREATE_HARDENED 0x200
#define MEM_UNMAP_NONE 0x0
#define MEM_UNMAP_WITH_TRANSIENT_BOOST 0x1
#define MEM_PRESERVE_PLACEHOLDER 0x2
#define MemoryPartitionInfo 0
#define MemoryPartitionDedicatedMemoryInfo 1
#define LHND 0x42
#define LMEM_FIXED 0x0
#define LMEM_MOVEABLE 0x2
#define LMEM_ZEROINIT 0x40
#define LPTR 0x40
#define NONZEROLHND 0x2
#define NONZEROLPTR 0x0
#define MemoryRegionInfo 0
#define FILE_MAP_WRITE 0x2
#define FILE_MAP_READ 0x4
#define FILE_MAP_ALL_ACCESS 0xf001f
#define FILE_MAP_EXECUTE 0x20
#define FILE_MAP_COPY 0x1
#define FILE_MAP_RESERVE 0x80000000
#define FILE_MAP_TARGETS_INVALID 0x40000000
#define FILE_MAP_LARGE_PAGES 0x20000000
#define LowMemoryResourceNotification 0
#define HighMemoryResourceNotification 1
#define SECTION_ALL_ACCESS 0xf001f
#define SECTION_QUERY 0x1
#define SECTION_MAP_WRITE 0x2
#define SECTION_MAP_READ 0x4
#define SECTION_MAP_EXECUTE 0x8
#define SECTION_EXTEND_SIZE 0x10
#define SECTION_MAP_EXECUTE_EXPLICIT 0x20
#define HeapCompatibilityInformation 0
#define HeapEnableTerminationOnCorruption 1
#define HeapOptimizeResources 3
#define HeapTag 7

typedef struct _PROCESS_HEAP_ENTRY {
    void* lpData;
    unsigned int cbData;
    unsigned char cbOverhead;
    unsigned char iRegionIndex;
    unsigned short wFlags;
    void* Anonymous;
} PROCESS_HEAP_ENTRY;

typedef struct _MEMORY_BASIC_INFORMATION32 {
    unsigned int BaseAddress;
    unsigned int AllocationBase;
    void* AllocationProtect;
    unsigned int RegionSize;
    void* State;
    void* Protect;
    void* Type;
} MEMORY_BASIC_INFORMATION32;

typedef struct _MEM_EXTENDED_PARAMETER {
    void* Anonymous1;
    void* Anonymous2;
} MEM_EXTENDED_PARAMETER;

typedef struct _WIN32_MEMORY_REGION_INFORMATION {
    void* AllocationBase;
    unsigned int AllocationProtect;
    void* Anonymous;
    unsigned long long RegionSize;
    unsigned long long CommitSize;
} WIN32_MEMORY_REGION_INFORMATION;

typedef struct _MEMORY_PARTITION_DEDICATED_MEMORY_ATTRIBUTE {
    void* Type;
    unsigned int Reserved;
    unsigned long long Value;
} MEMORY_PARTITION_DEDICATED_MEMORY_ATTRIBUTE;

typedef struct _MEMORY_BASIC_INFORMATION {
    void* BaseAddress;
    void* AllocationBase;
    void* AllocationProtect;
    unsigned short PartitionId;
    unsigned long long RegionSize;
    void* State;
    void* Protect;
    void* Type;
} MEMORY_BASIC_INFORMATION;

typedef struct _MEMORY_BASIC_INFORMATION {
    void* BaseAddress;
    void* AllocationBase;
    void* AllocationProtect;
    unsigned long long RegionSize;
    void* State;
    void* Protect;
    void* Type;
} MEMORY_BASIC_INFORMATION;

typedef struct _WIN32_MEMORY_NUMA_PERFORMANCE_INFORMATION_OUTPUT {
    unsigned int EntryCount;
    void* PerformanceEntries[1];
} WIN32_MEMORY_NUMA_PERFORMANCE_INFORMATION_OUTPUT;

typedef struct _MEM_ADDRESS_REQUIREMENTS {
    void* LowestStartingAddress;
    void* HighestEndingAddress;
    unsigned long long Alignment;
} MEM_ADDRESS_REQUIREMENTS;

typedef struct _WIN32_MEMORY_PARTITION_INFORMATION {
    unsigned int Flags;
    unsigned int NumaNode;
    unsigned int Channel;
    unsigned int NumberOfNumaNodes;
    unsigned long long ResidentAvailablePages;
    unsigned long long CommittedPages;
    unsigned long long CommitLimit;
    unsigned long long PeakCommitment;
    unsigned long long TotalNumberOfPages;
    unsigned long long AvailablePages;
    unsigned long long ZeroPages;
    unsigned long long FreePages;
    unsigned long long StandbyPages;
    unsigned long long Reserved[16];
    unsigned long long MaximumCommitLimit;
    unsigned long long Reserved2;
    unsigned int PartitionId;
} WIN32_MEMORY_PARTITION_INFORMATION;

typedef struct _MEMORY_PARTITION_DEDICATED_MEMORY_INFORMATION {
    unsigned int NextEntryOffset;
    unsigned int SizeOfInformation;
    unsigned int Flags;
    unsigned int AttributesOffset;
    unsigned int AttributeCount;
    unsigned int Reserved;
    unsigned long long TypeId;
} MEMORY_PARTITION_DEDICATED_MEMORY_INFORMATION;

typedef struct _HEAP_SUMMARY {
    unsigned int cb;
    unsigned long long cbAllocated;
    unsigned long long cbCommitted;
    unsigned long long cbReserved;
    unsigned long long cbMaxReserve;
} HEAP_SUMMARY;

typedef struct _AtlThunkData_t {
    long long Value;
} AtlThunkData_t;

typedef struct _WIN32_MEMORY_RANGE_ENTRY {
    void* VirtualAddress;
    unsigned long long NumberOfBytes;
} WIN32_MEMORY_RANGE_ENTRY;

typedef struct _MEMORY_BASIC_INFORMATION64 {
    unsigned long long BaseAddress;
    unsigned long long AllocationBase;
    void* AllocationProtect;
    unsigned int __alignment1;
    unsigned long long RegionSize;
    void* State;
    void* Protect;
    void* Type;
    unsigned int __alignment2;
} MEMORY_BASIC_INFORMATION64;

typedef struct _CFG_CALL_TARGET_INFO {
    unsigned long long Offset;
    unsigned long long Flags;
} CFG_CALL_TARGET_INFO;

typedef struct _MEMORY_MAPPED_VIEW_ADDRESS {
    void* Value;
} MEMORY_MAPPED_VIEW_ADDRESS;

typedef struct _WIN32_MEMORY_NUMA_PERFORMANCE_ENTRY {
    unsigned int InitiatorNodeNumber;
    unsigned int TargetNodeNumber;
    unsigned char DataType;
    void* Flags;
    unsigned long long MinTransferSizeInBytes;
    unsigned long long EntryValue;
} WIN32_MEMORY_NUMA_PERFORMANCE_ENTRY;

