// Generated by entc-win32gen from `Windows.Win32.System.Registry`.
// Do not edit by hand. Re-run the generator to refresh.

typedef unsigned char       BYTE;
typedef unsigned short      WORD;
typedef unsigned long       DWORD;
typedef unsigned long long  ULONGLONG;
typedef long                LONG;
typedef unsigned long       ULONG;
typedef int                 BOOL;
typedef void*               PVOID;
typedef void*               HANDLE;

#define HKEY_CLASSES_ROOT -2147483648
#define HKEY_CURRENT_USER -2147483647
#define HKEY_LOCAL_MACHINE -2147483646
#define HKEY_USERS -2147483645
#define HKEY_PERFORMANCE_DATA -2147483644
#define HKEY_PERFORMANCE_TEXT -2147483568
#define HKEY_PERFORMANCE_NLSTEXT -2147483552
#define HKEY_CURRENT_CONFIG -2147483643
#define HKEY_DYN_DATA -2147483642
#define HKEY_CURRENT_USER_LOCAL_SETTINGS -2147483641
#define REG_PROCESS_APPKEY 0x1
#define REG_USE_CURRENT_SECURITY_CONTEXT 0x2
#define PROVIDER_KEEPS_VALUE_LENGTH 0x1
#define REG_MUI_STRING_TRUNCATE 0x1
#define REG_SECURE_CONNECTION 0x1
#define REG_ALLOW_TRANSPORT_FALLBACK 0x2
#define REG_ALLOW_UNSECURE_CONNECTION 0x4
// SKIPPED const REGSTR_KEY_CLASS: non-integer constant
// SKIPPED const REGSTR_KEY_CONFIG: non-integer constant
// SKIPPED const REGSTR_KEY_ENUM: non-integer constant
// SKIPPED const REGSTR_KEY_ROOTENUM: non-integer constant
// SKIPPED const REGSTR_KEY_BIOSENUM: non-integer constant
// SKIPPED const REGSTR_KEY_ACPIENUM: non-integer constant
// SKIPPED const REGSTR_KEY_PCMCIAENUM: non-integer constant
// SKIPPED const REGSTR_KEY_PCIENUM: non-integer constant
// SKIPPED const REGSTR_KEY_VPOWERDENUM: non-integer constant
// SKIPPED const REGSTR_KEY_ISAENUM: non-integer constant
// SKIPPED const REGSTR_KEY_EISAENUM: non-integer constant
// SKIPPED const REGSTR_KEY_LOGCONFIG: non-integer constant
// SKIPPED const REGSTR_KEY_SYSTEMBOARD: non-integer constant
// SKIPPED const REGSTR_KEY_APM: non-integer constant
// SKIPPED const REGSTR_KEY_INIUPDATE: non-integer constant
// SKIPPED const REG_KEY_INSTDEV: non-integer constant
// SKIPPED const REGSTR_KEY_DOSOPTCDROM: non-integer constant
// SKIPPED const REGSTR_KEY_DOSOPTMOUSE: non-integer constant
// SKIPPED const REGSTR_KEY_KNOWNDOCKINGSTATES: non-integer constant
// SKIPPED const REGSTR_KEY_DEVICEPARAMETERS: non-integer constant
// SKIPPED const REGSTR_KEY_DRIVERPARAMETERS: non-integer constant
// SKIPPED const REGSTR_DEFAULT_INSTANCE: non-integer constant
// SKIPPED const REGSTR_PATH_SETUP: non-integer constant
// SKIPPED const REGSTR_PATH_DRIVERSIGN: non-integer constant
// SKIPPED const REGSTR_PATH_NONDRIVERSIGN: non-integer constant
// SKIPPED const REGSTR_PATH_DRIVERSIGN_POLICY: non-integer constant
// SKIPPED const REGSTR_PATH_NONDRIVERSIGN_POLICY: non-integer constant
// SKIPPED const REGSTR_PATH_PIFCONVERT: non-integer constant
// SKIPPED const REGSTR_PATH_MSDOSOPTS: non-integer constant
// SKIPPED const REGSTR_PATH_NOSUGGMSDOS: non-integer constant
// SKIPPED const REGSTR_PATH_NEWDOSBOX: non-integer constant
// SKIPPED const REGSTR_PATH_RUNONCE: non-integer constant
// SKIPPED const REGSTR_PATH_RUNONCEEX: non-integer constant
// SKIPPED const REGSTR_PATH_RUN: non-integer constant
// SKIPPED const REGSTR_PATH_RUNSERVICESONCE: non-integer constant
// SKIPPED const REGSTR_PATH_RUNSERVICES: non-integer constant
// SKIPPED const REGSTR_PATH_EXPLORER: non-integer constant
// SKIPPED const REGSTR_PATH_PROPERTYSYSTEM: non-integer constant
// SKIPPED const REGSTR_PATH_DETECT: non-integer constant
// SKIPPED const REGSTR_PATH_APPPATHS: non-integer constant
// SKIPPED const REGSTR_PATH_UNINSTALL: non-integer constant
// SKIPPED const REGSTR_PATH_REALMODENET: non-integer constant
// SKIPPED const REGSTR_PATH_NETEQUIV: non-integer constant
// SKIPPED const REGSTR_PATH_CVNETWORK: non-integer constant
// SKIPPED const REGSTR_PATH_WMI_SECURITY: non-integer constant
// SKIPPED const REGSTR_PATH_RELIABILITY: non-integer constant
// SKIPPED const REGSTR_PATH_RELIABILITY_POLICY: non-integer constant
// SKIPPED const REGSTR_PATH_RELIABILITY_POLICY_SHUTDOWNREASONUI: non-integer constant
// SKIPPED const REGSTR_PATH_RELIABILITY_POLICY_SNAPSHOT: non-integer constant
// SKIPPED const REGSTR_PATH_RELIABILITY_POLICY_REPORTSNAPSHOT: non-integer constant
// SKIPPED const REGSTR_PATH_REINSTALL: non-integer constant
// SKIPPED const REGSTR_PATH_NT_CURRENTVERSION: non-integer constant
// SKIPPED const REGSTR_PATH_VOLUMECACHE: non-integer constant
// SKIPPED const REGSTR_VAL_DISPLAY: non-integer constant
// SKIPPED const REGSTR_PATH_IDCONFIGDB: non-integer constant
// SKIPPED const REGSTR_PATH_CRITICALDEVICEDATABASE: non-integer constant
// SKIPPED const REGSTR_PATH_CLASS: non-integer constant
// SKIPPED const REGSTR_PATH_DISPLAYSETTINGS: non-integer constant
// SKIPPED const REGSTR_PATH_FONTS: non-integer constant
// SKIPPED const REGSTR_PATH_ENUM: non-integer constant
// SKIPPED const REGSTR_PATH_ROOT: non-integer constant
// SKIPPED const REGSTR_PATH_CURRENTCONTROLSET: non-integer constant
// SKIPPED const REGSTR_PATH_SYSTEMENUM: non-integer constant
// SKIPPED const REGSTR_PATH_HWPROFILES: non-integer constant
// SKIPPED const REGSTR_PATH_HWPROFILESCURRENT: non-integer constant
// SKIPPED const REGSTR_PATH_CLASS_NT: non-integer constant
// SKIPPED const REGSTR_PATH_PER_HW_ID_STORAGE: non-integer constant
// SKIPPED const REGSTR_PATH_DEVICE_CLASSES: non-integer constant
// SKIPPED const REGSTR_PATH_CODEVICEINSTALLERS: non-integer constant
// SKIPPED const REGSTR_PATH_BUSINFORMATION: non-integer constant
// SKIPPED const REGSTR_PATH_SERVICES: non-integer constant
// SKIPPED const REGSTR_PATH_VXD: non-integer constant
// SKIPPED const REGSTR_PATH_IOS: non-integer constant
// SKIPPED const REGSTR_PATH_VMM: non-integer constant
// SKIPPED const REGSTR_PATH_VPOWERD: non-integer constant
// SKIPPED const REGSTR_PATH_VNETSUP: non-integer constant
// SKIPPED const REGSTR_PATH_NWREDIR: non-integer constant
// SKIPPED const REGSTR_PATH_NCPSERVER: non-integer constant
// SKIPPED const REGSTR_PATH_VCOMM: non-integer constant
// SKIPPED const REGSTR_PATH_IOARB: non-integer constant
// SKIPPED const REGSTR_PATH_ADDRARB: non-integer constant
// SKIPPED const REGSTR_PATH_DMAARB: non-integer constant
// SKIPPED const REGSTR_PATH_IRQARB: non-integer constant
// SKIPPED const REGSTR_PATH_CODEPAGE: non-integer constant
// SKIPPED const REGSTR_PATH_FILESYSTEM: non-integer constant
// SKIPPED const REGSTR_PATH_FILESYSTEM_NOVOLTRACK: non-integer constant
// SKIPPED const REGSTR_PATH_CDFS: non-integer constant
// SKIPPED const REGSTR_PATH_WINBOOT: non-integer constant
// SKIPPED const REGSTR_PATH_INSTALLEDFILES: non-integer constant
// SKIPPED const REGSTR_PATH_VMM32FILES: non-integer constant
#define REGSTR_MAX_VALUE_LENGTH 0x100
// SKIPPED const REGSTR_KEY_DEVICE_PROPERTIES: non-integer constant
// SKIPPED const REGSTR_VAL_SERVICE: non-integer constant
// SKIPPED const REGSTR_VAL_CLASSGUID: non-integer constant
// SKIPPED const REGSTR_VAL_DISABLECOUNT: non-integer constant
// SKIPPED const REGSTR_VAL_DOCKSTATE: non-integer constant
// SKIPPED const REGSTR_VAL_DEVICE_INSTANCE: non-integer constant
// SKIPPED const REGSTR_VAL_SYMBOLIC_LINK: non-integer constant
// SKIPPED const REGSTR_VAL_DEFAULT: non-integer constant
// SKIPPED const REGSTR_VAL_LOWERFILTERS: non-integer constant
// SKIPPED const REGSTR_VAL_UPPERFILTERS: non-integer constant
// SKIPPED const REGSTR_VAL_LOCATION_INFORMATION: non-integer constant
// SKIPPED const REGSTR_VAL_UI_NUMBER: non-integer constant
// SKIPPED const REGSTR_VAL_UI_NUMBER_DESC_FORMAT: non-integer constant
// SKIPPED const REGSTR_VAL_CAPABILITIES: non-integer constant
// SKIPPED const REGSTR_VAL_ADDRESS: non-integer constant
// SKIPPED const REGSTR_VAL_DEVICE_TYPE: non-integer constant
// SKIPPED const REGSTR_VAL_DEVICE_CHARACTERISTICS: non-integer constant
// SKIPPED const REGSTR_VAL_DEVICE_SECURITY_DESCRIPTOR: non-integer constant
// SKIPPED const REGSTR_VAL_DEVICE_EXCLUSIVE: non-integer constant
// SKIPPED const REGSTR_VAL_RESOURCE_PICKER_TAGS: non-integer constant
// SKIPPED const REGSTR_VAL_RESOURCE_PICKER_EXCEPTIONS: non-integer constant
// SKIPPED const REGSTR_VAL_CUSTOM_PROPERTY_CACHE_DATE: non-integer constant
// SKIPPED const REGSTR_VAL_CUSTOM_PROPERTY_HW_ID_KEY: non-integer constant
// SKIPPED const REGSTR_VAL_LAST_UPDATE_TIME: non-integer constant
// SKIPPED const REGSTR_VAL_CONTAINERID: non-integer constant
// SKIPPED const REGSTR_VAL_EJECT_PRIORITY: non-integer constant
// SKIPPED const REGSTR_KEY_CONTROL: non-integer constant
// SKIPPED const REGSTR_VAL_ACTIVESERVICE: non-integer constant
// SKIPPED const REGSTR_VAL_LINKED: non-integer constant
// SKIPPED const REGSTR_VAL_PHYSICALDEVICEOBJECT: non-integer constant
// SKIPPED const REGSTR_VAL_REMOVAL_POLICY: non-integer constant
// SKIPPED const REGSTR_KEY_FILTERS: non-integer constant
// SKIPPED const REGSTR_VAL_LOWER_FILTER_DEFAULT_LEVEL: non-integer constant
// SKIPPED const REGSTR_VAL_UPPER_FILTER_DEFAULT_LEVEL: non-integer constant
// SKIPPED const REGSTR_KEY_LOWER_FILTER_LEVEL_DEFAULT: non-integer constant
// SKIPPED const REGSTR_KEY_UPPER_FILTER_LEVEL_DEFAULT: non-integer constant
// SKIPPED const REGSTR_VAL_LOWER_FILTER_LEVELS: non-integer constant
// SKIPPED const REGSTR_VAL_UPPER_FILTER_LEVELS: non-integer constant
// SKIPPED const REGSTR_VAL_CURRENT_VERSION: non-integer constant
// SKIPPED const REGSTR_VAL_CURRENT_BUILD: non-integer constant
// SKIPPED const REGSTR_VAL_CURRENT_CSDVERSION: non-integer constant
// SKIPPED const REGSTR_VAL_CURRENT_TYPE: non-integer constant
// SKIPPED const REGSTR_VAL_BITSPERPIXEL: non-integer constant
// SKIPPED const REGSTR_VAL_RESOLUTION: non-integer constant
// SKIPPED const REGSTR_VAL_DPILOGICALX: non-integer constant
// SKIPPED const REGSTR_VAL_DPILOGICALY: non-integer constant
// SKIPPED const REGSTR_VAL_DPIPHYSICALX: non-integer constant
// SKIPPED const REGSTR_VAL_DPIPHYSICALY: non-integer constant
// SKIPPED const REGSTR_VAL_REFRESHRATE: non-integer constant
// SKIPPED const REGSTR_VAL_DISPLAYFLAGS: non-integer constant
// SKIPPED const REGSTR_PATH_CONTROLPANEL: non-integer constant
// SKIPPED const REGSTR_PATH_CONTROLSFOLDER: non-integer constant
// SKIPPED const REGSTR_VAL_DOSCP: non-integer constant
// SKIPPED const REGSTR_VAL_WINCP: non-integer constant
// SKIPPED const REGSTR_VAL_DONTUSEMEM: non-integer constant
// SKIPPED const REGSTR_VAL_SYSTEMROOT: non-integer constant
// SKIPPED const REGSTR_VAL_BOOTCOUNT: non-integer constant
// SKIPPED const REGSTR_VAL_REALNETSTART: non-integer constant
// SKIPPED const REGSTR_VAL_MEDIA: non-integer constant
// SKIPPED const REGSTR_VAL_CONFIG: non-integer constant
// SKIPPED const REGSTR_VAL_DEVICEPATH: non-integer constant
// SKIPPED const REGSTR_VAL_SRCPATH: non-integer constant
// SKIPPED const REGSTR_VAL_DRIVERCACHEPATH: non-integer constant
// SKIPPED const REGSTR_VAL_OLDWINDIR: non-integer constant
// SKIPPED const REGSTR_VAL_SETUPFLAGS: non-integer constant
// SKIPPED const REGSTR_VAL_REGOWNER: non-integer constant
// SKIPPED const REGSTR_VAL_REGORGANIZATION: non-integer constant
// SKIPPED const REGSTR_VAL_LICENSINGINFO: non-integer constant
// SKIPPED const REGSTR_VAL_OLDMSDOSVER: non-integer constant
// SKIPPED const REGSTR_VAL_FIRSTINSTALLDATETIME: non-integer constant
// SKIPPED const REGSTR_VAL_INSTALLTYPE: non-integer constant
#define IT_COMPACT 0x0
#define IT_TYPICAL 0x1
#define IT_PORTABLE 0x2
#define IT_CUSTOM 0x3
// SKIPPED const REGSTR_VAL_WRAPPER: non-integer constant
// SKIPPED const REGSTR_KEY_RUNHISTORY: non-integer constant
// SKIPPED const REGSTR_VAL_LASTALIVEINTERVAL: non-integer constant
// SKIPPED const REGSTR_VAL_DIRTYSHUTDOWN: non-integer constant
// SKIPPED const REGSTR_VAL_DIRTYSHUTDOWNTIME: non-integer constant
// SKIPPED const REGSTR_VAL_BT: non-integer constant
// SKIPPED const REGSTR_VAL_LASTCOMPUTERNAME: non-integer constant
// SKIPPED const REGSTR_VAL_LASTALIVEBT: non-integer constant
// SKIPPED const REGSTR_VAL_LASTALIVESTAMP: non-integer constant
// SKIPPED const REGSTR_VAL_LASTALIVESTAMPFORCED: non-integer constant
// SKIPPED const REGSTR_VAL_LASTALIVESTAMPINTERVAL: non-integer constant
// SKIPPED const REGSTR_VAL_LASTALIVESTAMPPOLICYINTERVAL: non-integer constant
// SKIPPED const REGSTR_VAL_LASTALIVEUPTIME: non-integer constant
// SKIPPED const REGSTR_VAL_LASTALIVEPMPOLICY: non-integer constant
// SKIPPED const REGSTR_VAL_REASONCODE: non-integer constant
// SKIPPED const REGSTR_VAL_COMMENT: non-integer constant
// SKIPPED const REGSTR_VAL_SHUTDOWNREASON: non-integer constant
// SKIPPED const REGSTR_VAL_SHUTDOWNREASON_CODE: non-integer constant
// SKIPPED const REGSTR_VAL_SHUTDOWNREASON_COMMENT: non-integer constant
// SKIPPED const REGSTR_VAL_SHUTDOWNREASON_PROCESS: non-integer constant
// SKIPPED const REGSTR_VAL_SHUTDOWNREASON_USERNAME: non-integer constant
// SKIPPED const REGSTR_VAL_SHOWREASONUI: non-integer constant
// SKIPPED const REGSTR_VAL_SHUTDOWN_IGNORE_PREDEFINED: non-integer constant
// SKIPPED const REGSTR_VAL_SHUTDOWN_STATE_SNAPSHOT: non-integer constant
// SKIPPED const REGSTR_KEY_SETUP: non-integer constant
// SKIPPED const REGSTR_VAL_BOOTDIR: non-integer constant
// SKIPPED const REGSTR_VAL_WINBOOTDIR: non-integer constant
// SKIPPED const REGSTR_VAL_WINDIR: non-integer constant
// SKIPPED const REGSTR_VAL_APPINSTPATH: non-integer constant
// SKIPPED const REGSTR_KEY_EBDFILESLOCAL: non-integer constant
// SKIPPED const REGSTR_KEY_EBDFILESKEYBOARD: non-integer constant
// SKIPPED const REGSTR_KEY_EBDAUTOEXECBATLOCAL: non-integer constant
// SKIPPED const REGSTR_KEY_EBDAUTOEXECBATKEYBOARD: non-integer constant
// SKIPPED const REGSTR_KEY_EBDCONFIGSYSLOCAL: non-integer constant
// SKIPPED const REGSTR_KEY_EBDCONFIGSYSKEYBOARD: non-integer constant
// SKIPPED const REGSTR_VAL_POLICY: non-integer constant
// SKIPPED const REGSTR_VAL_BEHAVIOR_ON_FAILED_VERIFY: non-integer constant
#define DRIVERSIGN_NONE 0x0
#define DRIVERSIGN_WARNING 0x1
#define DRIVERSIGN_BLOCKING 0x2
// SKIPPED const REGSTR_VAL_MSDOSMODE: non-integer constant
// SKIPPED const REGSTR_VAL_MSDOSMODEDISCARD: non-integer constant
// SKIPPED const REGSTR_VAL_DOSOPTGLOBALFLAGS: non-integer constant
#define DOSOPTGF_DEFCLEAN 1
// SKIPPED const REGSTR_VAL_DOSOPTFLAGS: non-integer constant
// SKIPPED const REGSTR_VAL_OPTORDER: non-integer constant
// SKIPPED const REGSTR_VAL_CONFIGSYS: non-integer constant
// SKIPPED const REGSTR_VAL_AUTOEXEC: non-integer constant
// SKIPPED const REGSTR_VAL_STDDOSOPTION: non-integer constant
// SKIPPED const REGSTR_VAL_DOSOPTTIP: non-integer constant
#define DOSOPTF_DEFAULT 1
#define DOSOPTF_SUPPORTED 2
#define DOSOPTF_ALWAYSUSE 4
#define DOSOPTF_USESPMODE 8
#define DOSOPTF_PROVIDESUMB 16
#define DOSOPTF_NEEDSETUP 32
#define DOSOPTF_INDOSSTART 64
#define DOSOPTF_MULTIPLE 128
#define SUF_FIRSTTIME 1
#define SUF_EXPRESS 2
#define SUF_BATCHINF 4
#define SUF_CLEAN 8
#define SUF_INSETUP 16
#define SUF_NETSETUP 32
#define SUF_NETHDBOOT 64
#define SUF_NETRPLBOOT 128
#define SUF_SBSCOPYOK 256
// SKIPPED const REGSTR_VAL_DOSPAGER: non-integer constant
// SKIPPED const REGSTR_VAL_VXDGROUPS: non-integer constant
// SKIPPED const REGSTR_VAL_VPOWERDFLAGS: non-integer constant
#define VPDF_DISABLEPWRMGMT 0x1
#define VPDF_FORCEAPM10MODE 0x2
#define VPDF_SKIPINTELSLCHECK 0x4
#define VPDF_DISABLEPWRSTATUSPOLL 0x8
#define VPDF_DISABLERINGRESUME 0x10
#define VPDF_SHOWMULTIBATT 0x20
#define BIF_SHOWSIMILARDRIVERS 0x1
#define BIF_RAWDEVICENEEDSDRIVER 0x2
// SKIPPED const REGSTR_VAL_WORKGROUP: non-integer constant
// SKIPPED const REGSTR_VAL_DIRECTHOST: non-integer constant
// SKIPPED const REGSTR_VAL_FILESHARING: non-integer constant
// SKIPPED const REGSTR_VAL_PRINTSHARING: non-integer constant
// SKIPPED const REGSTR_VAL_FIRSTNETDRIVE: non-integer constant
// SKIPPED const REGSTR_VAL_MAXCONNECTIONS: non-integer constant
// SKIPPED const REGSTR_VAL_APISUPPORT: non-integer constant
// SKIPPED const REGSTR_VAL_MAXRETRY: non-integer constant
// SKIPPED const REGSTR_VAL_MINRETRY: non-integer constant
// SKIPPED const REGSTR_VAL_SUPPORTLFN: non-integer constant
// SKIPPED const REGSTR_VAL_SUPPORTBURST: non-integer constant
// SKIPPED const REGSTR_VAL_SUPPORTTUNNELLING: non-integer constant
// SKIPPED const REGSTR_VAL_FULLTRACE: non-integer constant
// SKIPPED const REGSTR_VAL_READCACHING: non-integer constant
// SKIPPED const REGSTR_VAL_SHOWDOTS: non-integer constant
// SKIPPED const REGSTR_VAL_GAPTIME: non-integer constant
// SKIPPED const REGSTR_VAL_SEARCHMODE: non-integer constant
// SKIPPED const REGSTR_VAL_SHELLVERSION: non-integer constant
// SKIPPED const REGSTR_VAL_MAXLIP: non-integer constant
// SKIPPED const REGSTR_VAL_PRESERVECASE: non-integer constant
// SKIPPED const REGSTR_VAL_OPTIMIZESFN: non-integer constant
// SKIPPED const REGSTR_VAL_NCP_BROWSEMASTER: non-integer constant
// SKIPPED const REGSTR_VAL_NCP_USEPEERBROWSING: non-integer constant
// SKIPPED const REGSTR_VAL_NCP_USESAP: non-integer constant
// SKIPPED const REGSTR_VAL_PCCARD_POWER: non-integer constant
// SKIPPED const REGSTR_VAL_WIN31FILESYSTEM: non-integer constant
// SKIPPED const REGSTR_VAL_PRESERVELONGNAMES: non-integer constant
// SKIPPED const REGSTR_VAL_DRIVEWRITEBEHIND: non-integer constant
// SKIPPED const REGSTR_VAL_ASYNCFILECOMMIT: non-integer constant
// SKIPPED const REGSTR_VAL_PATHCACHECOUNT: non-integer constant
// SKIPPED const REGSTR_VAL_NAMECACHECOUNT: non-integer constant
// SKIPPED const REGSTR_VAL_CONTIGFILEALLOC: non-integer constant
// SKIPPED const REGSTR_VAL_FREESPACERATIO: non-integer constant
// SKIPPED const REGSTR_VAL_VOLIDLETIMEOUT: non-integer constant
// SKIPPED const REGSTR_VAL_BUFFIDLETIMEOUT: non-integer constant
// SKIPPED const REGSTR_VAL_BUFFAGETIMEOUT: non-integer constant
// SKIPPED const REGSTR_VAL_NAMENUMERICTAIL: non-integer constant
// SKIPPED const REGSTR_VAL_READAHEADTHRESHOLD: non-integer constant
// SKIPPED const REGSTR_VAL_DOUBLEBUFFER: non-integer constant
// SKIPPED const REGSTR_VAL_SOFTCOMPATMODE: non-integer constant
// SKIPPED const REGSTR_VAL_DRIVESPINDOWN: non-integer constant
// SKIPPED const REGSTR_VAL_FORCEPMIO: non-integer constant
// SKIPPED const REGSTR_VAL_FORCERMIO: non-integer constant
// SKIPPED const REGSTR_VAL_LASTBOOTPMDRVS: non-integer constant
// SKIPPED const REGSTR_VAL_ACSPINDOWNPREVIOUS: non-integer constant
// SKIPPED const REGSTR_VAL_BATSPINDOWNPREVIOUS: non-integer constant
// SKIPPED const REGSTR_VAL_VIRTUALHDIRQ: non-integer constant
// SKIPPED const REGSTR_VAL_SRVNAMECACHECOUNT: non-integer constant
// SKIPPED const REGSTR_VAL_SRVNAMECACHE: non-integer constant
// SKIPPED const REGSTR_VAL_SRVNAMECACHENETPROV: non-integer constant
// SKIPPED const REGSTR_VAL_AUTOMOUNT: non-integer constant
// SKIPPED const REGSTR_VAL_COMPRESSIONMETHOD: non-integer constant
// SKIPPED const REGSTR_VAL_COMPRESSIONTHRESHOLD: non-integer constant
// SKIPPED const REGSTR_VAL_ACDRIVESPINDOWN: non-integer constant
// SKIPPED const REGSTR_VAL_BATDRIVESPINDOWN: non-integer constant
// SKIPPED const REGSTR_VAL_CDCACHESIZE: non-integer constant
// SKIPPED const REGSTR_VAL_CDPREFETCH: non-integer constant
// SKIPPED const REGSTR_VAL_CDPREFETCHTAIL: non-integer constant
// SKIPPED const REGSTR_VAL_CDRAWCACHE: non-integer constant
// SKIPPED const REGSTR_VAL_CDEXTERRORS: non-integer constant
// SKIPPED const REGSTR_VAL_CDSVDSENSE: non-integer constant
// SKIPPED const REGSTR_VAL_CDSHOWVERSIONS: non-integer constant
// SKIPPED const REGSTR_VAL_CDCOMPATNAMES: non-integer constant
// SKIPPED const REGSTR_VAL_CDNOREADAHEAD: non-integer constant
// SKIPPED const REGSTR_VAL_SCSI: non-integer constant
// SKIPPED const REGSTR_VAL_ESDI: non-integer constant
// SKIPPED const REGSTR_VAL_FLOP: non-integer constant
// SKIPPED const REGSTR_VAL_DISK: non-integer constant
// SKIPPED const REGSTR_VAL_CDROM: non-integer constant
// SKIPPED const REGSTR_VAL_TAPE: non-integer constant
// SKIPPED const REGSTR_VAL_SCANNER: non-integer constant
// SKIPPED const REGSTR_VAL_FLOPPY: non-integer constant
// SKIPPED const REGSTR_VAL_SCSITID: non-integer constant
// SKIPPED const REGSTR_VAL_SCSILUN: non-integer constant
// SKIPPED const REGSTR_VAL_REVLEVEL: non-integer constant
// SKIPPED const REGSTR_VAL_PRODUCTID: non-integer constant
// SKIPPED const REGSTR_VAL_PRODUCTTYPE: non-integer constant
// SKIPPED const REGSTR_VAL_DEVTYPE: non-integer constant
// SKIPPED const REGSTR_VAL_REMOVABLE: non-integer constant
// SKIPPED const REGSTR_VAL_CURDRVLET: non-integer constant
// SKIPPED const REGSTR_VAL_USRDRVLET: non-integer constant
// SKIPPED const REGSTR_VAL_SYNCDATAXFER: non-integer constant
// SKIPPED const REGSTR_VAL_AUTOINSNOTE: non-integer constant
// SKIPPED const REGSTR_VAL_DISCONNECT: non-integer constant
// SKIPPED const REGSTR_VAL_INT13: non-integer constant
// SKIPPED const REGSTR_VAL_PMODE_INT13: non-integer constant
// SKIPPED const REGSTR_VAL_USERSETTINGS: non-integer constant
// SKIPPED const REGSTR_VAL_NOIDE: non-integer constant
// SKIPPED const REGSTR_VAL_DISKCLASSNAME: non-integer constant
// SKIPPED const REGSTR_VAL_CDROMCLASSNAME: non-integer constant
// SKIPPED const REGSTR_VAL_FORCELOAD: non-integer constant
// SKIPPED const REGSTR_VAL_FORCEFIFO: non-integer constant
// SKIPPED const REGSTR_VAL_FORCECL: non-integer constant
// SKIPPED const REGSTR_VAL_NOUSECLASS: non-integer constant
// SKIPPED const REGSTR_VAL_NOINSTALLCLASS: non-integer constant
// SKIPPED const REGSTR_VAL_NODISPLAYCLASS: non-integer constant
// SKIPPED const REGSTR_VAL_SILENTINSTALL: non-integer constant
// SKIPPED const REGSTR_VAL_FSFILTERCLASS: non-integer constant
// SKIPPED const REGSTR_KEY_PCMCIA_CLASS: non-integer constant
// SKIPPED const REGSTR_KEY_SCSI_CLASS: non-integer constant
// SKIPPED const REGSTR_KEY_PORTS_CLASS: non-integer constant
// SKIPPED const REGSTR_KEY_MEDIA_CLASS: non-integer constant
// SKIPPED const REGSTR_KEY_DISPLAY_CLASS: non-integer constant
// SKIPPED const REGSTR_KEY_KEYBOARD_CLASS: non-integer constant
// SKIPPED const REGSTR_KEY_MOUSE_CLASS: non-integer constant
// SKIPPED const REGSTR_KEY_MONITOR_CLASS: non-integer constant
// SKIPPED const REGSTR_KEY_MODEM_CLASS: non-integer constant
// SKIPPED const REGSTR_VAL_PCMCIA_OPT: non-integer constant
#define PCMCIA_OPT_HAVE_SOCKET 1
#define PCMCIA_OPT_AUTOMEM 4
#define PCMCIA_OPT_NO_SOUND 8
#define PCMCIA_OPT_NO_AUDIO 16
#define PCMCIA_OPT_NO_APMREMOVE 32
// SKIPPED const REGSTR_VAL_PCMCIA_MEM: non-integer constant
#define PCMCIA_DEF_MEMBEGIN 0xc0000
#define PCMCIA_DEF_MEMEND 0xffffff
#define PCMCIA_DEF_MEMLEN 0x1000
// SKIPPED const REGSTR_VAL_PCMCIA_ALLOC: non-integer constant
// SKIPPED const REGSTR_VAL_PCMCIA_ATAD: non-integer constant
// SKIPPED const REGSTR_VAL_PCMCIA_SIZ: non-integer constant
#define PCMCIA_DEF_MIN_REGION 0x10000
// SKIPPED const REGSTR_VAL_P1284MDL: non-integer constant
// SKIPPED const REGSTR_VAL_P1284MFG: non-integer constant
// SKIPPED const REGSTR_VAL_ISAPNP: non-integer constant
// SKIPPED const REGSTR_VAL_ISAPNP_RDP_OVERRIDE: non-integer constant
// SKIPPED const REGSTR_VAL_PCI: non-integer constant
// SKIPPED const REGSTR_PCI_OPTIONS: non-integer constant
// SKIPPED const REGSTR_PCI_DUAL_IDE: non-integer constant
#define PCI_OPTIONS_USE_BIOS 1
#define PCI_OPTIONS_USE_IRQ_STEERING 2
#define AGP_FLAG_NO_1X_RATE 1
#define AGP_FLAG_NO_2X_RATE 2
#define AGP_FLAG_NO_4X_RATE 4
#define AGP_FLAG_NO_8X_RATE 8
#define AGP_FLAG_REVERSE_INITIALIZATION 128
#define AGP_FLAG_NO_SBA_ENABLE 256
#define AGP_FLAG_NO_FW_ENABLE 512
#define AGP_FLAG_SPECIAL_TARGET 1048575
#define AGP_FLAG_SPECIAL_RESERVE 1015808
// SKIPPED const REGSTR_KEY_CRASHES: non-integer constant
// SKIPPED const REGSTR_KEY_DANGERS: non-integer constant
// SKIPPED const REGSTR_KEY_DETMODVARS: non-integer constant
// SKIPPED const REGSTR_KEY_NDISINFO: non-integer constant
// SKIPPED const REGSTR_VAL_PROTINIPATH: non-integer constant
// SKIPPED const REGSTR_VAL_RESOURCES: non-integer constant
// SKIPPED const REGSTR_VAL_CRASHFUNCS: non-integer constant
// SKIPPED const REGSTR_VAL_CLASS: non-integer constant
// SKIPPED const REGSTR_VAL_CLASSDESC: non-integer constant
// SKIPPED const REGSTR_VAL_DEVDESC: non-integer constant
// SKIPPED const REGSTR_VAL_BOOTCONFIG: non-integer constant
// SKIPPED const REGSTR_VAL_DETFUNC: non-integer constant
// SKIPPED const REGSTR_VAL_DETFLAGS: non-integer constant
// SKIPPED const REGSTR_VAL_COMPATIBLEIDS: non-integer constant
// SKIPPED const REGSTR_VAL_DETCONFIG: non-integer constant
// SKIPPED const REGSTR_VAL_VERIFYKEY: non-integer constant
// SKIPPED const REGSTR_VAL_COMINFO: non-integer constant
// SKIPPED const REGSTR_VAL_INFNAME: non-integer constant
// SKIPPED const REGSTR_VAL_CARDSPECIFIC: non-integer constant
// SKIPPED const REGSTR_VAL_NETOSTYPE: non-integer constant
// SKIPPED const REGSTR_DATA_NETOS_NDIS: non-integer constant
// SKIPPED const REGSTR_DATA_NETOS_ODI: non-integer constant
// SKIPPED const REGSTR_DATA_NETOS_IPX: non-integer constant
// SKIPPED const REGSTR_VAL_MFG: non-integer constant
// SKIPPED const REGSTR_VAL_SCAN_ONLY_FIRST: non-integer constant
// SKIPPED const REGSTR_VAL_SHARE_IRQ: non-integer constant
// SKIPPED const REGSTR_VAL_NONSTANDARD_ATAPI: non-integer constant
// SKIPPED const REGSTR_VAL_IDE_FORCE_SERIALIZE: non-integer constant
#define REGSTR_VAL_MAX_HCID_LEN 0x400
// SKIPPED const REGSTR_VAL_HWREV: non-integer constant
// SKIPPED const REGSTR_VAL_ENABLEINTS: non-integer constant
#define REGDF_NOTDETIO 0x1
#define REGDF_NOTDETMEM 0x2
#define REGDF_NOTDETIRQ 0x4
#define REGDF_NOTDETDMA 0x8
#define REGDF_NEEDFULLCONFIG 0x10
#define REGDF_GENFORCEDCONFIG 0x20
#define REGDF_NODETCONFIG 0x8000
#define REGDF_CONFLICTIO 0x10000
#define REGDF_CONFLICTMEM 0x20000
#define REGDF_CONFLICTIRQ 0x40000
#define REGDF_CONFLICTDMA 0x80000
#define REGDF_MAPIRQ2TO9 0x100000
#define REGDF_NOTVERIFIED 0x80000000
// SKIPPED const REGSTR_VAL_APMBIOSVER: non-integer constant
// SKIPPED const REGSTR_VAL_APMFLAGS: non-integer constant
// SKIPPED const REGSTR_VAL_SLSUPPORT: non-integer constant
// SKIPPED const REGSTR_VAL_MACHINETYPE: non-integer constant
// SKIPPED const REGSTR_VAL_SETUPMACHINETYPE: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_UNKNOWN: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPC: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPCJR: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPCCONV: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPCXT: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPCXT_286: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPCAT: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_25: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_30_286: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_30: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_50: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_50Z: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_55SX: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_60: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_65SX: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_70: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_P70: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_70_80: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_80: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS2_90: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_IBMPS1: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_PHOENIX_PCAT: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_HP_VECTRA: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_ATT_PC: non-integer constant
// SKIPPED const REGSTR_MACHTYPE_ZENITH_PC: non-integer constant
// SKIPPED const REGSTR_VAL_APMMENUSUSPEND: non-integer constant
#define APMMENUSUSPEND_DISABLED 0x0
#define APMMENUSUSPEND_ENABLED 0x1
#define APMMENUSUSPEND_UNDOCKED 0x2
#define APMMENUSUSPEND_NOCHANGE 0x80
// SKIPPED const REGSTR_VAL_APMACTIMEOUT: non-integer constant
// SKIPPED const REGSTR_VAL_APMBATTIMEOUT: non-integer constant
#define APMTIMEOUT_DISABLED 0x0
// SKIPPED const REGSTR_VAL_APMSHUTDOWNPOWER: non-integer constant
// SKIPPED const REGSTR_VAL_BUSTYPE: non-integer constant
// SKIPPED const REGSTR_VAL_CPU: non-integer constant
// SKIPPED const REGSTR_VAL_NDP: non-integer constant
// SKIPPED const REGSTR_VAL_PNPBIOSVER: non-integer constant
// SKIPPED const REGSTR_VAL_PNPSTRUCOFFSET: non-integer constant
// SKIPPED const REGSTR_VAL_PCIBIOSVER: non-integer constant
// SKIPPED const REGSTR_VAL_HWMECHANISM: non-integer constant
// SKIPPED const REGSTR_VAL_LASTPCIBUSNUM: non-integer constant
// SKIPPED const REGSTR_VAL_CONVMEM: non-integer constant
// SKIPPED const REGSTR_VAL_EXTMEM: non-integer constant
// SKIPPED const REGSTR_VAL_COMPUTERNAME: non-integer constant
// SKIPPED const REGSTR_VAL_BIOSNAME: non-integer constant
// SKIPPED const REGSTR_VAL_BIOSVERSION: non-integer constant
// SKIPPED const REGSTR_VAL_BIOSDATE: non-integer constant
// SKIPPED const REGSTR_VAL_MODEL: non-integer constant
// SKIPPED const REGSTR_VAL_SUBMODEL: non-integer constant
// SKIPPED const REGSTR_VAL_REVISION: non-integer constant
// SKIPPED const REGSTR_VAL_FIFODEPTH: non-integer constant
// SKIPPED const REGSTR_VAL_RDINTTHRESHOLD: non-integer constant
// SKIPPED const REGSTR_VAL_WRINTTHRESHOLD: non-integer constant
// SKIPPED const REGSTR_VAL_PRIORITY: non-integer constant
// SKIPPED const REGSTR_VAL_DRIVER: non-integer constant
// SKIPPED const REGSTR_VAL_FUNCDESC: non-integer constant
// SKIPPED const REGSTR_VAL_FORCEDCONFIG: non-integer constant
// SKIPPED const REGSTR_VAL_CONFIGFLAGS: non-integer constant
// SKIPPED const REGSTR_VAL_CSCONFIGFLAGS: non-integer constant
#define CSCONFIGFLAG_BITS 0x7
#define CSCONFIGFLAG_DISABLED 0x1
#define CSCONFIGFLAG_DO_NOT_CREATE 0x2
#define CSCONFIGFLAG_DO_NOT_START 0x4
#define DMSTATEFLAG_APPLYTOALL 0x1
// SKIPPED const REGSTR_VAL_ROOT_DEVNODE: non-integer constant
// SKIPPED const REGSTR_VAL_RESERVED_DEVNODE: non-integer constant
// SKIPPED const REGSTR_PATH_MULTI_FUNCTION: non-integer constant
// SKIPPED const REGSTR_VAL_RESOURCE_MAP: non-integer constant
// SKIPPED const REGSTR_PATH_CHILD_PREFIX: non-integer constant
#define NUM_RESOURCE_MAP 0x100
// SKIPPED const REGSTR_VAL_MF_FLAGS: non-integer constant
#define MF_FLAGS_EVEN_IF_NO_RESOURCE 0x1
#define MF_FLAGS_NO_CREATE_IF_NO_RESOURCE 0x2
#define MF_FLAGS_FILL_IN_UNKNOWN_RESOURCE 0x4
#define MF_FLAGS_CREATE_BUT_NO_SHOW_DISABLED 0x8
// SKIPPED const REGSTR_VAL_EISA_RANGES: non-integer constant
// SKIPPED const REGSTR_VAL_EISA_FUNCTIONS: non-integer constant
// SKIPPED const REGSTR_VAL_EISA_FUNCTIONS_MASK: non-integer constant
// SKIPPED const REGSTR_VAL_EISA_FLAGS: non-integer constant
// SKIPPED const REGSTR_VAL_EISA_SIMULATE_INT15: non-integer constant
#define EISAFLAG_NO_IO_MERGE 0x1
#define EISAFLAG_SLOT_IO_FIRST 0x2
#define EISA_NO_MAX_FUNCTION 0xff
#define NUM_EISA_RANGES 0x4
// SKIPPED const REGSTR_VAL_DRVDESC: non-integer constant
// SKIPPED const REGSTR_VAL_DEVLOADER: non-integer constant
// SKIPPED const REGSTR_VAL_STATICVXD: non-integer constant
// SKIPPED const REGSTR_VAL_PROPERTIES: non-integer constant
// SKIPPED const REGSTR_VAL_MANUFACTURER: non-integer constant
// SKIPPED const REGSTR_VAL_EXISTS: non-integer constant
// SKIPPED const REGSTR_VAL_CMENUMFLAGS: non-integer constant
// SKIPPED const REGSTR_VAL_CMDRIVFLAGS: non-integer constant
// SKIPPED const REGSTR_VAL_ENUMERATOR: non-integer constant
// SKIPPED const REGSTR_VAL_DEVICEDRIVER: non-integer constant
// SKIPPED const REGSTR_VAL_PORTNAME: non-integer constant
// SKIPPED const REGSTR_VAL_INFPATH: non-integer constant
// SKIPPED const REGSTR_VAL_INFSECTION: non-integer constant
// SKIPPED const REGSTR_VAL_INFSECTIONEXT: non-integer constant
// SKIPPED const REGSTR_VAL_POLLING: non-integer constant
// SKIPPED const REGSTR_VAL_DONTLOADIFCONFLICT: non-integer constant
// SKIPPED const REGSTR_VAL_PORTSUBCLASS: non-integer constant
// SKIPPED const REGSTR_VAL_NETCLEAN: non-integer constant
// SKIPPED const REGSTR_VAL_IDE_NO_SERIALIZE: non-integer constant
// SKIPPED const REGSTR_VAL_NOCMOSORFDPT: non-integer constant
// SKIPPED const REGSTR_VAL_COMVERIFYBASE: non-integer constant
// SKIPPED const REGSTR_VAL_MATCHINGDEVID: non-integer constant
// SKIPPED const REGSTR_VAL_DRIVERDATE: non-integer constant
// SKIPPED const REGSTR_VAL_DRIVERDATEDATA: non-integer constant
// SKIPPED const REGSTR_VAL_DRIVERVERSION: non-integer constant
// SKIPPED const REGSTR_VAL_LOCATION_INFORMATION_OVERRIDE: non-integer constant
// SKIPPED const REGSTR_KEY_OVERRIDE: non-integer constant
// SKIPPED const REGSTR_VAL_CONFIGMG: non-integer constant
// SKIPPED const REGSTR_VAL_SYSDM: non-integer constant
// SKIPPED const REGSTR_VAL_SYSDMFUNC: non-integer constant
// SKIPPED const REGSTR_VAL_PRIVATE: non-integer constant
// SKIPPED const REGSTR_VAL_PRIVATEFUNC: non-integer constant
// SKIPPED const REGSTR_VAL_DETECT: non-integer constant
// SKIPPED const REGSTR_VAL_DETECTFUNC: non-integer constant
// SKIPPED const REGSTR_VAL_ASKFORCONFIG: non-integer constant
// SKIPPED const REGSTR_VAL_ASKFORCONFIGFUNC: non-integer constant
// SKIPPED const REGSTR_VAL_WAITFORUNDOCK: non-integer constant
// SKIPPED const REGSTR_VAL_WAITFORUNDOCKFUNC: non-integer constant
// SKIPPED const REGSTR_VAL_REMOVEROMOKAY: non-integer constant
// SKIPPED const REGSTR_VAL_REMOVEROMOKAYFUNC: non-integer constant
// SKIPPED const REGSTR_VAL_CURCONFIG: non-integer constant
// SKIPPED const REGSTR_VAL_FRIENDLYNAME: non-integer constant
// SKIPPED const REGSTR_VAL_CURRENTCONFIG: non-integer constant
// SKIPPED const REGSTR_VAL_MAP: non-integer constant
// SKIPPED const REGSTR_VAL_ID: non-integer constant
// SKIPPED const REGSTR_VAL_DOCKED: non-integer constant
// SKIPPED const REGSTR_VAL_CHECKSUM: non-integer constant
// SKIPPED const REGSTR_VAL_HWDETECT: non-integer constant
// SKIPPED const REGSTR_VAL_INHIBITRESULTS: non-integer constant
// SKIPPED const REGSTR_VAL_PROFILEFLAGS: non-integer constant
// SKIPPED const REGSTR_KEY_PCMCIA: non-integer constant
// SKIPPED const REGSTR_KEY_PCUNKNOWN: non-integer constant
// SKIPPED const REGSTR_VAL_PCSSDRIVER: non-integer constant
// SKIPPED const REGSTR_KEY_PCMTD: non-integer constant
// SKIPPED const REGSTR_VAL_PCMTDRIVER: non-integer constant
// SKIPPED const REGSTR_VAL_HARDWAREID: non-integer constant
// SKIPPED const REGSTR_VAL_INSTALLER: non-integer constant
// SKIPPED const REGSTR_VAL_INSTALLER_32: non-integer constant
// SKIPPED const REGSTR_VAL_INSICON: non-integer constant
// SKIPPED const REGSTR_VAL_ENUMPROPPAGES: non-integer constant
// SKIPPED const REGSTR_VAL_ENUMPROPPAGES_32: non-integer constant
// SKIPPED const REGSTR_VAL_BASICPROPERTIES: non-integer constant
// SKIPPED const REGSTR_VAL_BASICPROPERTIES_32: non-integer constant
// SKIPPED const REGSTR_VAL_COINSTALLERS_32: non-integer constant
// SKIPPED const REGSTR_VAL_PRIVATEPROBLEM: non-integer constant
// SKIPPED const REGSTR_KEY_CURRENT: non-integer constant
// SKIPPED const REGSTR_KEY_DEFAULT: non-integer constant
// SKIPPED const REGSTR_KEY_MODES: non-integer constant
// SKIPPED const REGSTR_VAL_MODE: non-integer constant
// SKIPPED const REGSTR_VAL_BPP: non-integer constant
// SKIPPED const REGSTR_VAL_HRES: non-integer constant
// SKIPPED const REGSTR_VAL_VRES: non-integer constant
// SKIPPED const REGSTR_VAL_FONTSIZE: non-integer constant
// SKIPPED const REGSTR_VAL_DRV: non-integer constant
// SKIPPED const REGSTR_VAL_GRB: non-integer constant
// SKIPPED const REGSTR_VAL_VDD: non-integer constant
// SKIPPED const REGSTR_VAL_VER: non-integer constant
// SKIPPED const REGSTR_VAL_MAXRES: non-integer constant
// SKIPPED const REGSTR_VAL_DPMS: non-integer constant
// SKIPPED const REGSTR_VAL_RESUMERESET: non-integer constant
// SKIPPED const REGSTR_KEY_SYSTEM: non-integer constant
// SKIPPED const REGSTR_KEY_USER: non-integer constant
// SKIPPED const REGSTR_VAL_DPI: non-integer constant
// SKIPPED const REGSTR_VAL_PCICOPTIONS: non-integer constant
#define PCIC_DEFAULT_IRQMASK 0x4eb8
#define PCIC_DEFAULT_NUMSOCKETS 0x0
// SKIPPED const REGSTR_VAL_PCICIRQMAP: non-integer constant
// SKIPPED const REGSTR_PATH_APPEARANCE: non-integer constant
// SKIPPED const REGSTR_PATH_LOOKSCHEMES: non-integer constant
// SKIPPED const REGSTR_VAL_CUSTOMCOLORS: non-integer constant
// SKIPPED const REGSTR_PATH_SCREENSAVE: non-integer constant
// SKIPPED const REGSTR_VALUE_USESCRPASSWORD: non-integer constant
// SKIPPED const REGSTR_VALUE_SCRPASSWORD: non-integer constant
// SKIPPED const REGSTR_VALUE_LOWPOWERTIMEOUT: non-integer constant
// SKIPPED const REGSTR_VALUE_POWEROFFTIMEOUT: non-integer constant
// SKIPPED const REGSTR_VALUE_LOWPOWERACTIVE: non-integer constant
// SKIPPED const REGSTR_VALUE_POWEROFFACTIVE: non-integer constant
// SKIPPED const REGSTR_PATH_WINDOWSAPPLETS: non-integer constant
// SKIPPED const REGSTR_PATH_SYSTRAY: non-integer constant
// SKIPPED const REGSTR_VAL_SYSTRAYSVCS: non-integer constant
// SKIPPED const REGSTR_VAL_SYSTRAYBATFLAGS: non-integer constant
// SKIPPED const REGSTR_VAL_SYSTRAYPCCARDFLAGS: non-integer constant
// SKIPPED const REGSTR_PATH_NETWORK_USERSETTINGS: non-integer constant
// SKIPPED const REGSTR_KEY_NETWORK_PERSISTENT: non-integer constant
// SKIPPED const REGSTR_KEY_NETWORK_RECENT: non-integer constant
// SKIPPED const REGSTR_VAL_REMOTE_PATH: non-integer constant
// SKIPPED const REGSTR_VAL_USER_NAME: non-integer constant
// SKIPPED const REGSTR_VAL_PROVIDER_NAME: non-integer constant
// SKIPPED const REGSTR_VAL_CONNECTION_TYPE: non-integer constant
// SKIPPED const REGSTR_VAL_UPGRADE: non-integer constant
// SKIPPED const REGSTR_KEY_LOGON: non-integer constant
// SKIPPED const REGSTR_VAL_MUSTBEVALIDATED: non-integer constant
// SKIPPED const REGSTR_VAL_RUNLOGINSCRIPT: non-integer constant
// SKIPPED const REGSTR_KEY_NETWORKPROVIDER: non-integer constant
// SKIPPED const REGSTR_VAL_AUTHENT_AGENT: non-integer constant
// SKIPPED const REGSTR_VAL_PREFREDIR: non-integer constant
// SKIPPED const REGSTR_VAL_AUTOSTART: non-integer constant
// SKIPPED const REGSTR_VAL_AUTOLOGON: non-integer constant
// SKIPPED const REGSTR_VAL_NETCARD: non-integer constant
// SKIPPED const REGSTR_VAL_TRANSPORT: non-integer constant
// SKIPPED const REGSTR_VAL_DYNAMIC: non-integer constant
// SKIPPED const REGSTR_VAL_TRANSITION: non-integer constant
// SKIPPED const REGSTR_VAL_STATICDRIVE: non-integer constant
// SKIPPED const REGSTR_VAL_LOADHI: non-integer constant
// SKIPPED const REGSTR_VAL_LOADRMDRIVERS: non-integer constant
// SKIPPED const REGSTR_VAL_SETUPN: non-integer constant
// SKIPPED const REGSTR_VAL_SETUPNPATH: non-integer constant
// SKIPPED const REGSTR_VAL_WRKGRP_FORCEMAPPING: non-integer constant
// SKIPPED const REGSTR_VAL_WRKGRP_REQUIRED: non-integer constant
// SKIPPED const REGSTR_PATH_CURRENT_CONTROL_SET: non-integer constant
// SKIPPED const REGSTR_VAL_CURRENT_USER: non-integer constant
// SKIPPED const REGSTR_PATH_PWDPROVIDER: non-integer constant
// SKIPPED const REGSTR_VAL_PWDPROVIDER_PATH: non-integer constant
// SKIPPED const REGSTR_VAL_PWDPROVIDER_DESC: non-integer constant
// SKIPPED const REGSTR_VAL_PWDPROVIDER_CHANGEPWD: non-integer constant
// SKIPPED const REGSTR_VAL_PWDPROVIDER_CHANGEPWDHWND: non-integer constant
// SKIPPED const REGSTR_VAL_PWDPROVIDER_GETPWDSTATUS: non-integer constant
// SKIPPED const REGSTR_VAL_PWDPROVIDER_ISNP: non-integer constant
// SKIPPED const REGSTR_VAL_PWDPROVIDER_CHANGEORDER: non-integer constant
// SKIPPED const REGSTR_PATH_POLICIES: non-integer constant
// SKIPPED const REGSTR_PATH_UPDATE: non-integer constant
// SKIPPED const REGSTR_VALUE_ENABLE: non-integer constant
// SKIPPED const REGSTR_VALUE_VERBOSE: non-integer constant
// SKIPPED const REGSTR_VALUE_NETPATH: non-integer constant
// SKIPPED const REGSTR_VALUE_DEFAULTLOC: non-integer constant
// SKIPPED const REGSTR_KEY_NETWORK: non-integer constant
// SKIPPED const REGSTR_KEY_PRINTERS: non-integer constant
// SKIPPED const REGSTR_KEY_WINOLDAPP: non-integer constant
// SKIPPED const REGSTR_KEY_EXPLORER: non-integer constant
// SKIPPED const REGSTR_VAL_NOFILESHARING: non-integer constant
// SKIPPED const REGSTR_VAL_NOPRINTSHARING: non-integer constant
// SKIPPED const REGSTR_VAL_NOFILESHARINGCTRL: non-integer constant
// SKIPPED const REGSTR_VAL_NOPRINTSHARINGCTRL: non-integer constant
// SKIPPED const REGSTR_VAL_HIDESHAREPWDS: non-integer constant
// SKIPPED const REGSTR_VAL_DISABLEPWDCACHING: non-integer constant
// SKIPPED const REGSTR_VAL_ALPHANUMPWDS: non-integer constant
// SKIPPED const REGSTR_VAL_NETSETUP_DISABLE: non-integer constant
// SKIPPED const REGSTR_VAL_NETSETUP_NOCONFIGPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_NETSETUP_NOIDPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_NETSETUP_NOSECURITYPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_SYSTEMCPL_NOVIRTMEMPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_SYSTEMCPL_NODEVMGRPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_SYSTEMCPL_NOCONFIGPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_SYSTEMCPL_NOFILESYSPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_DISPCPL_NODISPCPL: non-integer constant
// SKIPPED const REGSTR_VAL_DISPCPL_NOBACKGROUNDPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_DISPCPL_NOSCRSAVPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_DISPCPL_NOAPPEARANCEPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_DISPCPL_NOSETTINGSPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_SECCPL_NOSECCPL: non-integer constant
// SKIPPED const REGSTR_VAL_SECCPL_NOPWDPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_SECCPL_NOADMINPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_SECCPL_NOPROFILEPAGE: non-integer constant
// SKIPPED const REGSTR_VAL_PRINTERS_HIDETABS: non-integer constant
// SKIPPED const REGSTR_VAL_PRINTERS_NODELETE: non-integer constant
// SKIPPED const REGSTR_VAL_PRINTERS_NOADD: non-integer constant
// SKIPPED const REGSTR_VAL_WINOLDAPP_DISABLED: non-integer constant
// SKIPPED const REGSTR_VAL_WINOLDAPP_NOREALMODE: non-integer constant
// SKIPPED const REGSTR_VAL_NOENTIRENETWORK: non-integer constant
// SKIPPED const REGSTR_VAL_NOWORKGROUPCONTENTS: non-integer constant
// SKIPPED const REGSTR_VAL_UNDOCK_WITHOUT_LOGON: non-integer constant
// SKIPPED const REGSTR_VAL_MINPWDLEN: non-integer constant
// SKIPPED const REGSTR_VAL_PWDEXPIRATION: non-integer constant
// SKIPPED const REGSTR_VAL_WIN31PROVIDER: non-integer constant
// SKIPPED const REGSTR_VAL_DISABLEREGTOOLS: non-integer constant
// SKIPPED const REGSTR_PATH_WINLOGON: non-integer constant
// SKIPPED const REGSTR_VAL_LEGALNOTICECAPTION: non-integer constant
// SKIPPED const REGSTR_VAL_LEGALNOTICETEXT: non-integer constant
// SKIPPED const REGSTR_VAL_DRIVE_SPINDOWN: non-integer constant
// SKIPPED const REGSTR_VAL_SHUTDOWN_FLAGS: non-integer constant
// SKIPPED const REGSTR_VAL_RESTRICTRUN: non-integer constant
// SKIPPED const REGSTR_KEY_POL_USERS: non-integer constant
// SKIPPED const REGSTR_KEY_POL_COMPUTERS: non-integer constant
// SKIPPED const REGSTR_KEY_POL_USERGROUPS: non-integer constant
// SKIPPED const REGSTR_KEY_POL_DEFAULT: non-integer constant
// SKIPPED const REGSTR_KEY_POL_USERGROUPDATA: non-integer constant
// SKIPPED const REGSTR_PATH_TIMEZONE: non-integer constant
// SKIPPED const REGSTR_VAL_TZBIAS: non-integer constant
// SKIPPED const REGSTR_VAL_TZDLTBIAS: non-integer constant
// SKIPPED const REGSTR_VAL_TZSTDBIAS: non-integer constant
// SKIPPED const REGSTR_VAL_TZACTBIAS: non-integer constant
// SKIPPED const REGSTR_VAL_TZDLTFLAG: non-integer constant
// SKIPPED const REGSTR_VAL_TZSTDSTART: non-integer constant
// SKIPPED const REGSTR_VAL_TZDLTSTART: non-integer constant
// SKIPPED const REGSTR_VAL_TZDLTNAME: non-integer constant
// SKIPPED const REGSTR_VAL_TZSTDNAME: non-integer constant
// SKIPPED const REGSTR_VAL_TZNOCHANGESTART: non-integer constant
// SKIPPED const REGSTR_VAL_TZNOCHANGEEND: non-integer constant
// SKIPPED const REGSTR_VAL_TZNOAUTOTIME: non-integer constant
// SKIPPED const REGSTR_PATH_FLOATINGPOINTPROCESSOR: non-integer constant
// SKIPPED const REGSTR_PATH_FLOATINGPOINTPROCESSOR0: non-integer constant
// SKIPPED const REGSTR_PATH_COMPUTRNAME: non-integer constant
// SKIPPED const REGSTR_VAL_COMPUTRNAME: non-integer constant
// SKIPPED const REGSTR_PATH_SHUTDOWN: non-integer constant
// SKIPPED const REGSTR_VAL_FORCEREBOOT: non-integer constant
// SKIPPED const REGSTR_VAL_SETUPPROGRAMRAN: non-integer constant
// SKIPPED const REGSTR_VAL_DOES_POLLING: non-integer constant
// SKIPPED const REGSTR_PATH_KNOWNDLLS: non-integer constant
// SKIPPED const REGSTR_PATH_KNOWN16DLLS: non-integer constant
// SKIPPED const REGSTR_PATH_CHECKVERDLLS: non-integer constant
// SKIPPED const REGSTR_PATH_WARNVERDLLS: non-integer constant
// SKIPPED const REGSTR_PATH_HACKINIFILE: non-integer constant
// SKIPPED const REGSTR_PATH_CHECKBADAPPS: non-integer constant
// SKIPPED const REGSTR_PATH_APPPATCH: non-integer constant
// SKIPPED const REGSTR_PATH_CHECKBADAPPS400: non-integer constant
// SKIPPED const REGSTR_PATH_KNOWNVXDS: non-integer constant
// SKIPPED const REGSTR_VAL_UNINSTALLER_DISPLAYNAME: non-integer constant
// SKIPPED const REGSTR_VAL_UNINSTALLER_COMMANDLINE: non-integer constant
// SKIPPED const REGSTR_VAL_REINSTALL_DISPLAYNAME: non-integer constant
// SKIPPED const REGSTR_VAL_REINSTALL_STRING: non-integer constant
// SKIPPED const REGSTR_VAL_REINSTALL_DEVICEINSTANCEIDS: non-integer constant
// SKIPPED const REGSTR_PATH_DESKTOP: non-integer constant
// SKIPPED const REGSTR_PATH_MOUSE: non-integer constant
// SKIPPED const REGSTR_PATH_KEYBOARD: non-integer constant
// SKIPPED const REGSTR_PATH_COLORS: non-integer constant
// SKIPPED const REGSTR_PATH_SOUND: non-integer constant
// SKIPPED const REGSTR_PATH_METRICS: non-integer constant
// SKIPPED const REGSTR_PATH_ICONS: non-integer constant
// SKIPPED const REGSTR_PATH_CURSORS: non-integer constant
// SKIPPED const REGSTR_PATH_CHECKDISK: non-integer constant
// SKIPPED const REGSTR_PATH_CHECKDISKSET: non-integer constant
// SKIPPED const REGSTR_PATH_CHECKDISKUDRVS: non-integer constant
// SKIPPED const REGSTR_PATH_FAULT: non-integer constant
// SKIPPED const REGSTR_VAL_FAULT_LOGFILE: non-integer constant
// SKIPPED const REGSTR_PATH_AEDEBUG: non-integer constant
// SKIPPED const REGSTR_VAL_AEDEBUG_DEBUGGER: non-integer constant
// SKIPPED const REGSTR_VAL_AEDEBUG_AUTO: non-integer constant
// SKIPPED const REGSTR_PATH_GRPCONV: non-integer constant
// SKIPPED const REGSTR_VAL_REGITEMDELETEMESSAGE: non-integer constant
// SKIPPED const REGSTR_PATH_LASTCHECK: non-integer constant
// SKIPPED const REGSTR_PATH_LASTOPTIMIZE: non-integer constant
// SKIPPED const REGSTR_PATH_LASTBACKUP: non-integer constant
// SKIPPED const REGSTR_PATH_CHKLASTCHECK: non-integer constant
// SKIPPED const REGSTR_PATH_CHKLASTSURFAN: non-integer constant
#define DTRESULTOK 0x0
#define DTRESULTFIX 0x1
#define DTRESULTPROB 0x2
#define DTRESULTPART 0x3
// SKIPPED const REGSTR_KEY_SHARES: non-integer constant
// SKIPPED const REGSTR_VAL_SHARES_FLAGS: non-integer constant
// SKIPPED const REGSTR_VAL_SHARES_TYPE: non-integer constant
// SKIPPED const REGSTR_VAL_SHARES_PATH: non-integer constant
// SKIPPED const REGSTR_VAL_SHARES_REMARK: non-integer constant
// SKIPPED const REGSTR_VAL_SHARES_RW_PASS: non-integer constant
// SKIPPED const REGSTR_VAL_SHARES_RO_PASS: non-integer constant
// SKIPPED const REGSTR_PATH_PRINT: non-integer constant
// SKIPPED const REGSTR_PATH_PRINTERS: non-integer constant
// SKIPPED const REGSTR_PATH_PROVIDERS: non-integer constant
// SKIPPED const REGSTR_PATH_MONITORS: non-integer constant
// SKIPPED const REGSTR_PATH_ENVIRONMENTS: non-integer constant
// SKIPPED const REGSTR_VAL_START_ON_BOOT: non-integer constant
// SKIPPED const REGSTR_VAL_PRINTERS_MASK: non-integer constant
// SKIPPED const REGSTR_VAL_DOS_SPOOL_MASK: non-integer constant
// SKIPPED const REGSTR_KEY_CURRENT_ENV: non-integer constant
// SKIPPED const REGSTR_KEY_DRIVERS: non-integer constant
// SKIPPED const REGSTR_KEY_PRINT_PROC: non-integer constant
// SKIPPED const REGSTR_PATH_EVENTLABELS: non-integer constant
// SKIPPED const REGSTR_PATH_SCHEMES: non-integer constant
// SKIPPED const REGSTR_PATH_MULTIMEDIA_AUDIO: non-integer constant
// SKIPPED const REGSTR_KEY_JOYCURR: non-integer constant
// SKIPPED const REGSTR_KEY_JOYSETTINGS: non-integer constant
// SKIPPED const REGSTR_VAL_JOYUSERVALUES: non-integer constant
// SKIPPED const REGSTR_VAL_JOYCALLOUT: non-integer constant
// SKIPPED const REGSTR_VAL_JOYNCONFIG: non-integer constant
// SKIPPED const REGSTR_VAL_JOYNOEMNAME: non-integer constant
// SKIPPED const REGSTR_VAL_JOYNOEMCALLOUT: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCALLOUT: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMNAME: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMDATA: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMXYLABEL: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMZLABEL: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMRLABEL: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMPOVLABEL: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMULABEL: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMVLABEL: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMTESTMOVEDESC: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMTESTBUTTONDESC: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMTESTMOVECAP: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMTESTBUTTONCAP: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMTESTWINCAP: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCALCAP: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCALWINCAP: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL1: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL2: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL3: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL4: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL5: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL6: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL7: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL8: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL9: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL10: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL11: non-integer constant
// SKIPPED const REGSTR_VAL_JOYOEMCAL12: non-integer constant
// SKIPPED const REGSTR_VAL_AUDIO_BITMAP: non-integer constant
// SKIPPED const REGSTR_VAL_AUDIO_ICON: non-integer constant
// SKIPPED const REGSTR_PATH_DEVICEINSTALLER: non-integer constant
// SKIPPED const REGSTR_PATH_DIFX: non-integer constant
// SKIPPED const REGSTR_VAL_SEARCHOPTIONS: non-integer constant
// SKIPPED const REGSTR_PATH_BIOSINFO: non-integer constant
// SKIPPED const REGSTR_PATH_PCIIR: non-integer constant
// SKIPPED const REGSTR_VAL_OPTIONS: non-integer constant
// SKIPPED const REGSTR_VAL_STAT: non-integer constant
// SKIPPED const REGSTR_VAL_TABLE_STAT: non-integer constant
// SKIPPED const REGSTR_VAL_MINIPORT_STAT: non-integer constant
#define PIR_OPTION_ENABLED 0x1
#define PIR_OPTION_REGISTRY 0x2
#define PIR_OPTION_MSSPEC 0x4
#define PIR_OPTION_REALMODE 0x8
#define PIR_OPTION_DEFAULT 0xf
#define PIR_STATUS_ERROR 0x0
#define PIR_STATUS_ENABLED 0x1
#define PIR_STATUS_DISABLED 0x2
#define PIR_STATUS_MAX 0x3
#define PIR_STATUS_TABLE_REGISTRY 0x0
#define PIR_STATUS_TABLE_MSSPEC 0x1
#define PIR_STATUS_TABLE_REALMODE 0x2
#define PIR_STATUS_TABLE_NONE 0x3
#define PIR_STATUS_TABLE_ERROR 0x4
#define PIR_STATUS_TABLE_BAD 0x5
#define PIR_STATUS_TABLE_SUCCESS 0x6
#define PIR_STATUS_TABLE_MAX 0x7
#define PIR_STATUS_MINIPORT_NORMAL 0x0
#define PIR_STATUS_MINIPORT_COMPATIBLE 0x1
#define PIR_STATUS_MINIPORT_OVERRIDE 0x2
#define PIR_STATUS_MINIPORT_NONE 0x3
#define PIR_STATUS_MINIPORT_ERROR 0x4
#define PIR_STATUS_MINIPORT_NOKEY 0x5
#define PIR_STATUS_MINIPORT_SUCCESS 0x6
#define PIR_STATUS_MINIPORT_INVALID 0x7
#define PIR_STATUS_MINIPORT_MAX 0x8
// SKIPPED const REGSTR_PATH_LASTGOOD: non-integer constant
// SKIPPED const REGSTR_PATH_LASTGOODTMP: non-integer constant
#define LASTGOOD_OPERATION 0xff
#define LASTGOOD_OPERATION_NOPOSTPROC 0x0
#define LASTGOOD_OPERATION_DELETE 0x1
#define REG_FORCE_RESTORE 8
#define REG_WHOLE_HIVE_VOLATILE 1
#define REG_NONE 0x0
#define REG_SZ 0x1
#define REG_EXPAND_SZ 0x2
#define REG_BINARY 0x3
#define REG_DWORD 0x4
#define REG_DWORD_LITTLE_ENDIAN 0x4
#define REG_DWORD_BIG_ENDIAN 0x5
#define REG_LINK 0x6
#define REG_MULTI_SZ 0x7
#define REG_RESOURCE_LIST 0x8
#define REG_FULL_RESOURCE_DESCRIPTOR 0x9
#define REG_RESOURCE_REQUIREMENTS_LIST 0xa
#define REG_QWORD 0xb
#define REG_QWORD_LITTLE_ENDIAN 0xb
#define REG_CREATED_NEW_KEY 0x1
#define REG_OPENED_EXISTING_KEY 0x2
#define REG_NOTIFY_CHANGE_NAME 0x1
#define REG_NOTIFY_CHANGE_ATTRIBUTES 0x2
#define REG_NOTIFY_CHANGE_LAST_SET 0x4
#define REG_NOTIFY_CHANGE_SECURITY 0x8
#define REG_NOTIFY_THREAD_AGNOSTIC 0x10000000
#define RRF_RT_DWORD 0x18
#define RRF_RT_QWORD 0x48
#define RRF_RT_REG_NONE 0x1
#define RRF_RT_REG_SZ 0x2
#define RRF_RT_REG_EXPAND_SZ 0x4
#define RRF_RT_REG_BINARY 0x8
#define RRF_RT_REG_DWORD 0x10
#define RRF_RT_REG_MULTI_SZ 0x20
#define RRF_RT_REG_QWORD 0x40
#define RRF_RT_ANY 0xffff
#define RRF_SUBKEY_WOW6464KEY 0x10000
#define RRF_SUBKEY_WOW6432KEY 0x20000
#define RRF_WOW64_MASK 0x30000
#define RRF_NOEXPAND 0x10000000
#define RRF_ZEROONFAILURE 0x20000000
#define REG_STANDARD_FORMAT 0x1
#define REG_LATEST_FORMAT 0x2
#define REG_NO_COMPRESSION 0x4
#define KEY_QUERY_VALUE 0x1
#define KEY_SET_VALUE 0x2
#define KEY_CREATE_SUB_KEY 0x4
#define KEY_ENUMERATE_SUB_KEYS 0x8
#define KEY_NOTIFY 0x10
#define KEY_CREATE_LINK 0x20
#define KEY_WOW64_32KEY 0x200
#define KEY_WOW64_64KEY 0x100
#define KEY_WOW64_RES 0x300
#define KEY_READ 0x20019
#define KEY_WRITE 0x20006
#define KEY_EXECUTE 0x20019
#define KEY_ALL_ACCESS 0xf003f
#define REG_OPTION_RESERVED 0x0
#define REG_OPTION_NON_VOLATILE 0x0
#define REG_OPTION_VOLATILE 0x1
#define REG_OPTION_CREATE_LINK 0x2
#define REG_OPTION_BACKUP_RESTORE 0x4
#define REG_OPTION_OPEN_LINK 0x8
#define REG_OPTION_DONT_VIRTUALIZE 0x10

typedef struct _VALENTA {
    void* ve_valuename;
    unsigned int ve_valuelen;
    unsigned long long ve_valueptr;
    void* ve_type;
} VALENTA;

typedef struct _val_context {
    int valuelen;
    void* value_context;
    void* val_buff_ptr;
} val_context;

typedef struct _PVALUEW {
    void* pv_valuename;
    int pv_valuelen;
    void* pv_value_context;
    unsigned int pv_type;
} PVALUEW;

typedef struct _VALENTW {
    void* ve_valuename;
    unsigned int ve_valuelen;
    unsigned long long ve_valueptr;
    void* ve_type;
} VALENTW;

typedef struct _REG_PROVIDER {
    void* pi_R0_1val;
    void* pi_R0_allvals;
    void* pi_R3_1val;
    void* pi_R3_allvals;
    unsigned int pi_flags;
    void* pi_key_context;
} REG_PROVIDER;

typedef struct _HKEY {
    void* Value;
} HKEY;

typedef struct _PVALUEA {
    void* pv_valuename;
    int pv_valuelen;
    void* pv_value_context;
    unsigned int pv_type;
} PVALUEA;

typedef struct _DSKTLSYSTEMTIME {
    unsigned short wYear;
    unsigned short wMonth;
    unsigned short wDayOfWeek;
    unsigned short wDay;
    unsigned short wHour;
    unsigned short wMinute;
    unsigned short wSecond;
    unsigned short wMilliseconds;
    unsigned short wResult;
} DSKTLSYSTEMTIME;

