// Generated by entc-win32gen from `Windows.Win32.Security`.
// Do not edit by hand. Re-run the generator to refresh.

typedef unsigned char       BYTE;
typedef unsigned short      WORD;
typedef unsigned long       DWORD;
typedef unsigned long long  ULONGLONG;
typedef long                LONG;
typedef unsigned long       ULONG;
typedef int                 BOOL;
typedef void*               PVOID;
typedef void*               HANDLE;

#define SECURITY_DYNAMIC_TRACKING 0x1
#define SECURITY_STATIC_TRACKING 0x0
#define SECURITY_MAX_SID_SIZE 0x44
// SKIPPED const SE_CREATE_TOKEN_NAME: non-integer constant
// SKIPPED const SE_ASSIGNPRIMARYTOKEN_NAME: non-integer constant
// SKIPPED const SE_LOCK_MEMORY_NAME: non-integer constant
// SKIPPED const SE_INCREASE_QUOTA_NAME: non-integer constant
// SKIPPED const SE_UNSOLICITED_INPUT_NAME: non-integer constant
// SKIPPED const SE_MACHINE_ACCOUNT_NAME: non-integer constant
// SKIPPED const SE_TCB_NAME: non-integer constant
// SKIPPED const SE_SECURITY_NAME: non-integer constant
// SKIPPED const SE_TAKE_OWNERSHIP_NAME: non-integer constant
// SKIPPED const SE_LOAD_DRIVER_NAME: non-integer constant
// SKIPPED const SE_SYSTEM_PROFILE_NAME: non-integer constant
// SKIPPED const SE_SYSTEMTIME_NAME: non-integer constant
// SKIPPED const SE_PROF_SINGLE_PROCESS_NAME: non-integer constant
// SKIPPED const SE_INC_BASE_PRIORITY_NAME: non-integer constant
// SKIPPED const SE_CREATE_PAGEFILE_NAME: non-integer constant
// SKIPPED const SE_CREATE_PERMANENT_NAME: non-integer constant
// SKIPPED const SE_BACKUP_NAME: non-integer constant
// SKIPPED const SE_RESTORE_NAME: non-integer constant
// SKIPPED const SE_SHUTDOWN_NAME: non-integer constant
// SKIPPED const SE_DEBUG_NAME: non-integer constant
// SKIPPED const SE_AUDIT_NAME: non-integer constant
// SKIPPED const SE_SYSTEM_ENVIRONMENT_NAME: non-integer constant
// SKIPPED const SE_CHANGE_NOTIFY_NAME: non-integer constant
// SKIPPED const SE_REMOTE_SHUTDOWN_NAME: non-integer constant
// SKIPPED const SE_UNDOCK_NAME: non-integer constant
// SKIPPED const SE_SYNC_AGENT_NAME: non-integer constant
// SKIPPED const SE_ENABLE_DELEGATION_NAME: non-integer constant
// SKIPPED const SE_MANAGE_VOLUME_NAME: non-integer constant
// SKIPPED const SE_IMPERSONATE_NAME: non-integer constant
// SKIPPED const SE_CREATE_GLOBAL_NAME: non-integer constant
// SKIPPED const SE_TRUSTED_CREDMAN_ACCESS_NAME: non-integer constant
// SKIPPED const SE_RELABEL_NAME: non-integer constant
// SKIPPED const SE_INC_WORKING_SET_NAME: non-integer constant
// SKIPPED const SE_TIME_ZONE_NAME: non-integer constant
// SKIPPED const SE_CREATE_SYMBOLIC_LINK_NAME: non-integer constant
// SKIPPED const SE_DELEGATE_SESSION_USER_IMPERSONATE_NAME: non-integer constant
// SKIPPED const wszCERTENROLLSHAREPATH: non-integer constant
#define cwcHRESULTSTRING 0x28
// SKIPPED const szLBRACE: non-integer constant
// SKIPPED const szRBRACE: non-integer constant
// SKIPPED const wszLBRACE: non-integer constant
// SKIPPED const wszRBRACE: non-integer constant
// SKIPPED const szLPAREN: non-integer constant
// SKIPPED const szRPAREN: non-integer constant
// SKIPPED const wszLPAREN: non-integer constant
// SKIPPED const wszRPAREN: non-integer constant
#define CVT_SECONDS 0x1
#define cwcFILENAMESUFFIXMAX 0x14
// SKIPPED const wszFCSAPARM_SERVERDNSNAME: non-integer constant
// SKIPPED const wszFCSAPARM_SERVERSHORTNAME: non-integer constant
// SKIPPED const wszFCSAPARM_SANITIZEDCANAME: non-integer constant
// SKIPPED const wszFCSAPARM_CERTFILENAMESUFFIX: non-integer constant
// SKIPPED const wszFCSAPARM_DOMAINDN: non-integer constant
// SKIPPED const wszFCSAPARM_CONFIGDN: non-integer constant
// SKIPPED const wszFCSAPARM_SANITIZEDCANAMEHASH: non-integer constant
// SKIPPED const wszFCSAPARM_CRLFILENAMESUFFIX: non-integer constant
// SKIPPED const wszFCSAPARM_CRLDELTAFILENAMESUFFIX: non-integer constant
// SKIPPED const wszFCSAPARM_DSCRLATTRIBUTE: non-integer constant
// SKIPPED const wszFCSAPARM_DSCACERTATTRIBUTE: non-integer constant
// SKIPPED const wszFCSAPARM_DSUSERCERTATTRIBUTE: non-integer constant
// SKIPPED const wszFCSAPARM_DSKRACERTATTRIBUTE: non-integer constant
// SKIPPED const wszFCSAPARM_DSCROSSCERTPAIRATTRIBUTE: non-integer constant
#define SIGNING_LEVEL_FILE_CACHE_FLAG_NOT_VALIDATED 0x1
#define SIGNING_LEVEL_FILE_CACHE_FLAG_VALIDATE_ONLY 0x4
#define SIGNING_LEVEL_MICROSOFT 0x8
#define SEF_AVOID_OWNER_CHECK 0x10
#define SEF_AVOID_OWNER_RESTRICTION 0x1000
#define SEF_AVOID_PRIVILEGE_CHECK 0x8
#define SEF_DACL_AUTO_INHERIT 0x1
#define SEF_DEFAULT_DESCRIPTOR_FOR_OBJECT 0x4
#define SEF_DEFAULT_GROUP_FROM_PARENT 0x40
#define SEF_DEFAULT_OWNER_FROM_PARENT 0x20
#define SEF_MACL_NO_EXECUTE_UP 0x400
#define SEF_MACL_NO_READ_UP 0x200
#define SEF_MACL_NO_WRITE_UP 0x100
#define SEF_SACL_AUTO_INHERIT 0x2
#define TOKEN_MANDATORY_POLICY_OFF 0x0
#define TOKEN_MANDATORY_POLICY_NO_WRITE_UP 0x1
#define TOKEN_MANDATORY_POLICY_NEW_PROCESS_MIN 0x2
#define TOKEN_MANDATORY_POLICY_VALID_MASK 0x3
#define ACE_OBJECT_TYPE_PRESENT 0x1
#define ACE_INHERITED_OBJECT_TYPE_PRESENT 0x2
#define ENUM_PERIOD_INVALID -1
#define ENUM_PERIOD_SECONDS 0
#define ENUM_PERIOD_MINUTES 1
#define ENUM_PERIOD_HOURS 2
#define ENUM_PERIOD_DAYS 3
#define ENUM_PERIOD_WEEKS 4
#define ENUM_PERIOD_MONTHS 5
#define ENUM_PERIOD_YEARS 6
#define WinNullSid 0
#define WinWorldSid 1
#define WinLocalSid 2
#define WinCreatorOwnerSid 3
#define WinCreatorGroupSid 4
#define WinCreatorOwnerServerSid 5
#define WinCreatorGroupServerSid 6
#define WinNtAuthoritySid 7
#define WinDialupSid 8
#define WinNetworkSid 9
#define WinBatchSid 10
#define WinInteractiveSid 11
#define WinServiceSid 12
#define WinAnonymousSid 13
#define WinProxySid 14
#define WinEnterpriseControllersSid 15
#define WinSelfSid 16
#define WinAuthenticatedUserSid 17
#define WinRestrictedCodeSid 18
#define WinTerminalServerSid 19
#define WinRemoteLogonIdSid 20
#define WinLogonIdsSid 21
#define WinLocalSystemSid 22
#define WinLocalServiceSid 23
#define WinNetworkServiceSid 24
#define WinBuiltinDomainSid 25
#define WinBuiltinAdministratorsSid 26
#define WinBuiltinUsersSid 27
#define WinBuiltinGuestsSid 28
#define WinBuiltinPowerUsersSid 29
#define WinBuiltinAccountOperatorsSid 30
#define WinBuiltinSystemOperatorsSid 31
#define WinBuiltinPrintOperatorsSid 32
#define WinBuiltinBackupOperatorsSid 33
#define WinBuiltinReplicatorSid 34
#define WinBuiltinPreWindows2000CompatibleAccessSid 35
#define WinBuiltinRemoteDesktopUsersSid 36
#define WinBuiltinNetworkConfigurationOperatorsSid 37
#define WinAccountAdministratorSid 38
#define WinAccountGuestSid 39
#define WinAccountKrbtgtSid 40
#define WinAccountDomainAdminsSid 41
#define WinAccountDomainUsersSid 42
#define WinAccountDomainGuestsSid 43
#define WinAccountComputersSid 44
#define WinAccountControllersSid 45
#define WinAccountCertAdminsSid 46
#define WinAccountSchemaAdminsSid 47
#define WinAccountEnterpriseAdminsSid 48
#define WinAccountPolicyAdminsSid 49
#define WinAccountRasAndIasServersSid 50
#define WinNTLMAuthenticationSid 51
#define WinDigestAuthenticationSid 52
#define WinSChannelAuthenticationSid 53
#define WinThisOrganizationSid 54
#define WinOtherOrganizationSid 55
#define WinBuiltinIncomingForestTrustBuildersSid 56
#define WinBuiltinPerfMonitoringUsersSid 57
#define WinBuiltinPerfLoggingUsersSid 58
#define WinBuiltinAuthorizationAccessSid 59
#define WinBuiltinTerminalServerLicenseServersSid 60
#define WinBuiltinDCOMUsersSid 61
#define WinBuiltinIUsersSid 62
#define WinIUserSid 63
#define WinBuiltinCryptoOperatorsSid 64
#define WinUntrustedLabelSid 65
#define WinLowLabelSid 66
#define WinMediumLabelSid 67
#define WinHighLabelSid 68
#define WinSystemLabelSid 69
#define WinWriteRestrictedCodeSid 70
#define WinCreatorOwnerRightsSid 71
#define WinCacheablePrincipalsGroupSid 72
#define WinNonCacheablePrincipalsGroupSid 73
#define WinEnterpriseReadonlyControllersSid 74
#define WinAccountReadonlyControllersSid 75
#define WinBuiltinEventLogReadersGroup 76
#define WinNewEnterpriseReadonlyControllersSid 77
#define WinBuiltinCertSvcDComAccessGroup 78
#define WinMediumPlusLabelSid 79
#define WinLocalLogonSid 80
#define WinConsoleLogonSid 81
#define WinThisOrganizationCertificateSid 82
#define WinApplicationPackageAuthoritySid 83
#define WinBuiltinAnyPackageSid 84
#define WinCapabilityInternetClientSid 85
#define WinCapabilityInternetClientServerSid 86
#define WinCapabilityPrivateNetworkClientServerSid 87
#define WinCapabilityPicturesLibrarySid 88
#define WinCapabilityVideosLibrarySid 89
#define WinCapabilityMusicLibrarySid 90
#define WinCapabilityDocumentsLibrarySid 91
#define WinCapabilitySharedUserCertificatesSid 92
#define WinCapabilityEnterpriseAuthenticationSid 93
#define WinCapabilityRemovableStorageSid 94
#define WinBuiltinRDSRemoteAccessServersSid 95
#define WinBuiltinRDSEndpointServersSid 96
#define WinBuiltinRDSManagementServersSid 97
#define WinUserModeDriversSid 98
#define WinBuiltinHyperVAdminsSid 99
#define WinAccountCloneableControllersSid 100
#define WinBuiltinAccessControlAssistanceOperatorsSid 101
#define WinBuiltinRemoteManagementUsersSid 102
#define WinAuthenticationAuthorityAssertedSid 103
#define WinAuthenticationServiceAssertedSid 104
#define WinLocalAccountSid 105
#define WinLocalAccountAndAdministratorSid 106
#define WinAccountProtectedUsersSid 107
#define WinCapabilityAppointmentsSid 108
#define WinCapabilityContactsSid 109
#define WinAccountDefaultSystemManagedSid 110
#define WinBuiltinDefaultSystemManagedGroupSid 111
#define WinBuiltinStorageReplicaAdminsSid 112
#define WinAccountKeyAdminsSid 113
#define WinAccountEnterpriseKeyAdminsSid 114
#define WinAuthenticationKeyTrustSid 115
#define WinAuthenticationKeyPropertyMFASid 116
#define WinAuthenticationKeyPropertyAttestationSid 117
#define WinAuthenticationFreshKeyAuthSid 118
#define WinBuiltinDeviceOwnersSid 119
#define WinBuiltinUserModeHardwareOperatorsSid 120
#define WinBuiltinOpenSSHUsersSid 121
#define TokenElevationTypeDefault 1
#define TokenElevationTypeFull 2
#define TokenElevationTypeLimited 3
#define CLAIM_SECURITY_ATTRIBUTE_NON_INHERITABLE 0x1
#define CLAIM_SECURITY_ATTRIBUTE_VALUE_CASE_SENSITIVE 0x2
#define CLAIM_SECURITY_ATTRIBUTE_USE_FOR_DENY_ONLY 0x4
#define CLAIM_SECURITY_ATTRIBUTE_DISABLED_BY_DEFAULT 0x8
#define CLAIM_SECURITY_ATTRIBUTE_DISABLED 0x10
#define CLAIM_SECURITY_ATTRIBUTE_MANDATORY 0x20
#define DISABLE_MAX_PRIVILEGE 0x1
#define SANDBOX_INERT 0x2
#define LUA_TOKEN 0x4
#define WRITE_RESTRICTED 0x8
#define LOGON32_PROVIDER_DEFAULT 0x0
#define LOGON32_PROVIDER_WINNT50 0x3
#define LOGON32_PROVIDER_WINNT40 0x2
#define SecurityAnonymous 0
#define SecurityIdentification 1
#define SecurityImpersonation 2
#define SecurityDelegation 3
#define AuditEventObjectAccess 0
#define AuditEventDirectoryServiceAccess 1
#define SidTypeUser 1
#define SidTypeGroup 2
#define SidTypeDomain 3
#define SidTypeAlias 4
#define SidTypeWellKnownGroup 5
#define SidTypeDeletedAccount 6
#define SidTypeInvalid 7
#define SidTypeUnknown 8
#define SidTypeComputer 9
#define SidTypeLabel 10
#define SidTypeLogonSession 11
#define SE_PRIVILEGE_ENABLED 0x2
#define SE_PRIVILEGE_ENABLED_BY_DEFAULT 0x1
#define SE_PRIVILEGE_REMOVED 0x4
#define SE_PRIVILEGE_USED_FOR_ACCESS 0x80000000
#define ACL_REVISION 0x2
#define ACL_REVISION_DS 0x4
#define TokenPrimary 1
#define TokenImpersonation 2
#define TokenUser 1
#define TokenGroups 2
#define TokenPrivileges 3
#define TokenOwner 4
#define TokenPrimaryGroup 5
#define TokenDefaultDacl 6
#define TokenSource 7
#define TokenType 8
#define TokenImpersonationLevel 9
#define TokenStatistics 10
#define TokenRestrictedSids 11
#define TokenSessionId 12
#define TokenGroupsAndPrivileges 13
#define TokenSessionReference 14
#define TokenSandBoxInert 15
#define TokenAuditPolicy 16
#define TokenOrigin 17
#define TokenElevationType 18
#define TokenLinkedToken 19
#define TokenElevation 20
#define TokenHasRestrictions 21
#define TokenAccessInformation 22
#define TokenVirtualizationAllowed 23
#define TokenVirtualizationEnabled 24
#define TokenIntegrityLevel 25
#define TokenUIAccess 26
#define TokenMandatoryPolicy 27
#define TokenLogonSid 28
#define TokenIsAppContainer 29
#define TokenCapabilities 30
#define TokenAppContainerSid 31
#define TokenAppContainerNumber 32
#define TokenUserClaimAttributes 33
#define TokenDeviceClaimAttributes 34
#define TokenRestrictedUserClaimAttributes 35
#define TokenRestrictedDeviceClaimAttributes 36
#define TokenDeviceGroups 37
#define TokenRestrictedDeviceGroups 38
#define TokenSecurityAttributes 39
#define TokenIsRestricted 40
#define TokenProcessTrustLevel 41
#define TokenPrivateNameSpace 42
#define TokenSingletonAttributes 43
#define TokenBnoIsolation 44
#define TokenChildProcessFlags 45
#define TokenIsLessPrivilegedAppContainer 46
#define TokenIsSandboxed 47
#define TokenIsAppSilo 48
#define TokenLoggingInformation 49
#define TokenLearningMode 50
#define MaxTokenInfoClass 51
#define CONTAINER_INHERIT_ACE 0x2
#define FAILED_ACCESS_ACE_FLAG 0x80
#define INHERIT_ONLY_ACE 0x8
#define INHERITED_ACE 0x10
#define NO_PROPAGATE_INHERIT_ACE 0x4
#define OBJECT_INHERIT_ACE 0x1
#define SUCCESSFUL_ACCESS_ACE_FLAG 0x40
#define SUB_CONTAINERS_AND_OBJECTS_INHERIT 0x3
#define SUB_CONTAINERS_ONLY_INHERIT 0x2
#define SUB_OBJECTS_ONLY_INHERIT 0x1
#define INHERIT_NO_PROPAGATE 0x4
#define INHERIT_ONLY 0x8
#define NO_INHERITANCE 0x0
#define ATTRIBUTE_SECURITY_INFORMATION 0x20
#define BACKUP_SECURITY_INFORMATION 0x10000
#define DACL_SECURITY_INFORMATION 0x4
#define GROUP_SECURITY_INFORMATION 0x2
#define LABEL_SECURITY_INFORMATION 0x10
#define OWNER_SECURITY_INFORMATION 0x1
#define PROTECTED_DACL_SECURITY_INFORMATION 0x80000000
#define PROTECTED_SACL_SECURITY_INFORMATION 0x40000000
#define SACL_SECURITY_INFORMATION 0x8
#define SCOPE_SECURITY_INFORMATION 0x40
#define UNPROTECTED_DACL_SECURITY_INFORMATION 0x20000000
#define UNPROTECTED_SACL_SECURITY_INFORMATION 0x10000000
#define CLAIM_SECURITY_ATTRIBUTE_TYPE_INT64 0x1
#define CLAIM_SECURITY_ATTRIBUTE_TYPE_UINT64 0x2
#define CLAIM_SECURITY_ATTRIBUTE_TYPE_STRING 0x3
#define CLAIM_SECURITY_ATTRIBUTE_TYPE_OCTET_STRING 0x10
#define CLAIM_SECURITY_ATTRIBUTE_TYPE_FQBN 0x4
#define CLAIM_SECURITY_ATTRIBUTE_TYPE_SID 0x5
#define CLAIM_SECURITY_ATTRIBUTE_TYPE_BOOLEAN 0x6
#define LOGON32_LOGON_BATCH 0x4
#define LOGON32_LOGON_INTERACTIVE 0x2
#define LOGON32_LOGON_NETWORK 0x3
#define LOGON32_LOGON_NETWORK_CLEARTEXT 0x8
#define LOGON32_LOGON_NEW_CREDENTIALS 0x9
#define LOGON32_LOGON_SERVICE 0x5
#define LOGON32_LOGON_UNLOCK 0x7
#define MandatoryLevelUntrusted 0
#define MandatoryLevelLow 1
#define MandatoryLevelMedium 2
#define MandatoryLevelHigh 3
#define MandatoryLevelSystem 4
#define MandatoryLevelSecureProcess 5
#define MandatoryLevelCount 6
#define AclRevisionInformation 1
#define AclSizeInformation 2
#define TOKEN_DELETE 0x10000
#define TOKEN_READ_CONTROL 0x20000
#define TOKEN_WRITE_DAC 0x40000
#define TOKEN_WRITE_OWNER 0x80000
#define TOKEN_ACCESS_SYSTEM_SECURITY 0x1000000
#define TOKEN_ASSIGN_PRIMARY 0x1
#define TOKEN_DUPLICATE 0x2
#define TOKEN_IMPERSONATE 0x4
#define TOKEN_QUERY 0x8
#define TOKEN_QUERY_SOURCE 0x10
#define TOKEN_ADJUST_PRIVILEGES 0x20
#define TOKEN_ADJUST_GROUPS 0x40
#define TOKEN_ADJUST_DEFAULT 0x80
#define TOKEN_ADJUST_SESSIONID 0x100
#define TOKEN_READ 0x20008
#define TOKEN_WRITE 0x200e0
#define TOKEN_EXECUTE 0x20000
#define TOKEN_TRUST_CONSTRAINT_MASK 0x20018
#define TOKEN_ACCESS_PSEUDO_HANDLE_WIN8 0x18
#define TOKEN_ACCESS_PSEUDO_HANDLE 0x18
#define TOKEN_ALL_ACCESS 0xf01ff
#define SE_OWNER_DEFAULTED 0x1
#define SE_GROUP_DEFAULTED 0x2
#define SE_DACL_PRESENT 0x4
#define SE_DACL_DEFAULTED 0x8
#define SE_SACL_PRESENT 0x10
#define SE_SACL_DEFAULTED 0x20
#define SE_DACL_AUTO_INHERIT_REQ 0x100
#define SE_SACL_AUTO_INHERIT_REQ 0x200
#define SE_DACL_AUTO_INHERITED 0x400
#define SE_SACL_AUTO_INHERITED 0x800
#define SE_DACL_PROTECTED 0x1000
#define SE_SACL_PROTECTED 0x2000
#define SE_RM_CONTROL_VALID 0x4000
#define SE_SELF_RELATIVE 0x8000

typedef struct _NCRYPT_STREAM_HANDLE {
    void* Value;
} NCRYPT_STREAM_HANDLE;

typedef struct _CLAIM_SECURITY_ATTRIBUTE_FQBN_VALUE {
    unsigned long long Version;
    void* Name;
} CLAIM_SECURITY_ATTRIBUTE_FQBN_VALUE;

typedef struct _ACCESS_DENIED_OBJECT_ACE {
    void* Header;
    unsigned int Mask;
    void* Flags;
    void* ObjectType;
    void* InheritedObjectType;
    unsigned int SidStart;
} ACCESS_DENIED_OBJECT_ACE;

typedef struct _PSECURITY_DESCRIPTOR {
    void* Value;
} PSECURITY_DESCRIPTOR;

typedef struct _ACL {
    unsigned char AclRevision;
    unsigned char Sbz1;
    unsigned short AclSize;
    unsigned short AceCount;
    unsigned short Sbz2;
} ACL;

typedef struct _SYSTEM_AUDIT_CALLBACK_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} SYSTEM_AUDIT_CALLBACK_ACE;

typedef struct _TOKEN_USER_CLAIMS {
    void* UserClaims;
} TOKEN_USER_CLAIMS;

typedef struct _SYSTEM_ALARM_CALLBACK_OBJECT_ACE {
    void* Header;
    unsigned int Mask;
    void* Flags;
    void* ObjectType;
    void* InheritedObjectType;
    unsigned int SidStart;
} SYSTEM_ALARM_CALLBACK_OBJECT_ACE;

typedef struct _SYSTEM_ALARM_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} SYSTEM_ALARM_ACE;

typedef struct _ACCESS_ALLOWED_OBJECT_ACE {
    void* Header;
    unsigned int Mask;
    void* Flags;
    void* ObjectType;
    void* InheritedObjectType;
    unsigned int SidStart;
} ACCESS_ALLOWED_OBJECT_ACE;

typedef struct _TOKEN_MANDATORY_LABEL {
    void* Label;
} TOKEN_MANDATORY_LABEL;

typedef struct _LUID_AND_ATTRIBUTES {
    void* Luid;
    void* Attributes;
} LUID_AND_ATTRIBUTES;

typedef struct _CLAIM_SECURITY_ATTRIBUTES_INFORMATION {
    unsigned short Version;
    unsigned short Reserved;
    unsigned int AttributeCount;
    void* Attribute;
} CLAIM_SECURITY_ATTRIBUTES_INFORMATION;

typedef struct _ACL_SIZE_INFORMATION {
    unsigned int AceCount;
    unsigned int AclBytesInUse;
    unsigned int AclBytesFree;
} ACL_SIZE_INFORMATION;

typedef struct _TOKEN_GROUPS {
    unsigned int GroupCount;
    void* Groups[1];
} TOKEN_GROUPS;

typedef struct _LLFILETIME {
    void* Anonymous;
} LLFILETIME;

typedef struct _SID_AND_ATTRIBUTES {
    void* Sid;
    unsigned int Attributes;
} SID_AND_ATTRIBUTES;

typedef struct _TOKEN_SOURCE {
    unsigned char SourceName[8];
    void* SourceIdentifier;
} TOKEN_SOURCE;

typedef struct _SE_ACCESS_REPLY {
    unsigned int Size;
    unsigned int ResultListCount;
    void* GrantedAccess;
    void* AccessStatus;
    void* AccessReason;
    void* Privileges;
} SE_ACCESS_REPLY;

typedef struct _ACCESS_DENIED_CALLBACK_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} ACCESS_DENIED_CALLBACK_ACE;

typedef struct _SE_IMPERSONATION_STATE {
    void* Token;
    BOOL CopyOnOpen;
    BOOL EffectiveOnly;
    void* Level;
} SE_IMPERSONATION_STATE;

typedef struct _SECURITY_ATTRIBUTES {
    unsigned int nLength;
    void* lpSecurityDescriptor;
    BOOL bInheritHandle;
} SECURITY_ATTRIBUTES;

typedef struct _ACL_REVISION_INFORMATION {
    unsigned int AclRevision;
} ACL_REVISION_INFORMATION;

typedef struct _SID_AND_ATTRIBUTES_HASH {
    unsigned int SidCount;
    void* SidAttr;
    unsigned long long Hash[32];
} SID_AND_ATTRIBUTES_HASH;

typedef struct _TOKEN_OWNER {
    void* Owner;
} TOKEN_OWNER;

typedef struct _TOKEN_ELEVATION {
    unsigned int TokenIsElevated;
} TOKEN_ELEVATION;

typedef struct _SE_SID {
    void* Sid;
    unsigned char Buffer[68];
} SE_SID;

typedef struct _ACCESS_DENIED_CALLBACK_OBJECT_ACE {
    void* Header;
    unsigned int Mask;
    void* Flags;
    void* ObjectType;
    void* InheritedObjectType;
    unsigned int SidStart;
} ACCESS_DENIED_CALLBACK_OBJECT_ACE;

typedef struct _ACE_HEADER {
    unsigned char AceType;
    unsigned char AceFlags;
    unsigned short AceSize;
} ACE_HEADER;

typedef struct _PSID {
    void* Value;
} PSID;

typedef struct _SYSTEM_ALARM_CALLBACK_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} SYSTEM_ALARM_CALLBACK_ACE;

typedef struct _SECURITY_DESCRIPTOR_RELATIVE {
    unsigned char Revision;
    unsigned char Sbz1;
    void* Control;
    unsigned int Owner;
    unsigned int Group;
    unsigned int Sacl;
    unsigned int Dacl;
} SECURITY_DESCRIPTOR_RELATIVE;

typedef struct _SAFER_LEVEL_HANDLE {
    void* Value;
} SAFER_LEVEL_HANDLE;

typedef struct _ACCESS_ALLOWED_CALLBACK_OBJECT_ACE {
    void* Header;
    unsigned int Mask;
    void* Flags;
    void* ObjectType;
    void* InheritedObjectType;
    unsigned int SidStart;
} ACCESS_ALLOWED_CALLBACK_OBJECT_ACE;

typedef struct _TOKEN_PRIVILEGES {
    unsigned int PrivilegeCount;
    void* Privileges[1];
} TOKEN_PRIVILEGES;

typedef struct _TOKEN_GROUPS_AND_PRIVILEGES {
    unsigned int SidCount;
    unsigned int SidLength;
    void* Sids;
    unsigned int RestrictedSidCount;
    unsigned int RestrictedSidLength;
    void* RestrictedSids;
    unsigned int PrivilegeCount;
    unsigned int PrivilegeLength;
    void* Privileges;
    void* AuthenticationId;
} TOKEN_GROUPS_AND_PRIVILEGES;

typedef struct _TOKEN_AUDIT_POLICY {
    unsigned char PerUserPolicy[31];
} TOKEN_AUDIT_POLICY;

typedef struct _TOKEN_ORIGIN {
    void* OriginatingLogonSession;
} TOKEN_ORIGIN;

typedef struct _QUOTA_LIMITS {
    unsigned long long PagedPoolLimit;
    unsigned long long NonPagedPoolLimit;
    unsigned long long MinimumWorkingSetSize;
    unsigned long long MaximumWorkingSetSize;
    unsigned long long PagefileLimit;
    long long TimeLimit;
} QUOTA_LIMITS;

typedef struct _CLAIM_SECURITY_ATTRIBUTE_OCTET_STRING_VALUE {
    void* pValue;
    unsigned int ValueLength;
} CLAIM_SECURITY_ATTRIBUTE_OCTET_STRING_VALUE;

typedef struct _CLAIM_SECURITY_ATTRIBUTE_RELATIVE_V1 {
    unsigned int Name;
    void* ValueType;
    unsigned short Reserved;
    void* Flags;
    unsigned int ValueCount;
    void* Values;
} CLAIM_SECURITY_ATTRIBUTE_RELATIVE_V1;

typedef struct _NCRYPT_DESCRIPTOR_HANDLE {
    void* Value;
} NCRYPT_DESCRIPTOR_HANDLE;

typedef struct _ACCESS_ALLOWED_CALLBACK_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} ACCESS_ALLOWED_CALLBACK_ACE;

typedef struct _SE_SECURITY_DESCRIPTOR {
    unsigned int Size;
    unsigned int Flags;
    void* SecurityDescriptor;
} SE_SECURITY_DESCRIPTOR;

typedef struct _PRIVILEGE_SET {
    unsigned int PrivilegeCount;
    unsigned int Control;
    void* Privilege[1];
} PRIVILEGE_SET;

typedef struct _TOKEN_USER {
    void* User;
} TOKEN_USER;

typedef struct _TOKEN_DEVICE_CLAIMS {
    void* DeviceClaims;
} TOKEN_DEVICE_CLAIMS;

typedef struct _OBJECT_TYPE_LIST {
    unsigned short Level;
    unsigned short Sbz;
    void* ObjectType;
} OBJECT_TYPE_LIST;

typedef struct _SYSTEM_PROCESS_TRUST_LABEL_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} SYSTEM_PROCESS_TRUST_LABEL_ACE;

typedef struct _SE_ACCESS_REQUEST {
    unsigned int Size;
    void* SeSecurityDescriptor;
    unsigned int DesiredAccess;
    unsigned int PreviouslyGrantedAccess;
    void* PrincipalSelfSid;
    void* GenericMapping;
    unsigned int ObjectTypeListCount;
    void* ObjectTypeList;
} SE_ACCESS_REQUEST;

typedef struct _SYSTEM_ALARM_OBJECT_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int Flags;
    void* ObjectType;
    void* InheritedObjectType;
    unsigned int SidStart;
} SYSTEM_ALARM_OBJECT_ACE;

typedef struct _SYSTEM_AUDIT_CALLBACK_OBJECT_ACE {
    void* Header;
    unsigned int Mask;
    void* Flags;
    void* ObjectType;
    void* InheritedObjectType;
    unsigned int SidStart;
} SYSTEM_AUDIT_CALLBACK_OBJECT_ACE;

typedef struct _TOKEN_DEFAULT_DACL {
    void* DefaultDacl;
} TOKEN_DEFAULT_DACL;

typedef struct _SYSTEM_MANDATORY_LABEL_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} SYSTEM_MANDATORY_LABEL_ACE;

typedef struct _SYSTEM_AUDIT_OBJECT_ACE {
    void* Header;
    unsigned int Mask;
    void* Flags;
    void* ObjectType;
    void* InheritedObjectType;
    unsigned int SidStart;
} SYSTEM_AUDIT_OBJECT_ACE;

typedef struct _TOKEN_ACCESS_INFORMATION {
    void* SidHash;
    void* RestrictedSidHash;
    void* Privileges;
    void* AuthenticationId;
    void* TokenType;
    void* ImpersonationLevel;
    void* MandatoryPolicy;
    unsigned int Flags;
    unsigned int AppContainerNumber;
    void* PackageSid;
    void* CapabilitiesHash;
    void* TrustLevelSid;
    void* SecurityAttributes;
} TOKEN_ACCESS_INFORMATION;

typedef struct _TOKEN_STATISTICS {
    void* TokenId;
    void* AuthenticationId;
    long long ExpirationTime;
    void* TokenType;
    void* ImpersonationLevel;
    unsigned int DynamicCharged;
    unsigned int DynamicAvailable;
    unsigned int GroupCount;
    unsigned int PrivilegeCount;
    void* ModifiedId;
} TOKEN_STATISTICS;

typedef struct _TOKEN_MANDATORY_POLICY {
    void* Policy;
} TOKEN_MANDATORY_POLICY;

typedef struct _SID_IDENTIFIER_AUTHORITY {
    unsigned char Value[6];
} SID_IDENTIFIER_AUTHORITY;

typedef struct _SECURITY_DESCRIPTOR {
    unsigned char Revision;
    unsigned char Sbz1;
    void* Control;
    void* Owner;
    void* Group;
    void* Sacl;
    void* Dacl;
} SECURITY_DESCRIPTOR;

typedef struct _ACCESS_REASONS {
    unsigned int Data[32];
} ACCESS_REASONS;

typedef struct _SECURITY_CAPABILITIES {
    void* AppContainerSid;
    void* Capabilities;
    unsigned int CapabilityCount;
    unsigned int Reserved;
} SECURITY_CAPABILITIES;

typedef struct _ACCESS_ALLOWED_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} ACCESS_ALLOWED_ACE;

typedef struct _SYSTEM_AUDIT_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} SYSTEM_AUDIT_ACE;

typedef struct _CLAIM_SECURITY_ATTRIBUTE_V1 {
    void* Name;
    void* ValueType;
    unsigned short Reserved;
    unsigned int Flags;
    unsigned int ValueCount;
    void* Values;
} CLAIM_SECURITY_ATTRIBUTE_V1;

typedef struct _SID {
    unsigned char Revision;
    unsigned char SubAuthorityCount;
    void* IdentifierAuthority;
    unsigned int SubAuthority[1];
} SID;

typedef struct _GENERIC_MAPPING {
    unsigned int GenericRead;
    unsigned int GenericWrite;
    unsigned int GenericExecute;
    unsigned int GenericAll;
} GENERIC_MAPPING;

typedef struct _ACCESS_DENIED_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} ACCESS_DENIED_ACE;

typedef struct _TOKEN_PRIMARY_GROUP {
    void* PrimaryGroup;
} TOKEN_PRIMARY_GROUP;

typedef struct _TOKEN_CONTROL {
    void* TokenId;
    void* AuthenticationId;
    void* ModifiedId;
    void* TokenSource;
} TOKEN_CONTROL;

typedef struct _SYSTEM_SCOPED_POLICY_ID_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} SYSTEM_SCOPED_POLICY_ID_ACE;

typedef struct _SYSTEM_ACCESS_FILTER_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} SYSTEM_ACCESS_FILTER_ACE;

typedef struct _TOKEN_APPCONTAINER_INFORMATION {
    void* TokenAppContainer;
} TOKEN_APPCONTAINER_INFORMATION;

typedef struct _SECURITY_QUALITY_OF_SERVICE {
    unsigned int Length;
    void* ImpersonationLevel;
    unsigned char ContextTrackingMode;
    BOOL EffectiveOnly;
} SECURITY_QUALITY_OF_SERVICE;

typedef struct _TOKEN_LINKED_TOKEN {
    void* LinkedToken;
} TOKEN_LINKED_TOKEN;

typedef struct _SYSTEM_RESOURCE_ATTRIBUTE_ACE {
    void* Header;
    unsigned int Mask;
    unsigned int SidStart;
} SYSTEM_RESOURCE_ATTRIBUTE_ACE;

