// Generated by entc-win32gen from `Windows.Win32.System.Diagnostics.ToolHelp`.
// Do not edit by hand. Re-run the generator to refresh.

#define TH32CS_SNAPHEAPLIST 0x1
#define TH32CS_SNAPPROCESS 0x2
#define TH32CS_SNAPTHREAD 0x4
#define TH32CS_SNAPMODULE 0x8
#define TH32CS_SNAPMODULE32 0x10
#define TH32CS_SNAPALL 0xF
#define TH32CS_INHERIT 0x80000000

#define MAX_MODULE_NAME32 255

typedef struct tagPROCESSENTRY32 {
    unsigned int dwSize;
    unsigned int cntUsage;
    unsigned int th32ProcessID;
    void* th32DefaultHeapID;
    unsigned int th32ModuleID;
    unsigned int cntThreads;
    unsigned int th32ParentProcessID;
    int pcPriClassBase;
    unsigned int dwFlags;
    unsigned char szExeFile[260];
} PROCESSENTRY32;

typedef struct tagMODULEENTRY32 {
    unsigned int dwSize;
    unsigned int th32ModuleID;
    unsigned int th32ProcessID;
    unsigned int GlblcntUsage;
    unsigned int ProccntUsage;
    void* modBaseAddr;
    unsigned int modBaseSize;
    void* hModule;
    unsigned char szModule[256];
    unsigned char szExePath[260];
} MODULEENTRY32;

typedef struct tagTHREADENTRY32 {
    unsigned int dwSize;
    unsigned int cntUsage;
    unsigned int th32ThreadID;
    unsigned int th32OwnerProcessID;
    int tpBasePri;
    int tpDeltaPri;
    unsigned int dwFlags;
} THREADENTRY32;

typedef struct tagHEAPENTRY32 {
    void* dwSize;
    void* hHandle;
    void* dwAddress;
    void* dwBlockSize;
    unsigned int dwFlags;
    unsigned int dwLockCount;
    unsigned int dwResvd;
    unsigned int th32ProcessID;
    void* th32HeapID;
} HEAPENTRY32;

