// Generated by entc-win32gen from `Windows.Win32.System.WindowsProgramming`.
// Do not edit by hand. Re-run the generator to refresh.

typedef unsigned char       BYTE;
typedef unsigned short      WORD;
typedef unsigned long       DWORD;
typedef unsigned long long  ULONGLONG;
typedef long                LONG;
typedef unsigned long       ULONG;
typedef int                 BOOL;
typedef void*               PVOID;
typedef void*               HANDLE;

// SKIPPED const WLDP_DLL: non-integer constant
// SKIPPED const WLDP_GETLOCKDOWNPOLICY_FN: non-integer constant
// SKIPPED const WLDP_ISCLASSINAPPROVEDLIST_FN: non-integer constant
// SKIPPED const WLDP_SETDYNAMICCODETRUST_FN: non-integer constant
// SKIPPED const WLDP_ISDYNAMICCODEPOLICYENABLED_FN: non-integer constant
// SKIPPED const WLDP_QUERYDANAMICCODETRUST_FN: non-integer constant
// SKIPPED const WLDP_QUERYDYNAMICCODETRUST_FN: non-integer constant
// SKIPPED const WLDP_QUERYWINDOWSLOCKDOWNMODE_FN: non-integer constant
// SKIPPED const WLDP_SETWINDOWSLOCKDOWNRESTRICTION_FN: non-integer constant
// SKIPPED const WLDP_QUERYDEVICESECURITYINFORMATION_FN: non-integer constant
// SKIPPED const WLDP_QUERYWINDOWSLOCKDOWNRESTRICTION_FN: non-integer constant
// SKIPPED const WLDP_ISAPPAPPROVEDBYPOLICY_FN: non-integer constant
// SKIPPED const WLDP_QUERYPOLICYSETTINGENABLED_FN: non-integer constant
// SKIPPED const WLDP_QUERYPOLICYSETTINGENABLED2_FN: non-integer constant
// SKIPPED const WLDP_ISWCOSPRODUCTIONCONFIGURATION_FN: non-integer constant
// SKIPPED const WLDP_RESETWCOSPRODUCTIONCONFIGURATION_FN: non-integer constant
// SKIPPED const WLDP_ISPRODUCTIONCONFIGURATION_FN: non-integer constant
// SKIPPED const WLDP_RESETPRODUCTIONCONFIGURATION_FN: non-integer constant
// SKIPPED const WLDP_CANEXECUTEBUFFER_FN: non-integer constant
// SKIPPED const WLDP_CANEXECUTEFILE_FN: non-integer constant
// SKIPPED const WLDP_CANEXECUTEFILEFROMDETACHEDSIGNATURE_FN: non-integer constant
// SKIPPED const WLDP_QUERYSECURITYPOLICY_FN: non-integer constant
#define WLDP_LOCKDOWN_UNDEFINED 0x0
#define WLDP_LOCKDOWN_DEFINED_FLAG 0x80000000
#define WLDP_LOCKDOWN_CONFIG_CI_FLAG 0x1
#define WLDP_LOCKDOWN_CONFIG_CI_AUDIT_FLAG 0x2
#define WLDP_LOCKDOWN_UMCIENFORCE_FLAG 0x4
#define WLDP_LOCKDOWN_AUDIT_FLAG 0x8
#define WLDP_LOCKDOWN_EXCLUSION_FLAG 0x10
#define WLDP_LOCKDOWN_OFF 0x80000000
#define WLDP_HOST_INFORMATION_REVISION 0x1
#define WLDP_FLAGS_SKIPSIGNATUREVALIDATION 0x100
#define MAX_TDI_ENTITIES 0x1000
#define INFO_CLASS_GENERIC 0x100
#define INFO_CLASS_PROTOCOL 0x200
#define INFO_CLASS_IMPLEMENTATION 0x300
#define INFO_TYPE_PROVIDER 0x100
#define INFO_TYPE_ADDRESS_OBJECT 0x200
#define INFO_TYPE_CONNECTION 0x300
#define ENTITY_LIST_ID 0x0
#define INVALID_ENTITY_INSTANCE -1
#define CONTEXT_SIZE 0x10
#define ENTITY_TYPE_ID 0x1
#define CO_TL_NBF 0x400
#define CO_TL_SPX 0x402
#define CO_TL_TCP 0x404
#define CO_TL_SPP 0x406
#define CL_TL_NBF 0x401
#define CL_TL_UDP 0x403
#define ER_ICMP 0x380
#define CL_NL_IPX 0x301
#define CL_NL_IP 0x303
#define AT_ARP 0x280
#define AT_NULL 0x282
#define IF_GENERIC 0x200
#define IF_MIB 0x202
#define IOCTL_TDI_TL_IO_CONTROL_ENDPOINT 0x210038
#define DCI_VERSION 0x100
#define DCICREATEPRIMARYSURFACE 0x1
#define DCICREATEOFFSCREENSURFACE 0x2
#define DCICREATEOVERLAYSURFACE 0x3
#define DCIENUMSURFACE 0x4
#define DCIESCAPE 0x5
#define DCI_OK 0x0
#define DCI_FAIL_GENERIC -1
#define DCI_FAIL_UNSUPPORTEDVERSION -2
#define DCI_FAIL_INVALIDSURFACE -3
#define DCI_FAIL_UNSUPPORTED -4
#define DCI_ERR_CURRENTLYNOTAVAIL -5
#define DCI_ERR_INVALIDRECT -6
#define DCI_ERR_UNSUPPORTEDFORMAT -7
#define DCI_ERR_UNSUPPORTEDMASK -8
#define DCI_ERR_TOOBIGHEIGHT -9
#define DCI_ERR_TOOBIGWIDTH -10
#define DCI_ERR_TOOBIGSIZE -11
#define DCI_ERR_OUTOFMEMORY -12
#define DCI_ERR_INVALIDPOSITION -13
#define DCI_ERR_INVALIDSTRETCH -14
#define DCI_ERR_INVALIDCLIPLIST -15
#define DCI_ERR_SURFACEISOBSCURED -16
#define DCI_ERR_XALIGN -17
#define DCI_ERR_YALIGN -18
#define DCI_ERR_XYALIGN -19
#define DCI_ERR_WIDTHALIGN -20
#define DCI_ERR_HEIGHTALIGN -21
#define DCI_STATUS_POINTERCHANGED 0x1
#define DCI_STATUS_STRIDECHANGED 0x2
#define DCI_STATUS_FORMATCHANGED 0x4
#define DCI_STATUS_SURFACEINFOCHANGED 0x8
#define DCI_STATUS_CHROMAKEYCHANGED 0x10
#define DCI_STATUS_WASSTILLDRAWING 0x20
#define DCI_SURFACE_TYPE 0xf
#define DCI_PRIMARY 0x0
#define DCI_OFFSCREEN 0x1
#define DCI_OVERLAY 0x2
#define DCI_VISIBLE 0x10
#define DCI_CHROMAKEY 0x20
#define DCI_1632_ACCESS 0x40
#define DCI_DWORDSIZE 0x80
#define DCI_DWORDALIGN 0x100
#define DCI_WRITEONLY 0x200
#define DCI_ASYNC 0x400
#define DCI_CAN_STRETCHX 0x1000
#define DCI_CAN_STRETCHY 0x2000
#define DCI_CAN_STRETCHXN 0x4000
#define DCI_CAN_STRETCHYN 0x8000
#define DCI_CANOVERLAY 0x10000
#define FILE_FLAG_OPEN_REQUIRING_OPLOCK 0x40000
#define FILE_FLAG_IGNORE_IMPERSONATED_DEVICEMAP 0x20000
#define FILE_FLAG_DISALLOW_PATH_REDIRECTS 0x10000
#define FAIL_FAST_GENERATE_EXCEPTION_ADDRESS 0x1
#define FAIL_FAST_NO_HARD_ERROR_DLG 0x2
#define SP_SERIALCOMM 0x1
#define PST_UNSPECIFIED 0x0
#define PST_RS232 0x1
#define PST_PARALLELPORT 0x2
#define PST_RS422 0x3
#define PST_RS423 0x4
#define PST_RS449 0x5
#define PST_MODEM 0x6
#define PST_FAX 0x21
#define PST_SCANNER 0x22
#define PST_NETWORK_BRIDGE 0x100
#define PST_LAT 0x101
#define PST_TCPIP_TELNET 0x102
#define PST_X25 0x103
#define PCF_DTRDSR 0x1
#define PCF_RTSCTS 0x2
#define PCF_RLSD 0x4
#define PCF_PARITY_CHECK 0x8
#define PCF_XONXOFF 0x10
#define PCF_SETXCHAR 0x20
#define PCF_TOTALTIMEOUTS 0x40
#define PCF_INTTIMEOUTS 0x80
#define PCF_SPECIALCHARS 0x100
#define PCF_16BITMODE 0x200
#define SP_PARITY 0x1
#define SP_BAUD 0x2
#define SP_DATABITS 0x4
#define SP_STOPBITS 0x8
#define SP_HANDSHAKING 0x10
#define SP_PARITY_CHECK 0x20
#define SP_RLSD 0x40
#define BAUD_075 0x1
#define BAUD_110 0x2
#define BAUD_134_5 0x4
#define BAUD_150 0x8
#define BAUD_300 0x10
#define BAUD_600 0x20
#define BAUD_1200 0x40
#define BAUD_1800 0x80
#define BAUD_2400 0x100
#define BAUD_4800 0x200
#define BAUD_7200 0x400
#define BAUD_9600 0x800
#define BAUD_14400 0x1000
#define BAUD_19200 0x2000
#define BAUD_38400 0x4000
#define BAUD_56K 0x8000
#define BAUD_128K 0x10000
#define BAUD_115200 0x20000
#define BAUD_57600 0x40000
#define BAUD_USER 0x10000000
#define COMMPROP_INITIALIZED 0xe73cf52e
#define DTR_CONTROL_DISABLE 0x0
#define DTR_CONTROL_ENABLE 0x1
#define DTR_CONTROL_HANDSHAKE 0x2
#define RTS_CONTROL_DISABLE 0x0
#define RTS_CONTROL_ENABLE 0x1
#define RTS_CONTROL_HANDSHAKE 0x2
#define RTS_CONTROL_TOGGLE 0x3
#define GMEM_NOCOMPACT 0x10
#define GMEM_NODISCARD 0x20
#define GMEM_MODIFY 0x80
#define GMEM_DISCARDABLE 0x100
#define GMEM_NOT_BANKED 0x1000
#define GMEM_SHARE 0x2000
#define GMEM_DDESHARE 0x2000
#define GMEM_NOTIFY 0x4000
#define GMEM_LOWER 0x1000
#define GMEM_VALID_FLAGS 0x7f72
#define GMEM_INVALID_HANDLE 0x8000
#define GMEM_DISCARDED 0x4000
#define GMEM_LOCKCOUNT 0xff
#define THREAD_PRIORITY_ERROR_RETURN 0x7fffffff
#define DRIVE_UNKNOWN 0x0
#define DRIVE_NO_ROOT_DIR 0x1
#define DRIVE_REMOVABLE 0x2
#define DRIVE_FIXED 0x3
#define DRIVE_REMOTE 0x4
#define DRIVE_CDROM 0x5
#define DRIVE_RAMDISK 0x6
#define IGNORE 0x0
#define CBR_110 0x6e
#define CBR_300 0x12c
#define CBR_600 0x258
#define CBR_1200 0x4b0
#define CBR_2400 0x960
#define CBR_4800 0x12c0
#define CBR_9600 0x2580
#define CBR_14400 0x3840
#define CBR_19200 0x4b00
#define CBR_38400 0x9600
#define CBR_56000 0xdac0
#define CBR_57600 0xe100
#define CBR_115200 0x1c200
#define CBR_128000 0x1f400
#define CBR_256000 0x3e800
#define CE_TXFULL 0x100
#define CE_PTO 0x200
#define CE_IOE 0x400
#define CE_DNS 0x800
#define CE_OOP 0x1000
#define CE_MODE 0x8000
#define IE_BADID -1
#define IE_OPEN -2
#define IE_NOPEN -3
#define IE_MEMORY -4
#define IE_DEFAULT -5
#define IE_HARDWARE -10
#define IE_BYTESIZE -11
#define IE_BAUDRATE -12
#define RESETDEV 0x7
#define LPTx 0x80
#define S_QUEUEEMPTY 0x0
#define S_THRESHOLD 0x1
#define S_ALLTHRESHOLD 0x2
#define S_NORMAL 0x0
#define S_LEGATO 0x1
#define S_STACCATO 0x2
#define S_PERIOD512 0x0
#define S_PERIOD1024 0x1
#define S_PERIOD2048 0x2
#define S_PERIODVOICE 0x3
#define S_WHITE512 0x4
#define S_WHITE1024 0x5
#define S_WHITE2048 0x6
#define S_WHITEVOICE 0x7
#define S_SERDVNA -1
#define S_SEROFM -2
#define S_SERMACT -3
#define S_SERQFUL -4
#define S_SERBDNT -5
#define S_SERDLN -6
#define S_SERDCC -7
#define S_SERDTP -8
#define S_SERDVL -9
#define S_SERDMD -10
#define S_SERDSH -11
#define S_SERDPT -12
#define S_SERDFQ -13
#define S_SERDDR -14
#define S_SERDSR -15
#define S_SERDST -16
#define FS_CASE_IS_PRESERVED 0x2
#define FS_CASE_SENSITIVE 0x1
#define FS_UNICODE_STORED_ON_DISK 0x4
#define FS_PERSISTENT_ACLS 0x8
#define FS_VOL_IS_COMPRESSED 0x8000
#define FS_FILE_COMPRESSION 0x10
#define FS_FILE_ENCRYPTION 0x20000
#define OFS_MAXPATHNAME 0x80
#define MAXINTATOM 0xc000
#define SCS_32BIT_BINARY 0x0
#define SCS_DOS_BINARY 0x1
#define SCS_WOW_BINARY 0x2
#define SCS_PIF_BINARY 0x3
#define SCS_POSIX_BINARY 0x4
#define SCS_OS216_BINARY 0x5
#define SCS_64BIT_BINARY 0x6
#define SCS_THIS_PLATFORM_BINARY 0x6
#define FIBER_FLAG_FLOAT_SWITCH 0x1
#define UMS_VERSION 0x100
#define FILE_SKIP_COMPLETION_PORT_ON_SUCCESS 0x1
#define FILE_SKIP_SET_EVENT_ON_HANDLE 0x2
#define CRITICAL_SECTION_NO_DEBUG_INFO 0x1000000
#define HINSTANCE_ERROR 0x20
#define FORMAT_MESSAGE_MAX_WIDTH_MASK 0xff
#define FILE_ENCRYPTABLE 0x0
#define FILE_IS_ENCRYPTED 0x1
#define FILE_SYSTEM_ATTR 0x2
#define FILE_ROOT_DIR 0x3
#define FILE_SYSTEM_DIR 0x4
#define FILE_UNKNOWN 0x5
#define FILE_SYSTEM_NOT_SUPPORT 0x6
#define FILE_USER_DISALLOWED 0x7
#define FILE_READ_ONLY 0x8
#define FILE_DIR_DISALLOWED 0x9
#define EFS_USE_RECOVERY_KEYS 0x1
#define CREATE_FOR_IMPORT 0x1
#define CREATE_FOR_DIR 0x2
#define OVERWRITE_HIDDEN 0x4
#define EFSRPC_SECURE_ONLY 0x8
#define EFS_DROP_ALTERNATE_STREAMS 0x10
#define BACKUP_INVALID 0x0
#define BACKUP_GHOSTED_FILE_EXTENTS 0xb
#define STREAM_NORMAL_ATTRIBUTE 0x0
#define STREAM_MODIFIED_WHEN_READ 0x1
#define STREAM_CONTAINS_SECURITY 0x2
#define STREAM_CONTAINS_PROPERTIES 0x4
#define STREAM_SPARSE_ATTRIBUTE 0x8
#define STREAM_CONTAINS_GHOSTED_FILE_EXTENTS 0x10
#define STARTF_HOLOGRAPHIC 0x40000
#define SHUTDOWN_NORETRY 0x1
#define PROTECTION_LEVEL_SAME 0xffffffff
#define ATOM_FLAG_GLOBAL 0x2
// SKIPPED const GET_SYSTEM_WOW64_DIRECTORY_NAME_A_A: non-integer constant
// SKIPPED const GET_SYSTEM_WOW64_DIRECTORY_NAME_A_W: non-integer constant
// SKIPPED const GET_SYSTEM_WOW64_DIRECTORY_NAME_A_T: non-integer constant
// SKIPPED const GET_SYSTEM_WOW64_DIRECTORY_NAME_W_A: non-integer constant
// SKIPPED const GET_SYSTEM_WOW64_DIRECTORY_NAME_W_W: non-integer constant
// SKIPPED const GET_SYSTEM_WOW64_DIRECTORY_NAME_W_T: non-integer constant
// SKIPPED const GET_SYSTEM_WOW64_DIRECTORY_NAME_T_A: non-integer constant
// SKIPPED const GET_SYSTEM_WOW64_DIRECTORY_NAME_T_W: non-integer constant
// SKIPPED const GET_SYSTEM_WOW64_DIRECTORY_NAME_T_T: non-integer constant
#define BASE_SEARCH_PATH_ENABLE_SAFE_SEARCHMODE 0x1
#define BASE_SEARCH_PATH_DISABLE_SAFE_SEARCHMODE 0x10000
#define BASE_SEARCH_PATH_PERMANENT 0x8000
#define EVENTLOG_FULL_INFO 0x0
#define OPERATION_API_VERSION 0x1
#define MAX_COMPUTERNAME_LENGTH 0xf
#define LOGON32_PROVIDER_WINNT35 0x1
#define LOGON32_PROVIDER_VIRTUAL 0x4
#define LOGON_ZERO_PASSWORD_BUFFER 0x80000000
#define HW_PROFILE_GUIDLEN 0x27
#define DOCKINFO_UNDOCKED 0x1
#define DOCKINFO_DOCKED 0x2
#define DOCKINFO_USER_SUPPLIED 0x4
#define TC_NORMAL 0x0
#define TC_HARDERR 0x1
#define TC_GP_TRAP 0x2
#define TC_SIGNAL 0x3
#define AC_LINE_OFFLINE 0x0
#define AC_LINE_ONLINE 0x1
#define AC_LINE_BACKUP_POWER 0x2
#define AC_LINE_UNKNOWN 0xff
#define BATTERY_FLAG_HIGH 0x1
#define BATTERY_FLAG_LOW 0x2
#define BATTERY_FLAG_CRITICAL 0x4
#define BATTERY_FLAG_CHARGING 0x8
#define BATTERY_FLAG_NO_BATTERY 0x80
#define BATTERY_FLAG_UNKNOWN 0xff
#define BATTERY_PERCENTAGE_UNKNOWN 0xff
#define SYSTEM_STATUS_FLAG_POWER_SAVING_ON 0x1
#define BATTERY_LIFE_UNKNOWN 0xffffffff
#define ACTCTX_FLAG_PROCESSOR_ARCHITECTURE_VALID 0x1
#define ACTCTX_FLAG_LANGID_VALID 0x2
#define ACTCTX_FLAG_ASSEMBLY_DIRECTORY_VALID 0x4
#define ACTCTX_FLAG_RESOURCE_NAME_VALID 0x8
#define ACTCTX_FLAG_SET_PROCESS_DEFAULT 0x10
#define ACTCTX_FLAG_APPLICATION_NAME_VALID 0x20
#define ACTCTX_FLAG_SOURCE_IS_ASSEMBLYREF 0x40
#define ACTCTX_FLAG_HMODULE_VALID 0x80
#define DEACTIVATE_ACTCTX_FLAG_FORCE_EARLY_DEACTIVATION 0x1
#define FIND_ACTCTX_SECTION_KEY_RETURN_HACTCTX 0x1
#define FIND_ACTCTX_SECTION_KEY_RETURN_FLAGS 0x2
#define FIND_ACTCTX_SECTION_KEY_RETURN_ASSEMBLY_METADATA 0x4
#define ACTIVATION_CONTEXT_BASIC_INFORMATION_DEFINED 0x1
#define QUERY_ACTCTX_FLAG_USE_ACTIVE_ACTCTX 0x4
#define QUERY_ACTCTX_FLAG_ACTCTX_IS_HMODULE 0x8
#define QUERY_ACTCTX_FLAG_ACTCTX_IS_ADDRESS 0x10
#define QUERY_ACTCTX_FLAG_NO_ADDREF 0x80000000
#define RESTART_MAX_CMD_LINE 0x400
#define RECOVERY_DEFAULT_PING_INTERVAL 0x1388
#define FILE_RENAME_FLAG_REPLACE_IF_EXISTS 0x1
#define FILE_RENAME_FLAG_POSIX_SEMANTICS 0x2
#define FILE_RENAME_FLAG_SUPPRESS_PIN_STATE_INHERITANCE 0x4
#define STORAGE_INFO_FLAGS_ALIGNED_DEVICE 0x1
#define STORAGE_INFO_FLAGS_PARTITION_ALIGNED_ON_DEVICE 0x2
#define STORAGE_INFO_OFFSET_UNKNOWN 0xffffffff
#define REMOTE_PROTOCOL_INFO_FLAG_LOOPBACK 0x1
#define REMOTE_PROTOCOL_INFO_FLAG_OFFLINE 0x2
#define REMOTE_PROTOCOL_INFO_FLAG_PERSISTENT_HANDLE 0x4
#define RPI_FLAG_SMB2_SHARECAP_TIMEWARP 0x2
#define RPI_FLAG_SMB2_SHARECAP_DFS 0x8
#define RPI_FLAG_SMB2_SHARECAP_CONTINUOUS_AVAILABILITY 0x10
#define RPI_FLAG_SMB2_SHARECAP_SCALEOUT 0x20
#define RPI_FLAG_SMB2_SHARECAP_CLUSTER 0x40
#define RPI_SMB2_SHAREFLAG_ENCRYPT_DATA 0x1
#define RPI_SMB2_SHAREFLAG_COMPRESS_DATA 0x2
#define RPI_SMB2_FLAG_SERVERCAP_DFS 0x1
#define RPI_SMB2_FLAG_SERVERCAP_LEASING 0x2
#define RPI_SMB2_FLAG_SERVERCAP_LARGEMTU 0x4
#define RPI_SMB2_FLAG_SERVERCAP_MULTICHANNEL 0x8
#define RPI_SMB2_FLAG_SERVERCAP_PERSISTENT_HANDLES 0x10
#define RPI_SMB2_FLAG_SERVERCAP_DIRECTORY_LEASING 0x20
#define MICROSOFT_WINDOWS_WINBASE_H_DEFINE_INTERLOCKED_CPLUSPLUS_OVERLOADS 0x0
#define MICROSOFT_WINBASE_H_DEFINE_INTERLOCKED_CPLUSPLUS_OVERLOADS 0x0
#define CODEINTEGRITY_OPTION_ENABLED 0x1
#define CODEINTEGRITY_OPTION_TESTSIGN 0x2
#define CODEINTEGRITY_OPTION_UMCI_ENABLED 0x4
#define CODEINTEGRITY_OPTION_UMCI_AUDITMODE_ENABLED 0x8
#define CODEINTEGRITY_OPTION_UMCI_EXCLUSIONPATHS_ENABLED 0x10
#define CODEINTEGRITY_OPTION_TEST_BUILD 0x20
#define CODEINTEGRITY_OPTION_PREPRODUCTION_BUILD 0x40
#define CODEINTEGRITY_OPTION_DEBUGMODE_ENABLED 0x80
#define CODEINTEGRITY_OPTION_FLIGHT_BUILD 0x100
#define CODEINTEGRITY_OPTION_FLIGHTING_ENABLED 0x200
#define CODEINTEGRITY_OPTION_HVCI_KMCI_ENABLED 0x400
#define CODEINTEGRITY_OPTION_HVCI_KMCI_AUDITMODE_ENABLED 0x800
#define CODEINTEGRITY_OPTION_HVCI_KMCI_STRICTMODE_ENABLED 0x1000
#define CODEINTEGRITY_OPTION_HVCI_IUM_ENABLED 0x2000
#define FILE_MAXIMUM_DISPOSITION 0x5
#define FILE_OPEN_REMOTE_INSTANCE 0x400
#define FILE_NO_COMPRESSION 0x8000
#define FILE_OPEN_NO_RECALL 0x400000
#define FILE_VALID_OPTION_FLAGS 0xffffff
#define FILE_VALID_PIPE_OPTION_FLAGS 0x32
#define FILE_VALID_MAILSLOT_OPTION_FLAGS 0x32
#define FILE_VALID_SET_FLAGS 0x36
#define FILE_SUPERSEDED 0x0
#define FILE_OPENED 0x1
#define FILE_CREATED 0x2
#define FILE_OVERWRITTEN 0x3
#define FILE_EXISTS 0x4
#define FILE_DOES_NOT_EXIST 0x5
#define WINWATCHNOTIFY_START 0x0
#define WINWATCHNOTIFY_STOP 0x1
#define WINWATCHNOTIFY_DESTROY 0x2
#define WINWATCHNOTIFY_CHANGING 0x3
#define WINWATCHNOTIFY_CHANGED 0x4
#define RSC_FLAG_INF 0x1
#define RSC_FLAG_SKIPDISKSPACECHECK 0x2
#define RSC_FLAG_QUIET 0x4
#define RSC_FLAG_NGCONV 0x8
#define RSC_FLAG_UPDHLPDLLS 0x10
#define RSC_FLAG_DELAYREGISTEROCX 0x200
#define RSC_FLAG_SETUPAPI 0x400
#define ALINF_QUIET 0x4
#define ALINF_NGCONV 0x8
#define ALINF_UPDHLPDLLS 0x10
#define ALINF_BKINSTALL 0x20
#define ALINF_ROLLBACK 0x40
#define ALINF_CHECKBKDATA 0x80
#define ALINF_ROLLBKDOALL 0x100
#define ALINF_DELAYREGISTEROCX 0x200
#define AIF_WARNIFSKIP 0x1
#define AIF_NOSKIP 0x2
#define AIF_NOVERSIONCHECK 0x4
#define AIF_FORCE_FILE_IN_USE 0x8
#define AIF_NOOVERWRITE 0x10
#define AIF_NO_VERSION_DIALOG 0x20
#define AIF_REPLACEONLY 0x400
#define AIF_NOLANGUAGECHECK 0x10000000
#define AIF_QUIET 0x20000000
#define IE4_RESTORE 0x1
#define IE4_BACKNEW 0x2
#define IE4_NODELETENEW 0x4
#define IE4_NOMESSAGES 0x8
#define IE4_NOPROGRESS 0x10
#define IE4_NOENUMKEY 0x20
#define IE4_NO_CRC_MAPPING 0x40
#define IE4_REGSECTION 0x80
#define IE4_FRDOALL 0x100
#define IE4_UPDREFCNT 0x200
#define IE4_USEREFCNT 0x400
#define IE4_EXTRAINCREFCNT 0x800
#define IE4_REMOVREGBKDATA 0x1000
#define ARSR_RESTORE 0x1
#define ARSR_NOMESSAGES 0x8
#define ARSR_REGSECTION 0x80
#define ARSR_REMOVREGBKDATA 0x1000
// SKIPPED const REG_SAVE_LOG_KEY: non-integer constant
// SKIPPED const REG_RESTORE_LOG_KEY: non-integer constant
#define AFSR_RESTORE 0x1
#define AFSR_BACKNEW 0x2
#define AFSR_NODELETENEW 0x4
#define AFSR_NOMESSAGES 0x8
#define AFSR_NOPROGRESS 0x10
#define AFSR_UPDREFCNT 0x200
#define AFSR_USEREFCNT 0x400
#define AFSR_EXTRAINCREFCNT 0x800
#define AADBE_ADD_ENTRY 0x1
#define AADBE_DEL_ENTRY 0x2
#define ADN_DEL_IF_EMPTY 0x1
#define ADN_DONT_DEL_SUBDIRS 0x2
#define ADN_DONT_DEL_DIR 0x4
#define ADN_DEL_UNC_PATHS 0x8
#define LIS_QUIET 0x1
#define LIS_NOGRPCONV 0x2
#define RUNCMDS_QUIET 0x1
#define RUNCMDS_NOWAIT 0x2
#define RUNCMDS_DELAYPOSTCMD 0x4
#define IME_MAXPROCESS 0x20
#define CP_HWND 0x0
#define CP_OPEN 0x1
#define CP_DIRECT 0x2
#define CP_LEVEL 0x3
#define MCW_DEFAULT 0x0
#define MCW_RECT 0x1
#define MCW_WINDOW 0x2
#define MCW_SCREEN 0x4
#define MCW_VERTICAL 0x8
#define MCW_HIDDEN 0x10
#define IME_MODE_ALPHANUMERIC 0x1
#define IME_MODE_SBCSCHAR 0x2
#define IME_MODE_KATAKANA 0x2
#define IME_MODE_HIRAGANA 0x4
#define IME_MODE_HANJACONVERT 0x4
#define IME_MODE_DBCSCHAR 0x10
#define IME_MODE_ROMAN 0x20
#define IME_MODE_NOROMAN 0x40
#define IME_MODE_CODEINPUT 0x80
#define IME_MODE_NOCODEINPUT 0x100
#define IME_GETIMECAPS 0x3
#define IME_SETOPEN 0x4
#define IME_GETOPEN 0x5
#define IME_GETVERSION 0x7
#define IME_SETCONVERSIONWINDOW 0x8
#define IME_MOVEIMEWINDOW 0x8
#define IME_SETCONVERSIONMODE 0x10
#define IME_GETCONVERSIONMODE 0x11
#define IME_SET_MODE 0x12
#define IME_SENDVKEY 0x13
#define IME_ENTERWORDREGISTERMODE 0x18
#define IME_SETCONVERSIONFONTEX 0x19
#define IME_BANJAtoJUNJA 0x13
#define IME_JUNJAtoBANJA 0x14
#define IME_JOHABtoKS 0x15
#define IME_KStoJOHAB 0x16
#define IMEA_INIT 0x1
#define IMEA_NEXT 0x2
#define IMEA_PREV 0x3
#define IME_REQUEST_CONVERT 0x1
#define IME_ENABLE_CONVERT 0x2
#define INTERIM_WINDOW 0x0
#define MODE_WINDOW 0x1
#define HANJA_WINDOW 0x2
#define IME_RS_ERROR 0x1
#define IME_RS_NOIME 0x2
#define IME_RS_TOOLONG 0x5
#define IME_RS_ILLEGAL 0x6
#define IME_RS_NOTFOUND 0x7
#define IME_RS_NOROOM 0xa
#define IME_RS_DISKERROR 0xe
#define IME_RS_INVALID 0x11
#define IME_RS_NEST 0x12
#define IME_RS_SYSTEMMODAL 0x13
#define WM_IME_REPORT 0x280
#define IR_STRINGSTART 0x100
#define IR_STRINGEND 0x101
#define IR_OPENCONVERT 0x120
#define IR_CHANGECONVERT 0x121
#define IR_CLOSECONVERT 0x122
#define IR_FULLCONVERT 0x123
#define IR_IMESELECT 0x130
#define IR_STRING 0x140
#define IR_DBCSCHAR 0x160
#define IR_UNDETERMINE 0x170
#define IR_STRINGEX 0x180
#define IR_MODEINFO 0x190
#define WM_WNT_CONVERTREQUESTEX 0x109
#define WM_CONVERTREQUEST 0x10a
#define WM_CONVERTRESULT 0x10b
#define WM_INTERIM 0x10c
#define WM_IMEKEYDOWN 0x290
#define WM_IMEKEYUP 0x291
#define DELAYLOAD_GPA_FAILURE 0x4
#define DELETE_BROWSING_HISTORY_HISTORY 0x1
#define DELETE_BROWSING_HISTORY_COOKIES 0x2
#define DELETE_BROWSING_HISTORY_TIF 0x4
#define DELETE_BROWSING_HISTORY_FORMDATA 0x8
#define DELETE_BROWSING_HISTORY_PASSWORDS 0x10
#define DELETE_BROWSING_HISTORY_PRESERVEFAVORITES 0x20
#define DELETE_BROWSING_HISTORY_DOWNLOADHISTORY 0x40
#define WLDP_EXECUTION_POLICY_BLOCKED 0
#define WLDP_EXECUTION_POLICY_ALLOWED 1
#define WLDP_EXECUTION_POLICY_REQUIRE_SANDBOX 2
#define WLDP_HOST_RUNDLL32 0
#define WLDP_HOST_SVCHOST 1
#define WLDP_HOST_MAX 2
#define Mp4 0
#define Wmv 1
#define FEATURE_ENABLED_STATE_DEFAULT 0
#define FEATURE_ENABLED_STATE_DISABLED 1
#define FEATURE_ENABLED_STATE_ENABLED 2
#define WLDP_EXECUTION_EVALUATION_OPTION_NONE 0
#define WLDP_EXECUTION_EVALUATION_OPTION_EXECUTE_IN_INTERACTIVE_SESSION 1
#define GENERIC_ENTITY 0x0
#define AT_ENTITY 0x280
#define CL_NL_ENTITY 0x301
#define CO_NL_ENTITY 0x300
#define CL_TL_ENTITY 0x401
#define CO_TL_ENTITY 0x400
#define ER_ENTITY 0x380
#define IF_ENTITY 0x200
#define WLDP_POLICY_SETTING_AV_PERF_MODE 1000
#define WLDP_HOST_ID_UNKNOWN 0
#define WLDP_HOST_ID_GLOBAL 1
#define WLDP_HOST_ID_VBA 2
#define WLDP_HOST_ID_WSH 3
#define WLDP_HOST_ID_POWERSHELL 4
#define WLDP_HOST_ID_IE 5
#define WLDP_HOST_ID_MSI 6
#define WLDP_HOST_ID_ALL 7
#define WLDP_HOST_ID_MAX 8
#define WinStationInformation 8
#define EndpointIoControlType 0
#define SetSockOptIoControlType 1
#define GetSockOptIoControlType 2
#define SocketIoControlType 3
#define FEATURE_CHANGE_TIME_READ 0
#define FEATURE_CHANGE_TIME_MODULE_RELOAD 1
#define FEATURE_CHANGE_TIME_SESSION 2
#define FEATURE_CHANGE_TIME_REBOOT 3
#define Single 0
#define Multiple 1
#define DECISION_LOCATION_REFRESH_GLOBAL_DATA 0
#define DECISION_LOCATION_PARAMETER_VALIDATION 1
#define DECISION_LOCATION_AUDIT 2
#define DECISION_LOCATION_FAILED_CONVERT_GUID 3
#define DECISION_LOCATION_ENTERPRISE_DEFINED_CLASS_ID 4
#define DECISION_LOCATION_GLOBAL_BUILT_IN_LIST 5
#define DECISION_LOCATION_PROVIDER_BUILT_IN_LIST 6
#define DECISION_LOCATION_ENFORCE_STATE_LIST 7
#define DECISION_LOCATION_NOT_FOUND 8
#define DECISION_LOCATION_UNKNOWN 9
#define Browse 0
#define Linear 1
#define PhotoOrVideo 0
#define Photo 1
#define Video 2
#define VALUENAME_UNKNOWN 0
#define VALUENAME_ENTERPRISE_DEFINED_CLASS_ID 1
#define VALUENAME_BUILT_IN_LIST 2
#define WLDP_WINDOWS_LOCKDOWN_MODE_UNLOCKED 0
#define WLDP_WINDOWS_LOCKDOWN_MODE_TRIAL 1
#define WLDP_WINDOWS_LOCKDOWN_MODE_LOCKED 2
#define WLDP_WINDOWS_LOCKDOWN_MODE_MAX 3
#define SingleItem 0
#define ItemList 1
#define KEY_UNKNOWN 0
#define KEY_OVERRIDE 1
#define KEY_ALL_KEYS 2
#define WLDP_SECURE_SETTING_VALUE_TYPE_BOOLEAN 0
#define WLDP_SECURE_SETTING_VALUE_TYPE_ULONG 1
#define WLDP_SECURE_SETTING_VALUE_TYPE_BINARY 2
#define WLDP_SECURE_SETTING_VALUE_TYPE_STRING 3
#define Jpeg 0
#define Png 1
#define JpegXR 2
#define WLDP_WINDOWS_LOCKDOWN_RESTRICTION_NONE 0
#define WLDP_WINDOWS_LOCKDOWN_RESTRICTION_NOUNLOCK 1
#define WLDP_WINDOWS_LOCKDOWN_RESTRICTION_NOUNLOCK_PERMANENT 2
#define WLDP_WINDOWS_LOCKDOWN_RESTRICTION_MAX 3

typedef struct _TCP_REQUEST_QUERY_INFORMATION_EX_W2K {
    void* ID;
    unsigned char Context[16];
} TCP_REQUEST_QUERY_INFORMATION_EX_W2K;

typedef struct _ACTIVATION_CONTEXT_BASIC_INFORMATION {
    void* hActCtx;
    unsigned int dwFlags;
} ACTIVATION_CONTEXT_BASIC_INFORMATION;

typedef struct _TCP_REQUEST_QUERY_INFORMATION_EX32_XP {
    void* ID;
    unsigned int Context[4];
} TCP_REQUEST_QUERY_INFORMATION_EX32_XP;

typedef struct _LDR_DATA_TABLE_ENTRY {
    void* Reserved1[2];
    void* InMemoryOrderLinks;
    void* Reserved2[2];
    void* DllBase;
    void* Reserved3[2];
    void* FullDllName;
    unsigned char Reserved4[8];
    void* Reserved5[3];
    void* Anonymous;
    unsigned int TimeDateStamp;
} LDR_DATA_TABLE_ENTRY;

typedef struct _SYSTEM_CODEINTEGRITY_INFORMATION {
    unsigned int Length;
    unsigned int CodeIntegrityOptions;
} SYSTEM_CODEINTEGRITY_INFORMATION;

typedef struct _TCP_REQUEST_QUERY_INFORMATION_EX_XP {
    void* ID;
    unsigned long long Context[4];
} TCP_REQUEST_QUERY_INFORMATION_EX_XP;

typedef struct _DELAYLOAD_PROC_DESCRIPTOR {
    unsigned int ImportDescribedByName;
    void* Description;
} DELAYLOAD_PROC_DESCRIPTOR;

typedef struct _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION {
    long long IdleTime;
    long long KernelTime;
    long long UserTime;
    long long Reserved1[2];
    unsigned int Reserved2;
} SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION;

typedef struct _SYSTEM_HANDLECOUNT_INFORMATION {
    unsigned int ProcessCount;
    unsigned int ThreadCount;
    unsigned int HandleCount;
} SYSTEM_HANDLECOUNT_INFORMATION;

typedef struct _TDIObjectID {
    void* toi_entity;
    unsigned int toi_class;
    unsigned int toi_type;
    unsigned int toi_id;
} TDIObjectID;

typedef struct _IMAGE_THUNK_DATA64 {
    void* u1;
} IMAGE_THUNK_DATA64;

typedef struct _DCICREATEINPUT {
    void* cmd;
    unsigned int dwCompression;
    unsigned int dwMask[3];
    unsigned int dwWidth;
    unsigned int dwHeight;
    unsigned int dwDCICaps;
    unsigned int dwBitCount;
    void* lpSurface;
} DCICREATEINPUT;

typedef struct _HW_PROFILE_INFOW {
    unsigned int dwDockInfo;
    unsigned short szHwProfileGuid[39];
    unsigned short szHwProfileName[80];
} HW_PROFILE_INFOW;

typedef struct _CLIENT_ID {
    void* UniqueProcess;
    void* UniqueThread;
} CLIENT_ID;

typedef struct _WLDP_DEVICE_SECURITY_INFORMATION {
    unsigned int UnlockIdSize;
    void* UnlockId;
    unsigned int ManufacturerIDLength;
    void* ManufacturerID;
} WLDP_DEVICE_SECURITY_INFORMATION;

typedef struct _IMAGE_THUNK_DATA32 {
    void* u1;
} IMAGE_THUNK_DATA32;

// SKIPPED struct EditionUpgradeHelper: no representable fields
typedef struct _TDIEntityID {
    void* tei_entity;
    unsigned int tei_instance;
} TDIEntityID;

typedef struct _CABINFOW {
    void* pszCab;
    void* pszInf;
    void* pszSection;
    unsigned short szSrcPath[260];
    unsigned int dwFlags;
} CABINFOW;

typedef struct _SYSTEM_LOOKASIDE_INFORMATION {
    unsigned char Reserved1[32];
} SYSTEM_LOOKASIDE_INFORMATION;

typedef struct _DCICMD {
    unsigned int dwCommand;
    unsigned int dwParam1;
    unsigned int dwParam2;
    unsigned int dwVersion;
    unsigned int dwReserved;
} DCICMD;

typedef struct _PERUSERSECTIONA {
    unsigned char szGUID[59];
    unsigned char szDispName[128];
    unsigned char szLocale[10];
    unsigned char szStub[1040];
    unsigned char szVersion[32];
    unsigned char szCompID[128];
    unsigned int dwIsInstalled;
    BOOL bRollback;
} PERUSERSECTIONA;

typedef struct _WLDP_HOST_INFORMATION {
    unsigned int dwRevision;
    void* dwHostId;
    void* szSource;
    void* hSource;
} WLDP_HOST_INFORMATION;

typedef struct _STRENTRYW {
    void* pszName;
    void* pszValue;
} STRENTRYW;

// SKIPPED struct CameraUIControl: no representable fields
typedef struct _SYSTEM_BASICPROCESS_INFORMATION {
    unsigned int NextEntryOffset;
    void* UniqueProcessId;
    void* InheritedFromUniqueProcessId;
    unsigned long long SequenceNumber;
    void* ImageName;
} SYSTEM_BASICPROCESS_INFORMATION;

typedef struct _STRINGEXSTRUCT {
    unsigned int dwSize;
    unsigned int uDeterminePos;
    unsigned int uDetermineDelimPos;
    unsigned int uYomiPos;
    unsigned int uYomiDelimPos;
} STRINGEXSTRUCT;

typedef struct _DELAYLOAD_INFO {
    unsigned int Size;
    void* DelayloadDescriptor;
    void* ThunkAddress;
    void* TargetDllName;
    void* TargetApiDescriptor;
    void* TargetModuleBase;
    void* Unused;
    unsigned int LastError;
} DELAYLOAD_INFO;

typedef struct _DELAYLOAD_INFO {
    unsigned int Size;
    void* DelayloadDescriptor;
    void* ThunkAddress;
    void* TargetDllName;
    void* TargetApiDescriptor;
    void* TargetModuleBase;
    void* Unused;
    unsigned int LastError;
} DELAYLOAD_INFO;

typedef struct _STRTABLEA {
    unsigned int cEntries;
    void* pse;
} STRTABLEA;

// SKIPPED struct DefaultBrowserSyncSettings: no representable fields
typedef struct _IMEPROW {
    void* hWnd;
    void* InstDate;
    unsigned int wVersion;
    unsigned short szDescription[50];
    unsigned short szName[80];
    unsigned short szOptions[30];
} IMEPROW;

typedef struct _SYSTEM_INTERRUPT_INFORMATION {
    unsigned char Reserved1[24];
} SYSTEM_INTERRUPT_INFORMATION;

typedef struct _PROCESS_CREATION_SVE_VECTOR_LENGTH {
    unsigned int Data;
    void* Anonymous;
} PROCESS_CREATION_SVE_VECTOR_LENGTH;

typedef struct _ACTCTX_SECTION_KEYED_DATA_2600 {
    unsigned int cbSize;
    unsigned int ulDataFormatVersion;
    void* lpData;
    unsigned int ulLength;
    void* lpSectionGlobalData;
    unsigned int ulSectionGlobalDataLength;
    void* lpSectionBase;
    unsigned int ulSectionTotalLength;
    void* hActCtx;
    unsigned int ulAssemblyRosterIndex;
} ACTCTX_SECTION_KEYED_DATA_2600;

typedef struct _SYSTEM_PROCESS_INFORMATION {
    unsigned int NextEntryOffset;
    unsigned int NumberOfThreads;
    unsigned char Reserved1[48];
    void* ImageName;
    int BasePriority;
    void* UniqueProcessId;
    void* Reserved2;
    unsigned int HandleCount;
    unsigned int SessionId;
    void* Reserved3;
    unsigned long long PeakVirtualSize;
    unsigned long long VirtualSize;
    unsigned int Reserved4;
    unsigned long long PeakWorkingSetSize;
    unsigned long long WorkingSetSize;
    void* Reserved5;
    unsigned long long QuotaPagedPoolUsage;
    void* Reserved6;
    unsigned long long QuotaNonPagedPoolUsage;
    unsigned long long PagefileUsage;
    unsigned long long PeakPagefileUsage;
    unsigned long long PrivatePageCount;
    long long Reserved7[6];
} SYSTEM_PROCESS_INFORMATION;

typedef struct _PUBLIC_OBJECT_TYPE_INFORMATION {
    void* TypeName;
    unsigned int Reserved[22];
} PUBLIC_OBJECT_TYPE_INFORMATION;

typedef struct _SYSTEM_BASIC_INFORMATION {
    unsigned char Reserved1[24];
    void* Reserved2[4];
    signed char NumberOfProcessors;
} SYSTEM_BASIC_INFORMATION;

typedef struct _JIT_DEBUG_INFO {
    unsigned int dwSize;
    unsigned int dwProcessorArchitecture;
    unsigned int dwThreadID;
    unsigned int dwReserved0;
    unsigned long long lpExceptionAddress;
    unsigned long long lpExceptionRecord;
    unsigned long long lpContextRecord;
} JIT_DEBUG_INFO;

typedef struct _PERUSERSECTIONW {
    unsigned short szGUID[59];
    unsigned short szDispName[128];
    unsigned short szLocale[10];
    unsigned short szStub[1040];
    unsigned short szVersion[32];
    unsigned short szCompID[128];
    unsigned int dwIsInstalled;
    BOOL bRollback;
} PERUSERSECTIONW;

typedef struct _SYSTEM_THREAD_INFORMATION {
    long long Reserved1[3];
    unsigned int Reserved2;
    void* StartAddress;
    void* ClientId;
    int Priority;
    int BasePriority;
    unsigned int Reserved3;
    unsigned int ThreadState;
    unsigned int WaitReason;
} SYSTEM_THREAD_INFORMATION;

typedef struct _DCIOVERLAY {
    void* dciInfo;
    unsigned int dwChromakeyValue;
    unsigned int dwChromakeyMask;
} DCIOVERLAY;

typedef struct _DCIENUMINPUT {
    void* cmd;
    void* rSrc;
    void* rDst;
    long long EnumCallback;
    void* lpContext;
} DCIENUMINPUT;

typedef struct _CUSTOM_SYSTEM_EVENT_TRIGGER_CONFIG {
    unsigned int Size;
    void* TriggerId;
} CUSTOM_SYSTEM_EVENT_TRIGGER_CONFIG;

typedef struct _SYSTEM_REGISTRY_QUOTA_INFORMATION {
    unsigned int RegistryQuotaAllowed;
    unsigned int RegistryQuotaUsed;
    void* Reserved1;
} SYSTEM_REGISTRY_QUOTA_INFORMATION;

typedef struct _THREAD_NAME_INFORMATION {
    void* ThreadName;
} THREAD_NAME_INFORMATION;

typedef struct _IMEPROA {
    void* hWnd;
    void* InstDate;
    unsigned int wVersion;
    unsigned char szDescription[50];
    unsigned char szName[80];
    unsigned char szOptions[30];
} IMEPROA;

// SKIPPED struct EditionUpgradeBroker: no representable fields
typedef struct _STRTABLEW {
    unsigned int cEntries;
    void* pse;
} STRTABLEW;

typedef struct _HW_PROFILE_INFOA {
    unsigned int dwDockInfo;
    unsigned char szHwProfileGuid[39];
    unsigned char szHwProfileName[80];
} HW_PROFILE_INFOA;

typedef struct _PUBLIC_OBJECT_BASIC_INFORMATION {
    unsigned int Attributes;
    unsigned int GrantedAccess;
    unsigned int HandleCount;
    unsigned int PointerCount;
    unsigned int Reserved[10];
} PUBLIC_OBJECT_BASIC_INFORMATION;

typedef struct _JAVA_TRUST {
    unsigned int cbSize;
    unsigned int flag;
    BOOL fAllActiveXPermissions;
    BOOL fAllPermissions;
    unsigned int dwEncodingType;
    void* pbJavaPermissions;
    unsigned int cbJavaPermissions;
    void* pbSigner;
    unsigned int cbSigner;
    void* pwszZone;
    void* guidZone;
    int hVerify;
} JAVA_TRUST;

typedef struct _IMAGE_DELAYLOAD_DESCRIPTOR {
    void* Attributes;
    unsigned int DllNameRVA;
    unsigned int ModuleHandleRVA;
    unsigned int ImportAddressTableRVA;
    unsigned int ImportNameTableRVA;
    unsigned int BoundImportAddressTableRVA;
    unsigned int UnloadInformationTableRVA;
    unsigned int TimeDateStamp;
} IMAGE_DELAYLOAD_DESCRIPTOR;

typedef struct _ACTCTX_SECTION_KEYED_DATA_ASSEMBLY_METADATA {
    void* lpInformation;
    void* lpSectionBase;
    unsigned int ulSectionLength;
    void* lpSectionGlobalDataBase;
    unsigned int ulSectionGlobalDataLength;
} ACTCTX_SECTION_KEYED_DATA_ASSEMBLY_METADATA;

typedef struct _SYSTEM_POLICY_INFORMATION {
    void* Reserved1[2];
    unsigned int Reserved2[3];
} SYSTEM_POLICY_INFORMATION;

typedef struct _WINSTATIONINFORMATIONW {
    unsigned char Reserved2[70];
    unsigned int LogonId;
    unsigned char Reserved3[1140];
} WINSTATIONINFORMATIONW;

typedef struct _TDI_TL_IO_CONTROL_ENDPOINT {
    void* Type;
    unsigned int Level;
    void* Anonymous;
    void* InputBuffer;
    unsigned int InputBufferLength;
    void* OutputBuffer;
    unsigned int OutputBufferLength;
} TDI_TL_IO_CONTROL_ENDPOINT;

typedef struct _UNDETERMINESTRUCT {
    unsigned int dwSize;
    unsigned int uDefIMESize;
    unsigned int uDefIMEPos;
    unsigned int uUndetTextLen;
    unsigned int uUndetTextPos;
    unsigned int uUndetAttrPos;
    unsigned int uCursorPos;
    unsigned int uDeltaStart;
    unsigned int uDetermineTextLen;
    unsigned int uDetermineTextPos;
    unsigned int uDetermineDelimPos;
    unsigned int uYomiTextLen;
    unsigned int uYomiTextPos;
    unsigned int uYomiDelimPos;
} UNDETERMINESTRUCT;

typedef struct _SYSTEM_PERFORMANCE_INFORMATION {
    unsigned char Reserved1[312];
} SYSTEM_PERFORMANCE_INFORMATION;

typedef struct _SYSTEM_TIMEOFDAY_INFORMATION {
    unsigned char Reserved1[48];
} SYSTEM_TIMEOFDAY_INFORMATION;

typedef struct _SYSTEM_EXCEPTION_INFORMATION {
    unsigned char Reserved1[16];
} SYSTEM_EXCEPTION_INFORMATION;

typedef struct _CABINFOA {
    void* pszCab;
    void* pszInf;
    void* pszSection;
    unsigned char szSrcPath[260];
    unsigned int dwFlags;
} CABINFOA;

typedef struct _STRENTRYA {
    void* pszName;
    void* pszValue;
} STRENTRYA;

typedef struct _FEATURE_STATE_CHANGE_SUBSCRIPTION {
    void* Value;
} FEATURE_STATE_CHANGE_SUBSCRIPTION;

typedef struct _TCP_REQUEST_SET_INFORMATION_EX {
    void* ID;
    unsigned int BufferSize;
    unsigned char Buffer[1];
} TCP_REQUEST_SET_INFORMATION_EX;

typedef struct _DATETIME {
    unsigned short year;
    unsigned short month;
    unsigned short day;
    unsigned short hour;
    unsigned short min;
    unsigned short sec;
} DATETIME;

typedef struct _FEATURE_ERROR {
    int hr;
    unsigned short lineNumber;
    void* file;
    void* process;
    void* module;
    unsigned int callerReturnAddressOffset;
    void* callerModule;
    void* message;
    unsigned short originLineNumber;
    void* originFile;
    void* originModule;
    unsigned int originCallerReturnAddressOffset;
    void* originCallerModule;
    void* originName;
} FEATURE_ERROR;

typedef struct _HWINWATCH {
    void* Value;
} HWINWATCH;

typedef struct _DCIOFFSCREEN {
    void* dciInfo;
    long long Draw;
    long long SetClipList;
    long long SetDestination;
} DCIOFFSCREEN;

typedef struct _DCISURFACEINFO {
    unsigned int dwSize;
    unsigned int dwDCICaps;
    unsigned int dwCompression;
    unsigned int dwMask[3];
    unsigned int dwWidth;
    unsigned int dwHeight;
    int lStride;
    unsigned int dwBitCount;
    unsigned long long dwOffSurface;
    unsigned short wSelSurface;
    unsigned short wReserved;
    unsigned int dwReserved1;
    unsigned int dwReserved2;
    unsigned int dwReserved3;
    long long BeginAccess;
    long long EndAccess;
    long long DestroySurface;
} DCISURFACEINFO;

typedef struct _IMESTRUCT {
    unsigned int fnc;
    void* wParam;
    unsigned int wCount;
    unsigned int dchSource;
    unsigned int dchDest;
    void* lParam1;
    void* lParam2;
    void* lParam3;
} IMESTRUCT;

